### ISSUE TITLE
Dragging of the threshold (# of dimensions) in the PCA Widget

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#1051]
PCA Widget allows the user to manually drag the threshold in the graph. The threshold (the number of dimensions) is an integer, so it has to snap to the grid. Currently the number is rounded down, but the line can be at an arbitrary point.

**Comment by RachitKansal** [comment]
@janezd  I would like to take up this task.

**Comment by RachitKansal** [comment]
I have recreated the bug on my local machine, will send a PR soon.

**Comment by RachitKansal** [comment]
I have just made a PR https://github.com/biolab/orange3/pull/1053

**Comment by kernc** [comment]
Should the graph also color (paint) the area between? The threshold line is absolutely not visible enough.

**Comment by RachitKansal** [comment]
I think coloring can make the graph clumsy, I was thinking thickening of the line is a better option. @janezd please take a look at this screen shot, If this is better.
![snap](https://cloud.githubusercontent.com/assets/9735009/13503318/d495db02-e194-11e5-97db-646db06976fa.png)

**Comment by janezd** [comment]
It is better, in my opinion. It's something one must play with, though, to see what looks good. If I was trying to aesthetically improve the widget, I would make a dashed line instead of a solid, I would make the graph curves (the red and the greenish line) a bit thicker on the part to the left of the threshold and a bit thinner on the right. It's not really a part of this issue - the issue is fixed, I guess (this was cheap :)). But if you want you can also try to make it nicer.

@BlazZupan, how much of the control area do we actually need? I'm much in favour of getting rid of as much as we can. (See how the new Sieve looks like.) Does one ever need more than 100 components? What about changing the first box into info, and putting it below the graph. So the only way to change the number of components is to drag the line. The second box would be eliminated altogether: the data would always be normalized (does non-normal PCA make sense?) and the graph would always show up to 100 components. The buttons go at the bottom, to the right of the info. Hence, we would keep only the graph and a single-line box with info and buttons below it.

**Comment by lanzagar** [comment]
@janezd @BlazZupan 

> Does one ever need more than 100 components?

Yes, often you want all components (e.g. for comparison). If we want the graph to cover the whole range it might be better to have it in logarithmic scale (x-axis). I think it would also be acceptable to have it limited to 100 components if there is a separate option to use all components instead.

> The second box would be eliminated altogether: the data would always be normalized (does non-normal PCA make sense?) and the graph would always show up to 100 components.

It makes perfect sense and should definitely be possible. Think of gene expressions - if a gene is not differentially expressed and varies around X (e.g. 95-105) due to noise, you do not want to have its variation count as much as that of a gene which changes form unexpressed (1) to expressed (1000) due to experimental conditions. Normalization destroys this information.
Actually, until recently we did not even have the option to normalize (you could do it explicitly before PCA of course). I think we need easy access to both options.
