### ISSUE TITLE
Impute widget crashes on learner input

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#1082]
Impute widget crashes when provided with a learner input. Should automatically switch to 'Model-based imputer' and use it. Also the widget should check for model compatibility (classification or regression).

**Comment by kernc** [comment]
How to reproduce? Is this about the widget or about the class?

**Comment by ajdapretnar** [comment]
File --> Impute. Connect learner to Impute (I used Classification Tree) and select 'model-based imputer' in the widget.

**Comment by matevzkren** [comment]
Referenced in PR https://github.com/biolab/orange3/pull/1122

**Comment by lanzagar** [comment]
There are 2 pull requests addressing this issue (#1094, #1122) so let's discuss here.
Both PRs prevent the crash, but do not solve the root of the problem IMO.

Supplying a single learner will always be a problem since it cannot be used to impute all variables if data contains a mix of continuous and discrete vars.

1) I think the best solution is to allow 2 inputs for the Impute widget: Classification Learner and Regression Learner
The API should probably be similarly updated with 2 learner parameters for `impute.Model`
2) If either is not provided a default learner is used for that type
Again, the defaults should probably already be set in `impute.Model`.

Before going further, let's make sure the desired solution is specified in enough detail (@astaric, @janezd, @kernc comments welcome) and who will work on it.
@mstrazar were you working on something like this for model imputation in the past or was that different?
