### ISSUE TITLE
There is a desktop file missing in a Linux version

### ISSUE THREAD

**Issue by drws** [biolab/orange3#1190]
##### Orange version
3.3.1.dev0

##### Expected bahavior
/usr/share/applications directory is populated with a orange.desktop file providing a desktop icon on Linux machines.

##### Actual behavior
That doesn't happen - the /usr/share/applications/orange.desktop file is missing.

##### Steps to reproduce the behavior
Install Orange on a Linux machine.

**Comment by drws** [comment]
This is an example desktop file working on Arch Linux system:

    [Desktop Entry]
    Version=1.0
    Type=Application
    Name=Orange
    Exec=orange-canvas
    Terminal=false
    Icon=/usr/lib/python3.5/site-packages/Orange/canvas/icons/orange-canvas.svg
    Categories=Development;

**Comment by kernc** [comment]
@drws Thanks for reporting. Can you confirm [the latest master](https://github.com/biolab/orange3) does install the launcher correctly?

**Comment by astaric** [comment]
We had to revert the commit that installs the desktop file, because the installation procedure is not compatible with wheel packages (which are a preferred). The desktop file and an icon are still present in the repository and can be used with distribution specific installers (i.e. aur package) if someone decides to write one.
