### ISSUE TITLE
[ENH] Support for JSON in io.py

### ISSUE THREAD

**Issue by rahulroxx** [biolab/orange3#1195]
AFAIK Orange3 is not supporting JSON files . Orange3-text has support for parsing json but that is limited to NY Times Widget . I would like to work on , if it's required. :smile:

**Comment by lanzagar** [comment]
What kind of json files would you like to support? Add another data file format, for storing models, or some other type of objects?

**Comment by rahulroxx** [comment]
@lanzagar  Adding another data file format.

**Comment by lanzagar** [comment]
I presume that in that case you are targeting an existing data file format for which you want to add support.
1) Could you be more specific about which format do you want to support (name, reference, specification, links?)
2) Provide a few reasons why we would want to support it (is it widespread, do many other tools use it, which ones?)
3) What are the benefits compared with the existing formats we support.

**Comment by cheral** [comment]
Nice idea @rahulroxx 
@langazar response to most of the API calls is in json or XML format.
If we can add support to json or xml  format that would make integration API's and making widgets for various API's much easier

Like instead of adding support for NYT ( let's say Alchemy API , Semantria etc in future) separately
And writing code for each one of them separately

We can add support to json or xml 
So that same thing is used everywhere :D

**Comment by kernc** [comment]
This is a really good idea! But are the JSON or XML schemas of those APIs the same or at least compatible? How can we support this functionality in a generic, compatible way? How do we construct a structured data table from an unstructured JSON?

**Comment by rahulroxx** [comment]
I might need assistance on this .

**Comment by ajdapretnar** [comment]
@rahulroxx You can submit a PR with [WIP] tag in front and then we can all comment and give suggestions. Or just ask away here. :)

**Comment by kernc** [comment]
Will come free with pandas integration. Pandas handling of JSON is fantastic.
