### ISSUE TITLE
OpenML authentication widget

### ISSUE THREAD

**Issue by brylie** [biolab/orange3#1264]
In order to integrate with the OpenML platform, it may be useful to provide an "OpenML Authentication" module.

The basic idea, for your early feedback, is for the OpenML authentication module to show text input fields for credentials. Once a user has input the credentials, and clicked "authenticate" if necessary, the widget will pass the OpenML authentication object as an output, for other OpenML modules.
# User interface

The User Interface may need only one field:
- API Key
# Authentication Code

In order to authenticate with OpenML, use the following code:

``` py
from openml.apiconnector import APIConnector
apikey = 'Your API key'
connector = APIConnector(apikey=apikey)
```

**Comment by brylie** [comment]
The first challenge here appears to be that OpennML expects the authentication details to be stored in a text file:

> The first time, you need to set up your config file (~/.openml/config) with your API key.
>
> ```
> apikey=FILL_IN_API_KEY
> cachedir=FILL_IN_CACHE_DIR
> ```

**Comment by brylie** [comment]
After a bit of [further reading](https://openml.github.io/openml-python/usage.html#usage), I found an example of how to use the API key from code:

```py
>>> from openml.apiconnector import APIConnector
>>> apikey = 'Your API key'
>>> connector = APIConnector(apikey=apikey)
```

**Comment by brylie** [comment]
Another challenge relates to installing the OpenML library. There does not appear to be a *pip* module. Rather, the package requires [manual installation](https://openml.github.io/openml-python/index.html#installation).

How can I include the OpenML package, so that I can `import APIConnector` from within the Orange module? Should I include the output of the `setup.py install` process within the module source-code?

**Comment by ajdapretnar** [comment]
@brylie I think it's brilliant that you're tackling this. I'm sure it will help many other people with their learning. However, it might be a good idea to move the entire widget to Orange3-Prototypes [https://github.com/biolab/orange3-prototypes], since this repo is intended particularly for prototype widgets.

**Comment by astaric** [comment]
External dependencies can be specified using dependency_links option in setup.py (like this: https://github.com/astaric/orange3-prototypes/pull/1/commits/0395d4ebbe56f00cc3e78975bf715124ba322950).

This installed non-pypi dependencies when package is installed using `python setup.py install`. When packages is installed with pip, one has to pass --process-dependency-links flag to pip to allow installation of external packages.

**Comment by kernc** [comment]
Why not move the widget into a standalone [Orange3-OpenML **add-on**](
https://github.com/biolab/orange3-example-addon)?? Surely other related widgets will follow this one?

**Comment by ajdapretnar** [comment]
@brylie How are things with the OpenML project? Are there any PRs we can test? And I agree, a separate add-on is a great idea!

**Comment by brylie** [comment]
@ajdapretnar the learning curve is a bit steep for my experience, and my time availability is diminished. I will try again to make progress with this idea.

**Comment by ajdapretnar** [comment]
@brylie Hey, don't worry! We really appreciate your effort and contributions! :star: 
I just wanted to touch base and see if there's anything we can help you with. Whenever you're ready to resume this project, feel free to get back at us and ask questions!

**Comment by brylie** [comment]
Cool. I am just getting back from vacation, so am be getting back in to machine learning studies now. I need to set up a development environment on my local computer.

Is there a tutorial I can follow that shows, step-by-step, how to create an Orange3 add-on?

**Comment by ajdapretnar** [comment]
> Is there a tutorial I can follow that shows, step-by-step, how to create an Orange3 add-on?

Not as nice one as we would like, but here are some materials:
- https://github.com/biolab/orange3/wiki/Add-Ons
- https://github.com/biolab/orange3-example-addon
- http://stackoverflow.com/questions/28055333/how-to-add-add-ons-to-orange3

We would just love an updated guide if you'll get a chance to add your own experience to it. :+1:

**Comment by janezd** [comment]
In the interest of keeping the list of issues at manageable size, I'm closing this one, but keeping #1265. #1265 is small enough to be doable, and I believe the OpenML repository is big and well-organized, so it's worth investing some time into it eventually. If the widget proposed in #1265 is the only OpenML related-widget, authentication can be integrated in it.

There is also a more principled reason why I believe that we shouldn't have this widget. A widget that provides details as an output makes total sense from the technical perspective (because authentication must be shared somehow), but from the perspective of an end-user it would make a mess of unnecessary connections. If the user would be asked for a password when he uses the first of openML widgets, (s)he would understand that "Orange" asks for password which is then used in all widgets. A group of widgets can share session-wide data in another fashion, for instance a class attribute of a common base class.
