### ISSUE TITLE
multiple langguage support?

### ISSUE THREAD

**Issue by jaeho-kang** [biolab/orange3#1290]
##### Orange version

3.3.3

##### Additional info (worksheets, data, screenshots, ...)
thank you 
for develop to orange 
i wanna to make multiple language support 
ie. korean, chinese, japaness
does anyone interest it?

**Comment by ajdapretnar** [comment]
@jaeho-kang We've had a version for Japanese a while ago, but the problem here is someone needs to maintain the translation. We're continuously making changes to the software, so a translation can quickly become obsolete. If you're willing to put in all the effort of maintaining the translation, then sure, go at it. But first I would suggest you to translate the user documentation as this would probably help a lot of people understand how the program works. We've had someone expressing an interest in translating to Chinese, so perhaps you could work on Korean first. If you're up for the task, please find the files here: https://github.com/biolab/orange3/tree/master/doc/visual-programming/source/widgets
You can translate a few and then submit a PR for inspection. Thanks!
