### ISSUE TITLE
Problems loading Corpus in Text Mining on Orange 3.3.5

### ISSUE THREAD

**Issue by rmianalytics** [biolab/orange3#1369]
##### Orange version

Orange 3.3.5, git revision f97240f, using Anaconda navigator (Orange app v1.0).

##### Expected behavior
To be able to load a corpus of text files.

##### Actual behavior
Gives error message "from_file() takes 2 positional arguments but 3 were given"  and does not load. Even when trying with test datasets the issue continues. I believe the issue is only related to the Corpus widget since I can load files through the NYT widget and corpus viewer, and LDA have no issues whatsoever processing the files.
I have tried to debug myself but had no luck so far. Since I am in the middle of a project any interim solution would be greatly appreciated, even it it means implementing a change myself on the relevant .py file
 
in the previous version of Orange (3.2) it was working fine, so I guess it is just a quick fix glitch.

##### Steps to reproduce the behavior
Just open Orange and try to load a Corpus. 

##### Additional info (worksheets, data, screenshots, ...)

![capture](https://cloud.githubusercontent.com/assets/15268567/16309036/b4042e7e-393d-11e6-9b84-33a9b97bac24.JPG)

**Comment by nikicc** [comment]
@rmianalytics thanks for reporting this! This bug was already fixed a while ago but didn't yet made a new release. I everything goes well we should release a new version tomorrow.

Since you said you are happy with a quick and dirty fix you can do the following. In file `corpus.py` find method `from_file`. In this method find a line:

 ```python
table = Table.from_file(filename, wrapper)
```

and delete the `wrapper` argument. So this line should look like this:

```python
table = Table.from_file(filename)
```

Let us know if this works for you. You can also check [the commit that fixed this](https://github.com/biolab/orange3-text/commit/a66d60ab21616a3b212f0086c9256e4f197efc64).

**Comment by rmianalytics** [comment]
Many thanks! Will try it tonight, otherwise will wait for the new release tomorrow.

 

By the way, is there a possibility of implementing – as a counterpoint to LDA – a method like SVD for Topic extraction?

 

Kindest regards,

 

Rodrigo

**Comment by nikicc** [comment]
> By the way, is there a possibility of implementing – as a counterpoint to LDA – a method like SVD for Topic extraction?

This would be nice so maybe in the future. Currently we have no plans for it in near future. If you would like to work on it we are happy to help and guide you.

**Comment by ajdapretnar** [comment]
Closing the issue for the same reasons as in #1370.

@rmianalytics If you'd care to give us a hand in creating a SVD widget for Text Mining add-on, we're more than welcome to guide you. Please, send a PR to [Orange3-Text](https://github.com/biolab/orange3-text) and we'll give it a look. :smile:
