### ISSUE TITLE
CN2 Viewer doesn't output filtered data

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#1578]
Documentation says:
Selecting a rule outputs filtered data instances. These can be viewed in a :doc:\`Data Table <../data/datatable>\`.
Also there'a a signal called *filtered data*.

Upon selecting any rule in CN2 Rule Viewer, no data is sent to the output.

**Comment by janezd** [comment]
We knew this when we were merging, but decided to fix this later.

It's not a bug, it's intentional: the widget has a separate input for the data, so you can use it to filter other, independent data instances. This is nice and we should add it to the tree widget as well, but it has to fall back to the training data by default.

**Comment by ajdapretnar** [comment]
Perhaps a use-case then in the docs?
