### ISSUE TITLE
Orange fails to save data sets in the schema

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#1610]
When saving a workflow with data set that is not pre-loaded in Orange (personal data set), the data doesn't get saved (or maybe it is, but it's not loaded in the workflow). Orange defaults to iris.tab, which makes sharing of .ows useless.

Sharing of workflows with data sets that come with Orange works well.

**Comment by astaric** [comment]
Can you give me the steps needed to reproduce this? In order to share the workflow that works on custom dataset, you need to share the dataset as well as the data. As far as I know, if they are stored in the same folder (on both computers), file widget should figure it out and modify the paths accordingly.

**Comment by janezd** [comment]
The same folder or even the same folder relative to the schema file. Aleš fixed that some time ago.

**Comment by ajdapretnar** [comment]
Feature not a bug.
