### ISSUE TITLE
 Question: Orange  appropriate for "real time" data analysis from analog Arduino pins through USB port?

### ISSUE THREAD

**Issue by mcevzar** [biolab/orange3#1833]
#question 

**Goal**
For students to have a visual tool for the purpuse of classifiying human signals (EMG, ECG ect.) aka algorithm design testing on a data stream.

**Background**

- I have an EMG (electromyogram) shield on top of my Arduino through which I monitor my muscle activity.
	
- I would write a widget that would allow me to get data from a data stream aka Arduino analog pins through USB serial port (int values in range(0, 1024)).

- Next widget would allow me to visulize the data on a graph with a decent refresh rate so I could monitor my EMG signals.

![hh-controlsoftware-calibrate](https://cloud.githubusercontent.com/assets/10882533/21383730/87125a0e-c767-11e6-8a93-260665f2b824.jpg)

- Then I would write widgets for a Low Pass and Peak Detection Filter and then apply SVM for supervised learning so it would recognize
gestures based on my EMG signal filtering and classification.

### Would Orange work for my case described above or would it be too slow to use in "real time"?  I know I could import and export data, but for rapid testing I would prefer to do in on a data stream.

@kernc @janezd

**Comment by kernc** [comment]
I assume, if you introduce a new data structure adapted for work with streams of time series data, e.g. a [deque](https://docs.python.org/3/library/collections.html#collections.deque), it might work. The reading widget would construct a deque object and append readings to it. It would pass this deque through a signal to your other filtering/visualization widgets. For best (or reasonable) performance, I suppose it shouldn't re-send the signal on each reading appended, but instead the other widgets just update themselves according to the refresh rate you (the user) specify, and since all widgets are working on the exact same object, they see the new data as it is appended.
However, the widget that sends the signal to learners for training / prediction will need to construct a `Table` and re-send it via signal on each update as there are currently no sufficient streaming mechanisms in place to allow otherwise.

**Comment by mcevzar** [comment]
How much would be the biggest refresh rate?

Thank you for the reply.

**Comment by kernc** [comment]
> How much would be the biggest refresh rate?

If you mean for the first part which is signal recording into a custom deque object and visualization, as described above, then Orange will add no overhead and the limit is that of the hardware/Python/stack/implementation.

If you mean altogether, including constructing a `Table` object to send to _Predictions_ widget, the "refresh rate" should depend mostly upon the size of the data, but should definitely be much lower.

What minimum refresh rate would you expect and what use cases do you envision?

**Comment by ajdapretnar** [comment]
@mcevzar Did you manage to implement this? We'd love to hear about the results! :)
