### ISSUE TITLE
Random sample generator widget

### ISSUE THREAD

**Issue by brylie** [biolab/orange3#1847]
# User story
> As a data analyst
I would like to generate some random samples, fitted to a given distribution
so that I can visualize how well my observed data fits a general distribution

# Feature
A random sample generator widget could generate *n* samples from a selected distribution with necessary input parameters. The output data could be fed into a visualization widget, possibly allowing comparison of a general distribution with the distribution of values within an observation data set.

# Related resources
The [`np.random` module](https://docs.scipy.org/doc/numpy/reference/routines.random.html) has many types of random data generators, such as:

- [binomial](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.binomial.html#numpy.random.binomial)
- [normal](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.normal.html#numpy.random.normal)
- [poisson](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.poisson.html#numpy.random.poisson)

**Comment by janezd** [comment]
Widgets like this are easy to implement. This is dangerous since we could easily end up with hundreds and hundreds of widgets, which would confuse the users on one side, and make it a maintenance nightmare on the other.

The functionality you propose could be added to the Paint widget. This would require renaming the widget to something like *Create data*. @BlazZupan?

**Comment by brylie** [comment]
> we could easily end up with hundreds and hundreds of widgets

This is a proposal for one multi-purpose widget that would generate random samples based on the `np.random` library.

**Comment by janezd** [comment]
Sorry, I wasn't clear. With "Widgets like this" I didn't mean widgets for generating distribution samples, but simple (single multipurpose) widgets like this one. We come up with ideas for new (single) widgets every day. Since implementing a widget for a simple data manipulation or a widget that wraps a numpy or scikit function takes so little time, we have to resist the temptation to create seven new widgets a week. Many of our internal discussions are about whether a new widget is necessary or can the functionality be added to another widget, without making that widget too complicated.

This is why I think we should consider merging your suggestion into a general data creation widget. In `Paint`, we would just add a button for adding a random sample; the user would choose the distribution and its parameters in a dialog, and the widget would add a sample to the existing data in the plot.

**Comment by brylie** [comment]
Cool, so the 'Paint' widget might take on a new name, such as 'Paint/generate', to match its extended purpose?

**Comment by shivin9** [comment]
Hi @brylie,
I would like to work on this issue, can you guide me through this as I am a beginner to Orange. Also, how this package similar or different to #1849?
Thanks,
Shivin

**Comment by brylie** [comment]
Hi @shivin9, and thanks for your interest in this idea.

# Comparison with #1849
In some ways, a random sample generator is the inverse of a distribution fitting process. In effect, a random sample generator creates **new data** from a **selected, or known, distribution**. In contrast, a distribution fitting process takes **existing data** and **fits a (previously unknown) distribution**.

Random sample generator
- creates new data
- previously known (selected) distribution

Distribution fitting widget
- uses existing data
- fits a previously 'unknown' distribution

For clarification, **by 'previously unknown', I mean it was unclear how the data was distributed**. The distribution fitting widget will compare several theoretical distributions with the data, and select one that matches as closely as possible.

# Getting started
To get started, there are a few basic steps and resources:

## Read the following
- [My First Orange Widget](http://blog.biolab.si/2017/02/23/my-first-orange-widget/)
- [Widget Development](http://orange-development.readthedocs.io/)

## Consider your development strategy
There are two basic strategies to realize this idea:

1. develop a single-purpose widget
2. integrate into an existing widget

### Develop a single-purpose widget
In the case of developing a single-purpose widget, you would have the benefits of simplicity and focus. You can learn the basics of widget development, while implementing the features. This will give you a sense of the entire widget development process, which you can use as a scaffold for creating/modifying other more complicated widgets.

Developing a single-purpose widget has some perceived setbacks, namely that there is 'yet another widget'. To some extent, there are schools of thought that advocate for small, single purpose libraries and tools (or widgets) that can be loosely coupled to compose higher level functionality. There is also a benefit of having a single widget that does several things, so an end user does not have to construct a graph of widgets to do related tasks or tweak parameters.

Relevant knowledge (you can learn as you go)
- Python
- PyQt
- Orange widget development

### integrate into an existing widget
> The functionality you propose could be added to the Paint widget. This would require renaming the widget to something like Create data.
> @janezd 

Integrating with an existing widget has the benefit of keeping the orange toolbox 'clean'. It gives us an opportunity to re-think, or even re-purpose, an existing widget to be more flexible.

In terms of drawbacks, integrating with an existing widget adds to the learning curve. You will have to understand orange widget development in addition to the specific widget you are integrating:

Relevant knowledge (you can learn as you go)
- Python
- PyQt
- Orange widget development
- Specific widget functionality (integration widget)

### Choice and guidance
Both of the above cases are open-ended, and can ultimately converge. E.g. you can start with a single-purpose plugin and merge the feature into a larger plugin once you understand more about the task and widget development.

In any case, we are available for mentorship, code review, pair programming, etc.

**Comment by janezd** [comment]
I'm closing stalled issues, but this one is simple enough and useful. I vote against my idea to add this to Paint data, though, because it would add too many options. :)

I suppose the widget would generate mixtures, not single distributions. It's settings would be:

- sample size,
- distribution type (binomial, Poisson, Gaussian),
- number of components,

followed by multiple lines in which the user would specify distribution parameters for each component, e.g. mean and variance for each Gaussian.

Would we like to have multivariate Gaussian mixtures? And, huh, force the user to enter covariance matrices? Perhaps we'd limit the widget to two dimensions and simplify the GUI by presenting it as a forth distribution, that is, binomial, Poisson, Gaussian and bivariate Gaussian. We'd then have five parameters (two means, two variances and covariance) for each component.

The widget would output one or two random variables, plus a categorical variables that would indicate the component.

**Comment by ajdapretnar** [comment]
I think such a widget would be more at home in the Educational add-on. Correct me if I am wrong.

**Comment by janezd** [comment]
Such synthetic data is often used for testing new algorithms, but you're right, Orange is not used for that. Educational add-on is probably a better place. We'll discuss it tomorrow.

**Comment by janezd** [comment]
Decision: this goes to Educational add-on. I'm still keeping the issue here, otherwise we'll forget it.

**Comment by janezd** [comment]
Continued in https://github.com/biolab/orange3-educational/pull/70.
