### ISSUE TITLE
Port and redesign Leban's modules behind most visualizations

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#19]
This is a big task, not suitable for retreat. It requires thinking about what is needed by most visualization widgets, and probably also have the SQL-based storage in mind. Probably a job for Aleš.

**Comment by kernc** [comment]
I have no idea what this issue is about, but I nevertheless give a technically sound vote to ...

# matplotlib

Matplotlib is the Python standard for 2D scientific plots. It comes with [many kinds of plots out of the box](http://matplotlib.org/gallery.html), most other scientific Python tools [play along well with it](docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.cluster.hierarchy.dendrogram.html), it has [a mature, stable, well-designed, extensible object-oriented architecture](http://www.aosabook.org/en/matplotlib.html), easy to develop (and release) [add-ons upon it](https://pypi.python.org/pypi?%3Aaction=search&term=matplotlib&submit=search), and it [fits well into Qt apps](http://matplotlib.org/examples/user_interfaces/embedding_in_qt4.html) (or apps of any other widget toolkit). It is [easily styleable](http://matplotlib.org/users/style_sheets.html), and its early concept of backends is now making it possible to put interactive plots generation [in the user's browser (using WebAgg backend) and soon even with OpenGL](http://mdboom.github.io/blog/2013/03/25/matplotlib-lessons-learned/), all with the same, familiar code. Its rendering can also be made [very fast](http://stackoverflow.com/questions/8955869/why-is-plotting-with-matplotlib-so-slow), even without a GPU.
