### ISSUE TITLE
Manifold Learning removes almost all attributes

### ISSUE THREAD

**Issue by processo** [biolab/orange3#1932]
##### Orange version
3.3.9

##### Expected behavior
Manifold Learning should simply add new features (like MDS) and not remove others.

##### Actual behavior
It removes all attributes except `target`.

**Comment by ajdapretnar** [comment]
I think this is intentional and should be as is. Manifold Learning is intended to transform your data into a new lower-dimensional space. This means new features implicitly contain old features. In MDS however, the output is a subset, so it's a little different.
This is also intended for easier visualization, since you don't have to browse for attributes in drop down menus.

If you want this functionality, you can use Merge Data widget.

Closing as wontfix.
