### ISSUE TITLE
Python Script widget's console should have code completion

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#2089]
It is tedious to use console which does not allow for completion with Orange (try typing ContinuousVariable). :)

**Comment by borondics** [comment]
I completely support this! We have discussed the possibility of having an ipython shell instead of a simple python console. If that could be done many of the users could learn more about the data structures and available functionality. Right now we are pretty much stuck with browsing the documentation and trying to figure out what is what and what kind of structures we are working with.

**Comment by janezd** [comment]
We had some correspondence via email.

> I looked into it a bit today.

> I'd like to avoid transferring data to another Python shell. This implies that we can't let jupyter run another Python kernel: we must force it to connect to the kernel running in Orange. As I understand, this is doable in principle: the kernel must accept data through four ports (or a few less?); see https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/connect.py. I'm not good at system-level stuff, but to my understanding you just have to listed to these ports and execute whatever Pyhon code you get there.

> This https://github.com/ebanner/pynt/ and this https://github.com/ebanner/extipy may be helpful.

> A potential huge problem is that ipykernel expects an ipython shell. Orange runs in ordinary Python. I don't know anything about ipython shell and whether it can just wrap another interpreter.

> I don't know how much would this add to Orange installation size.

> The widget would have to use Webkit or Webengine, neither of which is well supported. A weird alternative is to open a jupyter notebook in an ordinary browser and connect it to our kernel. As I understand, it's all the same to the kernel, and browser may be a better environment than a widget anyway. The widget would effectively control the kernel, that is, whether calls to kernel are immediately reflected in the widget's output or not, etc.

@lanzagar also looked into it and says it's complicated.

- We can't use jupyter notebook within widget because we'd either have to pickle data (and probably have all kinds of errors related to pickling) or run the whole Orange within ipython.
- Code completion (in editor and console) may be doable, but doesn't look trivial at all. It's a huge project, and with it we'd essentially write a new IDE for Python. We can't afford to spend so much time on a rather non-essential feature.
