### ISSUE TITLE
Deep Neural Network training widget

### ISSUE THREAD

**Issue by brylie** [biolab/orange3#2094]
Consider developing a Deep Neural Network training widget.

# User story
> As a researcher/data scientist
> I would like to include Deep Neural Network analysis as part of my Orange data flow
> so that I can harness the power of Deep Neural Networks through an intuitive User Interfaceq

# Feature
Compare Deep Learning libraries available for Python. Choose a promising library and wrap it in an Orange3 widget UI.

# Rationale
Deep Learning networks are proving to be powerful tools for pattern recognition. Building Deep Learning networks is somewhat challenging, with a steep learning curve.

Building a User Interface around one of the more simple to use Deep Learning libraries would make Deep Learning more accessible.

# Resources
- sklearn [Neural network models (supervised)](http://scikit-learn.org/stable/modules/neural_networks_supervised.html)
- [TensorFlow](https://www.tensorflow.org/)
  - [TFLearn](http://tflearn.org/) - easy to use wrapper on top of TensorFlow with similar API to Scikit-learn
- [Theano](http://www.deeplearning.net/software/theano/)
- [Keras](https://keras.io/) - high-level interface on top of TensorFlow or Theano

## Comparison
- Slant: [TensorFlow vs. Theano](https://www.slant.co/versus/14689/14690/~tensorflow_vs_theano)

**Comment by pieroguerrero** [comment]
Good use case, I think TF is a good choice, will try with it!

**Comment by janezd** [comment]
Thanks for this suggestion, but apparently nobody want to own the issue.

Besides, Orange is oriented towards interactive data analysis, so we don't want to add any methods that do not give (semi-)instant responses (seconds, or at most a minute or so). Even more, it does not work well with slow algorithms: they block Orange and often can't be cancelled. Orange thus has some very basic neural networks, but anything fancier and deeper is out of question. They belong to a different class of tools.

Furthermore, we wouldn't like to add new dependencies. We already experience problems due to large number of dependencies: numba and llvmlite are proving to be a big pain in the neck -- they break our code with every update by introducing backward incompatible changes. I suppose any decent library for deep neural networks would bring so many dependencies that it would kill us. Combined with the previous paragraph ... we don't want to risk it.

**Comment by developeralgo8888** [comment]
what is the value of Orange3 as per your explanation ? The AI World has moved to Deep Learning but orange3 is still stuck in the stone age ?

**Comment by janezd** [comment]
Yes, if that's what you think.
