### ISSUE TITLE
Select Rows: Add 'any' as variable option

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#2223]
##### Orange version

3.5.dev

##### Desired behavior
Filter out instances that contain a specified value in ANY of the variables.

##### Additional info (worksheets, data, screenshots, ...)
Rationale: social sciences data include 'indifferent' or 'didn't respond' as value in any of the attributes. Provide the option to filter out all such instances at once and retain only 'full' tables.

**Comment by janezd** [comment]
@ajdapretnar, I suppose this "any variable" should behave differently for different types.

The first combo contains an attribute name. We should probably add "Any numeric variable", "Any categorical variable" and "Any string variable". This is a bit long, though. Is it OK if we omit "variable"?

The second defines the operator. It would have the same operators as it has for the corresponding variable type, right?

The third one is a bit complicated for categorical variables. Does it contain the values that appear in all variables? Or in any (which may be a long list!)? Or do we show a line edit instead of a combo, so the user can enter the value?

**Comment by ajdapretnar** [comment]
I agree that where things get complicated is when considering what different types do. This was mainly intended for removing rows where 'any numeric variable is nan', for example. Or any string variable is nan. For categorical... I don't know. We have to think of a use case for this one. I suppose there is a chance one would want to remove rows where any of the survey responses was 'I don't know' or 'Prefer not to answer'. 🤔 I think visually it would be best the user can enter the value herself.
