### ISSUE TITLE
Example workflows not working

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#2240]
Some recent changes in Scatter Plot caused Example workflows to fail. Also Classification Tree / Tree is still not compatible with the current workflow.

Reproduce: load workflows from Help - Examples.

@jerneju Could some recent changes you've made cause Scatter Plot to fail with these workflows?
@pavlin-policar Could you please check why Classification Tree workflow is still not working? I thought we fixed the channel a long time ago...

Thanks!

**Comment by jerneju** [comment]
That does not work since 3424ef94c09c31c2d3a16adef585d7a58efd99b1.

**Comment by pavlin-policar** [comment]
Yes, I thought this worked at some point... I think #2243 should fix the problem with the workflow, but does this problem also occur with the regression widget? I don't know if we could test this, since there don't seem to be any workflow with that as well. It would probably be a good idea to add that as well with `Orange.widgets.regression.owregressiontree.OWTreeLearner`.

**Comment by ajdapretnar** [comment]
This now works. I have tested all the core examples, so I'm closing this.
