### ISSUE TITLE
OWPredictions: Bad predictions when new Table is built "by hand"

### ISSUE THREAD

**Issue by lopezco** [biolab/orange3#2307]
#### Orange version
3.5.0.dev0+c546666

##### Expected behavior
OWPredictions should be able to predict from a "handmade" Table if all the needed variables are present

##### Actual behavior
OWPredictions predicts the same value all the time

##### Steps to reproduce the behavior
Use attached workflow
[bad_predictions_when_new_data_is_built_by_hand.zip](https://github.com/biolab/orange3/files/992525/bad_predictions_when_new_data_is_built_by_hand.zip)

##### Additional info (worksheets, data, screenshots, ...)
![image](https://cloud.githubusercontent.com/assets/6637618/25942828/2500bf22-363e-11e7-98c2-9dd8e979bb43.png)

**Comment by janezd** [comment]
The handmade table does not have the same variables although they may have the same names. The identity is determined by descriptors (e.g. the instance of `Variable`) and not by names.

Use `ContinuousVariable.make('F')` instead of `ContinuousVariable('F')` (see [documentation](https://docs.orange.biolab.si/3/data-mining-library/reference/data.variable.html#constructors)).

Plus, `out_data` does not have the domain you build in the next line. Construct the domain first and the use `Table(domain, a)` instead of `Table.from_numpy(a)` (where `a` is your data). This should work.

**Comment by lopezco** [comment]
Thanks! @janezd.
