### ISSUE TITLE
Multiple inputs/outputs for "Python Script"

### ISSUE THREAD

**Issue by borondics** [biolab/orange3#2324]
##### Orange version 

3.4.dev0+1b1813c

##### Expected behavior
Often times it would be extremely useful to be able to connect several inputs to the Python Script widget and be able to do operations with them to generate one or multiple outputs.

Would it be possible to have _in_data_ and _out_data_ as an array and handle arbitrary number of inputs/outputs?  (Or at least for the input part, because I see how outputting an array can confuse other widget functionality)

##### Actual behavior
Python Script accepts only one input and provides one output channel.

**Comment by janezd** [comment]
This wouldn't be difficult to implement, but we have to decide what it will look like.

The natural way to access multiple data sets would be by indexing, e.g. `in_data[0]`, `in_data[1]`... If we do so, we break compatibility with the existing code where `in_data[0]` used to be the first data instance.

We could let `in_data` be the Table, if there is just one, or a list of tables, if there are multiple. This wouldn't work well for scripts that can accept multiple tables but also work with just a single table.

One solution may be to have `in_data.get_token(i)`, which returns the i-th table (we should come up with a better name than `get_token`. If there is just one signal, `in_data` would still contain the table, but also have a `get_token` method. If there are multiple signals, `in_data` without `get_token` would be ... hm, what?

The technical implementation of this is not very clean, but it would work.

**Comment by jschueller** [comment]
hi, news on this ?

**Comment by janezd** [comment]
@jerneju started working on it in #2418, but the current PR breaks compatibility with existing code. What about this option:

- `in_data` contains the table if there is exactly one; `None` otherwise
- `multi_data` is a list of tables; it can be empty, have a single table or multiple tables.

This solution doesn't require monkey-patching (like `get_token` above), and it supports scripts that expect a single table, as well as scripts that accept multiple tables but can work with one.

**Comment by janezd** [comment]
I'm sorry, I'm stupid. That's what's essentially already in #2418.

**Comment by kernc** [comment]
Fixed in https://github.com/biolab/orange3/pull/2506.
