### ISSUE TITLE
Separate canvas from widgets

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#2331]
There are multiple reasons for this.
- Canvas is one great piece of software, which can be used for many purposes unrelated to machine learning. E.g. Oasys needs this.
- Updates will be easier if Orange widgets behave more add-on-like.
- Separation is good by itself.

I'll start working on the simpler parts of this, but will have to ask @ales-erjavec for opinions and help, and to take over when I'm done with the trivial part.

We will probably need three separate parts (probably in three repos on github).
- Canvas,
- Base widget and report,
- Orange widgets.

Canvas already has a separate repo; we will have to merge the changes.

### Issues

A possibly incomplete list.

- [ ] Separate report windows from widgets and canvas
- [ ] Separate OWWidget from widgets and canvas
- [ ] config.py imports environ; environ imports Orange to get its directory and version, which is needed to extract cache directory
- [ ] Orange.canvas.resources includes a test that loads owfile, just for a test.
- [ ] Orange.canvas.application.aboutdialog imports Orange.version
- [ ] Orange.canvas.application.errorreporting tries to import OWWidget, but fallbacks if this is not Orange
- [ ] Orange.canvas.registry imports widges_entry_points
- [ ] Orange.canvas.scheme.widgetsscheme imports OWWidget to derive MockWidget.

**Comment by borondics** [comment]
I think this is a great idea!

I think you might have mentioned (or I saw/heard a ghost) that you were planning to make a Widget "App Store" instead of full packages too. This could help keeping the Canvas less busy in contrast to the way the Individual packages install all their widgets...

**Comment by ales-erjavec** [comment]
My previous attempt at separation ended at https://github.com/ales-erjavec/orange3/tree/orangecanvas-package/Orange/canvas

Basically what was left in Orange is the main program entry point (`__main__.py`), the application configuration module, the workflow model for OWWidgets and their discovery. However it had no report etc...

Most of the issues regarding the directory paths, versions, ... are 'solved' by having the application configuration define them and them look them up there instead of from specific modules, ...

The error reporting seems to be set through the application's `main` (and only used there), so it can be tied to the OWWidget if the entry point is defined by the same project.

The report is more difficult as it is tied directly into the functioning of the main application window.

**Comment by astaric** [comment]
Replaced by #3527
