### ISSUE TITLE
concatenation produces extra column

### ISSUE THREAD

**Issue by simon1tan** [biolab/orange3#2489]
I'm new to Orange and just learning but I am having issues with using Feature Constructor and the Concatenate function. I have 2 datasets. In each dataset, I add a new column called "type" using Feature Constructor. I use Concatenate to combine the data with the new column. I am getting 2 columns called "type" instead of one column. The Data Table shows both datasets correctly after Feature Constructor. Am I doing something wrong?

##### Orange version
3.4.4

##### Expected behavior
I expect the 2 datasets to be merged into 1 with the one new "type" column.

##### Actual behavior
Two "type" columns are created

##### Steps to reproduce the behavior
Import 2 datasets
For 1st dataset, Create Feature Constructor, new discrete value, name of "type", 0. Set value to 0. Click Send. Attach Data Table to confirm results.
For 2nd dataset, Create Feature Constructor, new discrete value, name of "type", 1. Set value to 1. Click Send. Attach Data Table to confirm results.
Connect Concatenate to the 2 Feature Constructors. Attach Data Table to confirm these results.

##### Additional info (worksheets, data, screenshots, ...)
I don't think the data matters but http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv & http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv.
![screenshot_2017-07-23_12-43-15](https://user-images.githubusercontent.com/1250858/28502323-af23e856-6fa4-11e7-9c76-19b9c4cb944a.png)
![screenshot_2017-07-23_12-44-16](https://user-images.githubusercontent.com/1250858/28502324-af248aae-6fa4-11e7-85a9-b9365eb48799.png)

**Comment by ajdapretnar** [comment]
@simon1tan Features created in Feature Constructor are not considered as the same, despite having the same name. So in your case, type is not the same as type.

You probably need to concatenate first and use Feature Constructor second.

**Comment by simon1tan** [comment]
The reason I added "type" first was because it was easy to make one dataset all 0s and the other dataset all 1s. If I concatenate first, I'm not sure it would be so easy if not impossible to determine the type. I can always modify the data externally. 

Can you see any reason why Feature Constructor was designed this way? From my point of view, if I wanted the columns to be different and distinct, I would have named them "type0" and "type1" so that they wouldn't merge. 

Hopefully, the developers can look into this some more.

**Comment by janezd** [comment]
As @ajdapretnar wrote, features are not identified by names. Names are just for the user. It's one of Orange's design principles which may be imperfect, but all other solutions are way worse. (I'm not going to go into the big picture here; you'll have to trust me on this one.) There are ways to break it, but you invariably get a mess.

In your specific case, the problem is that  features don't store only names, they also store lists of possible values. If two features "type" that you defined in two separate widgets (and they coincidentally have the same name) were actually one and the same feature, they would also have the same values. On the first glance this doesn't seem to be a problem -- if you change the list of values in one widget it would also change in another, right? -- yet if you think deeper, it would mean either propagation of information backwards through the scheme or spooky action at a distance -- one widget miraculously knowing what happened in another. However, widgets communicate only through channels in the schema. Forwards. (I can think of two cases where we didn't obey this rule, and it keeps annoying us with weird behavior that we have to hide from the user.)

And this is just what would go wrong *on the surface* if two Feature Constructor widgets defined the same feature. We sure could hack Feature Constructor to work like you proposed, but it would make a total mess. If we allowed "spooky action at a distance", any widget could change a feature and all other widgets, independent of what branch of the schema they're on, would have to update, too. If you add one more value to some feature, a widget showing the distribution of this feature would have to update the graph even if the Distributions widget was on a completely different branch. If there's a classifier somewhere -- anywhere -- in the schema that predicts the values of this feature, it would have to re-fit to the new values. 

Orange works so well (or, at least, it is maintainable) precisely because this is forbidden.

We should demote Feature Constructor to some use-at-your-own-risk category. More often than not, users discover and use it where a much simpler solution exists. Have you tried removing Feature constructors and checking "Append data source IDs" in Concatenate instead?
