### ISSUE TITLE
Freeviz: icon needed

### ISSUE THREAD

**Issue by jerneju** [biolab/orange3#2519]
##### Orange version
#2512 

##### Expected behavior
This new widget needs to have an icon like the other widgets have it.

Maybe something similar like these three:
![screenshot_20170802_140846](https://user-images.githubusercontent.com/22157215/28972739-099b20ca-7931-11e7-8588-e8d298ec3235.png)

**Comment by jerneju** [comment]
@janezd

**Comment by janezd** [comment]
Could be like Linear projection but with axes of different lengths. 
![freeviz](https://user-images.githubusercontent.com/2387315/31307031-5120791a-ab5c-11e7-95df-fb3105381708.png)
 (Svg here: 
[Freeviz.svg.zip](https://github.com/biolab/orange3/files/1364526/Freeviz.svg.zip)
). It's barely distinguishable from linear projection, though -- this is because we have two widgets with similar functions.

@BlazZupan has to approve this. Maybe @larazupan has a better idea. She's our icon designer, not me. :)
