### ISSUE TITLE
[ENH] Schedule workflows

### ISSUE THREAD

**Issue by Juriell** [biolab/orange3#2525]
It would be great if we could schedule a workflow.  For example: i have a daily task to do and i have an Orange3 workflow that does it. And i want it to be run every day/week/ month etc on a given time.

I tried to run the workflow file with windows cmd and it was close to what i needed but it opened the GUI. It would be great if the workflow could be run without opening the GUI or the process worked in background.

**Comment by janezd** [comment]
This would be solved by #1341, which I closed a few days ago (see explanation there).

This issue has a similar problem as #1341: running a workflow practically always requires some user intervention, so this functionality would not be very useful. Its implementation would require a significant time investment from the core developer team, so it will be implemented only if we feel a strong need to do so. If this moment arrives (which is unlikely because Orange is not used in this way), this feature will be implement disregarding whether this issue remains open or not.

**Comment by janezd** [comment]
Still, thanks for the idea and you're always welcome to contribute -- should somebody implement this and if the implementation is of sufficient quality and does not significantly complicate things, we'll be happy to accept it.
