### ISSUE TITLE
Widget test fields lose data after the workflow is saved and opened

### ISSUE THREAD

**Issue by Juriell** [biolab/orange3#2535]
##### Orange version
3.4.1

##### Expected behavior

After creating a workflow and filling input data in widget forms you save it and the form fields do not lose input data the next time you open the workflow

##### Actual behavior
After creating a workflow and filling input data in widget forms you save it and the form fields  are not saved. You lose all input data the next time you open the workflow and must save them somewhere else to remember what you have done.

##### Steps to reproduce the behavior

Take the File widget and in the URL field write in some url. Save the workflow and close it. 
Open it again and open the File widget - the URL field is blank - the information was lost.

**Comment by Juriell** [comment]
I had a typo in the heading. I meant widget text fields.

**Comment by ajdapretnar** [comment]
I cannot reproduce this. Perhaps update your Orange version to 3.4.5?

**Comment by jerneju** [comment]
URL can be saved only when an user commits the URL address. That means that one needs to click the second radio button, write the address and then press an enter key.

**Comment by Juriell** [comment]
The File widget was an example. For user built widgets you have to implement the remembering for each field you want to remember. And when you do that, the saved values become default for the next widgets of the same type. The widgets should remember the settings automatically when the workflow is saved and don't change tje default widget values.

**Comment by astaric** [comment]
If a widget wants its parameters remembered, it declares them as settings. New widgets starting with the last settings used is by design - this way when you use a scatterplot for the first time and configure what you want to show, the configuration is remembered and used every time you use a scatter plot widget.

If for some reason, you do not want this behaviour and only want the settings to be remembered when a workflow is saved, you mark the setting as schema_only. We do this for the painted data in [paint data widget](https://github.com/biolab/orange3/blob/master/Orange/widgets/data/owpaintdata.py#L763), where we want to save the painted data in workflow, but the new widgets start empty. The rest of the widgets in paint data (brush settings, autocommit checkbox) are remembered and restored when a new widget is added to canvas so you do not have to set them each time.

I'll update [relevants part of widget development documentation](http://orange-development.readthedocs.io/tutorial-settings.html) to include this.

**Comment by Juriell** [comment]
Thanks. I will take a look. Here is an explaination why i ask these questions: I'm working on an Oracle sql widget right now and i wan't it to remember the connection settings and the query for repeated and automated use. That's why i need it to remember the settings when i save the workflow but not make them default.

**Comment by Juriell** [comment]
The schema_only parameter solved the issue and i could finish my widget. Thanks.
