### ISSUE TITLE
ExcelReader: handle round (integer) floating-point values

### ISSUE THREAD

**Issue by thocevar** [biolab/orange3#2539]
##### Orange version
3.5.0

##### Expected behavior
ExcelReader should produce a DiscreteVariable with a list of integers (as strings) if all values are round.

##### Actual behavior
Opening excel files can result in a DiscreteVariable with a list of round floats.

##### Steps to reproduce the behavior
Open the attached test.xlsx file with the File widget. The third attribute '2nd-code' is Discrete with values '1.0' and '2.0'.

##### Additional info (worksheets, data, screenshots, ...)
[test.xlsx](https://github.com/biolab/orange3/files/1241211/test.xlsx)

**Comment by kernc** [comment]
I don't think this is possible with current upstream reader, who just knows a (vague) _number_ type.

**Comment by janezd** [comment]
+1 on this one. I am just working on a data with id's which are explicitly declared as strings in the file, but they're read as floats.

<img width="327" alt="screen shot 2017-09-18 at 13 15 20" src="https://user-images.githubusercontent.com/2387315/30557471-ff2fca8a-9c73-11e7-8a77-0a69ac3613ab.png">

**Comment by janezd** [comment]
xlrd is limited and also no longer maintained. Its [author recommends migrating](https://groups.google.com/forum/#!msg/python-excel/P6TjJgFVjMI/g8d0eWxTBQAJ) to openpyxl, except for those who need to support .xls, too. I suggest that we keep xlrd for .xls files, but use openpyxl for .xlsx. This will allow properly reading datetime, (mostly) distinguish between text and numbers, getting the correct number of decimals from cell format ... as well as properly storing all this data in .xlsx without losing types or formatting.

Dependency on openpyxl is not heavy.

The problem is that implementing this will require refactoring `FileFormat.data_table`, which is currently one long method that does everything from parsing data from headers to putting data into `Table`. `FileFormat.data_table` needs to be split into smaller methods, so that appropriate parts can be overriden by .xlsx reader.

**Comment by janezd** [comment]
While doing this, also consider whether this can help #2974. Switching types in the file widget is limited because it cannot re-read the data, but just reinterpreted the matrix. While #2974 is doable, it would be better if `data_table` is refactored so that readers can enforce attribute types -- which is essentially what this issue requires, too.
