### ISSUE TITLE
MS SQL issue

### ISSUE THREAD

**Issue by rmvaliev** [biolab/orange3#2573]
Dear team

Orange version 3.5.0

I tried to connect to MS SQL server 2014, Database: AdventureWorksDW2014

I have found two problems:
1. SQL Widget does not display Views. Only tables available. AdventureWorksDW2014 have special views like vTargetMail for data mining examples.

2.  When I have selected any table (for example FactInternetSales) or use custom SQL (select top 1000 * from vTargetMail) and then tried to use Data Table widget then Orange application frozed and does not response.
If I tried to use Logistic Regression immediatly after SQL Table widget I got error (attached file)

##### Expected behavior
1. Display all available tables and views
2. Data Table should display data from SQL Table

##### Actual behavior

1. Database views not visible in widget
2. Orange3 application frozed and does not answer 
![orange_error](https://user-images.githubusercontent.com/19163381/30250370-1990b310-965e-11e7-9c0e-ec096efe6309.png)

**Comment by ajdapretnar** [comment]
I suppose #3565 would solve this, too?

**Comment by lanzagar** [comment]
Actually, this is for Microsoft's SQL Server, so we already have an implementation that can read these databases.
The SQL Table widget has been updated to only allow downloading all data and working with in-memory numpy tables after that (except for PostgreSQL). So I don't think this issue is relevant anymore.
If some problems are still present in the latest version of Orange, please reopen an issue.
