### ISSUE TITLE
Creating new folder when saving images segfaults

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#2707]
##### Orange version

3.7.dev

##### Expected behavior
The user can create a new folder when saving images from visualization.

##### Actual behavior
Program segfaults and crashes when the user clicks on New Folder button in Save Image dialog.

##### Steps to reproduce the behavior
File (iris) - Distributions. Save Image - click New Folder.

##### Additional info (worksheets, data, screenshots, ...)
Segmentation fault: 11

**Comment by kernc** [comment]
OS/Qt version. Can't reproduce on GNU/Linux. The [file dialog](https://www.google.si/search?q=file+dialog+os+x) is a part of your operating system.

**Comment by ajdapretnar** [comment]
MacOS Sierra, 10.12.6.
qt = 5.6.2

**Comment by ajdapretnar** [comment]
Also, it doesn't happen across the system. Only in Orange.

**Comment by kernc** [comment]
Also in Save Report dialog?

**Comment by ajdapretnar** [comment]
Yes, also in Save Report. In Word or LibreOffice Save - New Folder works as expected. I can try other things as well, but these were the first two that came to mind for New Folder function.

**Comment by astaric** [comment]
it might be permission related. Could you try creating a new folder on the desktop?

**Comment by ajdapretnar** [comment]
I did. No problems.

**Comment by astaric** [comment]
My guess is the problem was that the dialog tried to create the folder in a location where the current user had no write permission. As @kernc stated, the file dialog is provided by the operating system, so there is nothing we can do about it. It is also wrapped in a layer of Qt and PyQt code, so if there was a way to mitigate the problem, it would probably be in one of those projects.
