### ISSUE TITLE
Association add-on only install 'frequentitem' tool

### ISSUE THREAD

**Issue by lidan6722286** [biolab/orange3#2778]
##### Expected behavior

there should be two widgets in association add-on

##### Actual behavior
but there is only on 'frequent item' widgets installed

##### Steps to reproduce the behavior
what i can do with it?

**Comment by astaric** [comment]
Thanks for reporting this.

As Associate is a separate add-on, its bugs are tracked on a different issue tracker:
https://github.com/biolab/orange3-associate/issues

The problem you mention has already been [reported and fixed in the development version](https://github.com/biolab/orange3-associate/issues/15). You just need to wait for the next version to be released (probably in the next couple of days) and reinstall the add-on.
