### ISSUE TITLE
Periodically rebuild website Widget Catalog

### ISSUE THREAD

**Issue by kernc** [biolab/orange3#2799]
[Widget catalog](https://orange.biolab.si/toolbox/) should be kept roughly up to date. Including add-ons.

Refs:
* https://github.com/biolab/orange3/issues/2798

**Comment by astaric** [comment]
The problem here was that widget catalog was built from documentation/help files which were not updated when the widget was removed.

Since #2868, widget catalog is created from the registry.
[The script](https://github.com/biolab/orange3/blob/master/scripts/create_widget_catalog.py) executes automaticaly on travis as a part of the [documentation build](https://github.com/biolab/orange3/blob/master/.travis/build_doc.sh).

Widgets from add-ons could easily be included in the catalog by installing the add-ons before the script is run. The list of [official add-ons](https://github.com/biolab/orange3/blob/master/Orange/canvas/application/addons.py#L49) could serve as a starting point for what to install.
