### ISSUE TITLE
Scatterplot: jittering is too slow

### ISSUE THREAD

**Issue by processo** [biolab/orange3#2881]
##### Orange version
3.8.0

##### Expected behavior
Jittering should only be calculated if _Jitter numeric values_ is checked.

##### Actual behavior
Each tick on _Jittering_ slider in Scatter Plot takes a lot of time with large datasets even when _Jitter numeric values_ is unchecked.

**Comment by jerneju** [comment]
I suppose than you also have categorical data in you dataset.

**Comment by processo** [comment]
@jerneju No, only two numeric attributes.

**Comment by markotoplak** [comment]
I think we should move jittering out of scaling.py and it only apply it on the variables shown. It should be applied as the last stage before displaying elements.

Ideally it should be applied to the current view, so that also in zoomed-in state we could see the same amount of jittering (in pixels!).
