### ISSUE TITLE
Datasets: agree on useful tags

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#2973]
##### Orange version

3.11.dev

##### Expected behavior
Data sets are marked with useful and standard tags.

##### Actual behavior
Data sets are marked with random tags or useless tags.

##### Steps to reproduce the behavior
Open Datasets. Wine data set has tag 'wine', zoo data set has tag 'animals'. Not giving any extra information.

##### Additional info (worksheets, data, screenshots, ...)
I propose a solution for improving tagging:
- tag for purpose [classification, regression, clustering]
- tag for special attributes [geolocation, time, image]
- tag for add-on it should be used with [bioinformatics, timeseries, image analytics]
- field it covers [economy, social sciences, genomics]
- special format [basket, multitarget]

Please add your suggestions.

**Comment by ajdapretnar** [comment]
I would like to implement this. @BlazZupan @lanzagar What do you think?

**Comment by lanzagar** [comment]
I agree tags could and should be improved.
The proposed tags look good enough (better than current).
I am not sure about the usefulness of the first item - tags for purpose - isn't that information visible in the Target column (categorical=classification, numeric=regression, no target = unsupervised/clustering).

Otherwise I think you can start a PR with tag improvements.

**Comment by ajdapretnar** [comment]
> I am not sure about the usefulness of the first item

I agree. I have prepared a [PR](https://github.com/biolab/datasets/pull/60). I am not sure the solution is optimal, but at least now it is fairly consistent.
