### ISSUE TITLE
Problem with test & score widget (test and train dataset)

### ISSUE THREAD

**Issue by paulaksm** [biolab/orange3#2992]
##### Orange version
3.11 and 3.12 

##### Expected behavior
Run Test & Score in Logistic Regression using train and test datasets.

##### Actual behavior
Error message "Test and train datasets have different target variables.". 
Looking at Data Tables, they both have a single column as target and the same categorical values.

##### Steps to reproduce the behavior
Construct the following workflow and upload the attached files or run issue_workflow.ows file.
<img width="482" alt="workflow_issue" src="https://user-images.githubusercontent.com/30325208/38510293-f12752c4-3bfa-11e8-8526-3060c89b8d1c.png">

##### Additional info (worksheets, data, screenshots, ...)
ZIP file attached with test and train datasets and .ows file
[orange_issue.zip](https://github.com/biolab/orange3/files/1890814/orange_issue.zip)

**Comment by hikea** [comment]
I have the same problem. Look at this issue --> https://github.com/biolab/orange3/issues/2346

My solution so far is to save the data as a .tab file (native for Orange) after preprocessing (I see you have python script there), then load it with a new File widget, then everything works.

**Comment by janezd** [comment]
Hi Paula,

when you are combining train and test data, Orange matches columns by names, not by their positions (e.g. first column in one table to the first column in another). Since it doesn't do so in general, it also doesn't do it for targets; even if you have just a single target in each data file, they won't be matched unless they have the same name.

The reason for this behaviour is that the columns' "identities" are already assigned by the file widget, and the file widgets do not know that the two data sets are going to be merged at some point in the scheme. Also, you can use Select Columns to move some ordinary feature to targets or vice versa. Or you can have two files with different numbers of features, with some partial intersection... If the Test&Score widget would have the power to decide that two columns represent the same variable, we would have a mess if some connections would go through Test&Score and some bypass it. So the only general (and reasonably safe) way for matching columns is by their names.

**Comment by paulaksm** [comment]
Hi Janez,

I see...It really seems reasonable to match the columns by their names. Although having the same column name for both train and test data did not solve this issue. 
Exporting as .tab and importing again using File, solved this issue as suggested by @hikea
