### ISSUE TITLE
Adding the Friedman Test to the Critical Difference Pipeline

### ISSUE THREAD

**Issue by BillyBarbaro** [biolab/orange3#3000]
This package has been super helpful for generating Critical Difference Diagrams; however, I realize the [CD functions](https://docs.orange.biolab.si/3/data-mining-library/reference/evaluation.cd.html#cd-diagram) only perform the post-hoc tests described in Demsar's [paper](http://jmlr.csail.mit.edu/papers/volume7/demsar06a/demsar06a.pdf).

Is there any use in including an implementation of the Friedman Test as part of Orange?  I realize the test is already available in [sklearn](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.friedmanchisquare.html), but it would be helpful to include it as part of this library as well.  You could even image a call that takes a dictionary mapping method names to lists of results, performs a Friedman test, computes the ranks, calls the existing `compute_CD` function, and outputs a CDD for the user.

If this sounds like something worth pursuing, I'd be happy to start defining the API for it and working toward a PR.

**Comment by ajdapretnar** [comment]
@lanzagar @astaric What do you think?

**Comment by janezd** [comment]
I would very much prefer doing Bayesian tests. Let us forget about the null hypotheses. [Time for a Change: a Tutorial for Comparing Multiple Classifiers Through Bayesian Analysis](http://jmlr.org/papers/volume18/16-305/16-305.pdf).

The required functions are in [baycomp](http://baycomp.readthedocs.io/en/latest/). Baycomp would drag in a few dependencies that are quite redundant for Orange. I can remove these or prepare a simplified version of baycomp. As the main author of baycomp, I doubt it will change a lot, so maintaining a separate slim version wouldn't be a problem.

What I'm thinking about here is a modification of the Test & Score widget which would show a graph and/or an additional table under the existing table, when the conditions (sampling method, selection of algorithms in the table) are such that the test is applicable.

**Comment by lanzagar** [comment]
Wow, I managed to miss the bayesian comparison paper completely. Very interesting (after 20min of reading, will need more time for the details). But anything that diminishes the (over-/ab-) use of p-values I like already :)

I think comparing different methods is a core part of Orange and if we want to advocate doing it better in papers, we should support it in the tool as well! My first thought was similar - an option to connect the Test & Score widget to a visualization / bayesian comparison widget. Like we can connect it to e.g. Confusion Matrix to analyse the results further. Maybe that would allow more freedom in designing the interface for this, since we would not need to minimize it as much as if we were to expand T&S itself (but that could work too).
