### ISSUE TITLE
Suggestion: Linear Projection Widget (Axes Scales and Labels)

### ISSUE THREAD

**Issue by jureyherrera** [biolab/orange3#3002]
##### Orange version
Version: 3.11.0 (git revision: 52b7ac4)

##### Expected behavior
The Linear Projection widget is very useful, for instance, you can make a biplot (https://en.wikipedia.org/wiki/Biplot) from PCA or LDA. From these biplots you can explore, at the same time, the class clustering and which feature have more weight for each group. 

##### Actual behavior
The Linear Projection plot could be more useful if the scales and labels were not missing.

**Comment by ajdapretnar** [comment]
Could you not make this with Scatter Plot?

**Comment by janezd** [comment]
Besides, what information do you get from the scale in the PCA? The scale is arbitrary; you can just multiply all loadings by a certain factor and the scale will change without changing the visualization or its meaning.

(Trivia: it's not that Linear projection does not show the axis because it does not enable it. As far as I recall, the widget must actually explicitly remove the axis to hide it. :) Same for MDS.)
