### ISSUE TITLE
Problems with Installing Addons

### ISSUE THREAD

**Issue by bhrigs** [biolab/orange3#3003]
##### Orange version

Orange3-3.11.0-Miniconda-x86_64

##### Expected behavior
1.) Show list of packages in options menu > Addons 
2.) Show the installed add on as a widget in the toolbox

##### Actual behavior
1.) Unable to retrieve list of packages
2.) Installed add ons  (bioinformatics and educational) not appearing in the toolbox even after restarting orange

**Comment by PrimozGodec** [comment]
Duplicated: https://github.com/biolab/orange3/issues/3001

**Comment by bhrigs** [comment]
The second issue is not closed in #3001. I have installed addons from terminal but they do not appear in the canvas toolbox.

**Comment by PrimozGodec** [comment]
No, it is not close since we are solving it right now. 
Make sure that you install it in the same environment that Orange uses. On Windows, you can open `Orange Command Prompt` that is available in Orange installation folder and install from there. Default path to Orange installation folder is C:\Users\<your username>\AppData\Orange\

**Comment by bhrigs** [comment]
Thanks. solved.
