### ISSUE TITLE
Better representation of repeated points in scatter plot

### ISSUE THREAD

**Issue by smihael** [biolab/orange3#3028]
Currently, when a data point is repeated multiple times it will just overlap the previous ones on a scatter plot. By adding some jittering, one can get an impression that there are multiple points with the sme value, but it is not always the best decision.

It would be nice to have a possibility to make points size dependent on the count of overlapping points, something like bubble chart in certain software.

There is a solution how you would achieve the same in matplotlib:
https://stackoverflow.com/questions/37759475/scatter-plot-same-point-repeated-several-times-python

**Comment by ajdapretnar** [comment]
I absolutely agree this is needed. It would also be great to implement this is Geo add-on as well.

**Comment by markotoplak** [comment]
Well, the stackoverflow solution would not be quite enough: we also need to show multiple classes (different colors) which can also overlap, and, if the widget is showing categorical data, they do overlap exactly.

**Comment by ajdapretnar** [comment]
We could turn off coloring by class in this case? This would be an easy solution. Or color by mode...

**Comment by ajdapretnar** [comment]
OR! Implement pie charts for coloring dots. 🤣

**Comment by janezd** [comment]
When refactoring visualizations in #3089, @VesnaT and I have ported this feature, but we haven't made any real effort to make the code nice because I don't like neither this feature nor its implementation (not from the code perspective but from its usability).

1. Coloring by majority is even more misleading than jittering. (Pie charts would be better, but ... no.) Hence, this can only be used when all points are of the same color and jittering is disabled. Implementing it like this complicates the user interface: if the user sets Sizes to Overlap, then Color should be automatically set to Same color. If the user sets Colors to anything but Same, Orange has to check whether Sizes are Overlap and set them to Same size.

2. This shouldn't be used together with jittering. If overlap is computed from jittered coordinates, it is wrong, since points can overlap by random. If it's computed from original coordinates (when jittering is otherwise enabled), it doesn't make sense because the points that are grouped are not actually plotted at the same spot. At least, setting Sizes to Overlap should disable jittering.

3. I would argue that if the data contains so many overlapping points that jittering gives a wrong impression, then Scatterplot is the wrong visualization in the first place. If this functionality is needed, it could be implemented differently -- with a widget that would data instances with the same value of a subset of attributes into a single instance, add a count attribute and perhaps remove all attributes except the counted. Or something along this line. Scatterplot can then visualize these counts by using the count as size.

I think this feature - with its present implementation - looks more like bells and whistles and I believe we should better remove it for the sake of simplicity of GUI and code.
