### ISSUE TITLE
the size limitation of File widget

### ISSUE THREAD

**Issue by qqliang** [biolab/orange3#3029]
##### Orange version

3.8.0

##### Issue
I wanna know the size limitation of File widget. When I load a csv file with 523 MB size , the File widget crashed.

**Comment by markotoplak** [comment]
Theoretically, the only limit should be the available memory. There is not a simple limit, and furthermore, it can depend on the file reader. It can also depend on the number of rows and columns.

Perhaps your crash is not because of the size. What kind of a crash do you get - what is the error message? 

Does reading work properly, if you only use a small part of your file? If it does, it would help, if you measured memory use when reading your file and report it here.

**Comment by ajdapretnar** [comment]
@qqliang Please expand the description of the problem with screenshots, error message and a minimal example if possible. Thanks!

**Comment by Chronocook** [comment]
I did a really simple benchmark of the footprint and got this.  It's for a 60 column dataset, looks like after a couple hundred thousand rows it starts to blow up.

<img width="614" alt="orange_ingest_footprint" src="https://user-images.githubusercontent.com/16802207/42822990-0935e4c6-89a2-11e8-8661-2a10b5afb54c.png">
<img width="615" alt="orange_ingest_behavior" src="https://user-images.githubusercontent.com/16802207/42822997-0cffe4bc-89a2-11e8-8b95-eeb40e031430.png">

**Comment by ntdef** [comment]
Has anyone seen these plots yet? My friend @Chronocook posted this 3 weeks ago showing that memory utilization in Orange scales exponentially with data size, which is a serious limiting factor.
