### ISSUE TITLE
k-means restores different clusters when loading a workflow

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#3075]
##### Expected behavior
Saving a workflow and opening it should return exactly the same clusters. 

Perhaps k-means should also have a replicable option similar to the data sampler widget. But I think that saving and opening a workflow should return the same clusters even if replicable is not selected. 

##### Actual behavior
K-means results change if you save and open schemas. Because also the order of classes changes, everything downstream is problematic.

**Comment by astaric** [comment]
I agree with a replicable checkbox.

In order to always return the same clusters when a workflow is reopened, the clusters would need to be stored in settings. The same behaviour could also be expected from sample data widget, jittering in scatter plot, cross validation, random forest, ... I am not sure we want to open that door. As a side note, when workflow is reopened, we have no guarantee that the dataset is the same as before, so we would have to handle that as well.

**Comment by markotoplak** [comment]
I would open that pandoras box. 

I know there are many such widgets, but would we really need anything else that to just save some kind of random seed?

**Comment by astaric** [comment]
The problem is how long to remember it for. If the widget would pick a random number when it is added to the workflow remember it and use it as a seed each time it does the clustering, it could work.

If we want a different seed each time apply is pressed, this could be problematic. If this is what you had in mind, let me know and I can explain the problem in detail.

**Comment by markotoplak** [comment]
I tried to think about the problematic solution, with random seed changing on each apply, except when applied the first time after widget init.

So, what am I missing? :)

**Comment by astaric** [comment]
When I concatenate multiple datasets in car registrations workflow, some of them get loaded automatically and some not, because they are too large. So when I open the workflow k-means would get multiple apply signals, one for all datasets that loaded automatically and then one for each dataset once I click reload.

**Comment by markotoplak** [comment]
I agree there is a problem. Thanks!

As I understand it now Data Table does not send anything if is is waiting for user confirmation. Would it perhaps work in that case, if Concatenate would wait for a signal on all inputs before constructing the output? 

If we could make above work and if each widget returned only one output per a set of inputs, would we still have a problem?

**Comment by astaric** [comment]
Probably.

I am thinking more along the line of having a single k-means always produce the same clusters for the same dataset (selecting a random seed in `__init__`. If you want to see multiple clusterings, we can add an explicit "new random" button, or you can use a separate k-means widget.

**Comment by janezd** [comment]
+1

Same data set + same algorithm = same results, unless explicitly randomized.

**Comment by markotoplak** [comment]
@astaric, I like your approach of selecting a random seed in __init__. It is certainly easier to implement than fixing all (at least some of) other widgets.

**Comment by BlazZupan** [comment]
For a start, I would propose that every time this widget runs a clustering, it sets the random seed. This is also done when trying different k. Only advanced users would try to see how the clustering is changing with different seeds, and they would achieve the same effect through shuffling of the data (via Data Sampler, I hope). We have many more users that expect replicable results and for which fixing a random seed would work just fine.
