### ISSUE TITLE
Save Data: allow saving to Excel format

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3096]
- Enable saving to .xslx format in Save Data widget.
- Don't save with a three-row header in .csv and .xlsx, since it destroys reading these files in other libraries (e.g. pandas).

**Comment by lanzagar** [comment]
If we plan to support saving to .xlsx, should we be conscientious enough to at least support the OpenDocument format (.ods) as well, if not instead of the Excel one.
It is an open standard, readable in most spreadsheet software, and could help save the blond capuchin and slow down the melting of polar ice caps (citation needed).

**Comment by ajdapretnar** [comment]
Yes. I have removed support for .ods, since pyods causes installation issues on some platforms. And I have removed support for .xsl in favour of .xslx, since it's a newer format.

**Comment by markotoplak** [comment]
Why did you decide to stop reading .xls files? This could break people's workflow.

Aren't we still using the same reading module and this would not cost us anything? If we do not support writing to xls, we could make 2 classes...

**Comment by ajdapretnar** [comment]
The reader wasn't working with both extensions set. If anyone knows how to do it, please change it.

**Comment by markotoplak** [comment]
The reader or the writer was not working? I'd suspect the writer. Ok, I can look into this.
