### ISSUE TITLE
Trouble with 32bit vs 64bit DLL

### ISSUE THREAD

**Issue by RhettPepe** [biolab/orange3#3239]
python -m Orange.canvas works on my friends machine but not on mine. Instead, we get this DLL Load failed error. Could you help fix this issue?

Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32

C:\MyProjects\___MECHANIKOS\orange3-master>python -m Orange.canvas
Traceback (most recent call last):
  File "C:\Python35\lib\runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Python35\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\MyProjects\___MECHANIKOS\orange3-master\Orange\__init__.py", line 27, in <module>
    from AnyQt.QtCore import QObject
  File "C:\Python35\lib\site-packages\AnyQt\QtCore.py", line 247, in <module>
    from PyQt5.QtCore import *
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by markotoplak** [comment]
I see you are using a custom Python installation (from C:\Python35\). 

How did you install dependencies for Orange?

**Comment by enjoysmath** [comment]
Rhett's my friend.  He installed them via the instructions on the front page.  The exact same procedure works on my machine which is also 64-bit.

**Comment by janezd** [comment]
I just noticed this old issue.

We no longer support Python 3.5 and 32-bit Windows. As for problems with Qt's DLLs, this usually occurred because some TeX distributions (MikTeX, I guess) include Qt's DLLs and put them in some paths on which Windows finds them before Orange's. If this report is still relevant, please check whether this could be the case.
