### ISSUE TITLE
Standardize window ratio for widgets

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3246]
##### Widgets to standardize
Visualization widgets, mostly. Don't forget PCA, Hierarchical Clustering, MDS.

**Comment by janezd** [comment]
@ajdapretnar, @markotoplak this pull request is probably not actionable. If so, I prefer to close it.

Besides, we started this topic multiple times but it remained on the level of a "guideline". Guidelines don't belong to issues.

If there's somebody who wants to own the issue: reopen it. One can also write a test that checks the heights of all widgets, and ... perhaps issue a warning instead of failing. Once we get rid of all warnings in tests, such warnings will be visible enough.
