### ISSUE TITLE
Remove tests (and support) for Python 3.4?

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#3341]
We discussed that we could stop supporting Python 3.4,  rather than fixing the reasons for the failed test.

Even disregarding the failed test, I propose we stop testing on 3.4 and start testing on 3.7. @lanzagar?

**Comment by lanzagar** [comment]
Yes, I see no reason to continue supporting (and hence testing) 3.4.
We can probably drop support for 3.5 as well since conda is deprecating it too.
See link in @pavlin-policar's comment https://github.com/biolab/orange3/pull/3192#issuecomment-432127215

Ran out of time on Friday, but I am in favor of starting to remove the tests as soon as possible (will hopefully make testing a bit faster too).
