### ISSUE TITLE
Distance Matrix Selected Data

### ISSUE THREAD

**Issue by hanshupe** [biolab/orange3#3367]
##### Orange version
3.17.0

##### Expected behavior
Selected Data Output should show the selected data in a connected data table

##### Actual behavior
When a cell is selected in the distance matrix the dashed line remains and the connected data table remains empty.

##### Steps to reproduce the behavior

Use File-Distance-Distance Matrix-Data Table/Scatter Plot

##### Additional info (worksheets, data, screenshots, ...)

The workflow works as expected with the Distance Map but not with the Distance Matrix widget.

**Comment by ajdapretnar** [comment]
Can't reproduce this. It works as expected for me.

**Comment by hanshupe** [comment]
Interesting, can you try it with this one:

[distance_matrix.zip](https://github.com/biolab/orange3/files/2558903/distance_matrix.zip)

**Comment by PrimozGodec** [comment]
The issue appears because you are making distances between columns and not between rows (you set it in the distances widget). The widget would work as expected in the case when you will make distances between rows but when distances between columns are made we decided not to show anything since all rows are included in the distance calculation.
