### ISSUE TITLE
Send error report without internet connection

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3369]
##### Orange version

3.18.dev

##### Expected behavior
When producing an error in offline mode, the error is saved and sent as soon as the user is connected.

##### Actual behavior
Trying to send an error report when offline crashes the internet.

##### Steps to reproduce the behavior
Go offline. Open Preprocess Text. An error occurs. Try to send it with Send Report button. Whole Orange dies.

**Comment by markotoplak** [comment]
Thanks, nice find!

I think we should just make it not crash and forget about these reports. We could do reporting as we do the update check: we do it in the background and ignore and error. Otherwise we would have to complicate: maintain queues of reports and periodically try to send them / check for internet.
