### ISSUE TITLE
Grouping feature values in Edit Domain

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#3371]
A user had some data with 6 class values and wanted to group them into two (three by three). In the end, he used two consecutive Create Class widgets (the first one to add meaningful labels to existing class values and the second one to actually select according to the the added labels).

Perhaps there should be a way to join values in Edit Domain.

**Comment by lanzagar** [comment]
I had a similar (but not the same) problem/task recently.
When a categorical variable has many values (e.g. 100) or some vary rare values, I would want to merge several values into one. Typically I want to keep some number of the most frequent values and merge the rest into something like "Other".
I currently have a script for this that can be used in Python Script, but I think something of this form would be useful to have available as a standard tool for preprocessing/transforming in Orange.
The question becomes how best to satisfy different use-cases since you probably want the ability to manually merge specific values, I want automatic merging based on frequency etc.
Maybe this is a single new widget, or we put the functionality in Edit Domain or Preprocess or both (manual in former, automatic in latter?).
