### ISSUE TITLE
Bag of words' IDF

### ISSUE THREAD

**Issue by benel** [biolab/orange3#3426]
##### Orange version
3.16

##### Expected behavior
When connecting a `corpus` to a `bag of words` and the `bag of words` to a `data table` (or even better to a `word cloud`), I would expect that changing the `document frequency` parameter in the `bag of words` from `none` to `IDF` would change the result (hiding common words in the language like "the", similarly to a stop words preprocessing, but **also** hiding words common to the corpus like "queen" for a tales corpus).

##### Actual behavior
Changing the parameter doesn't seem to change anything in the result.
Is there anything I'm missing? If it is not a bug, an example on how to do this would be welcome.

**Comment by ajdapretnar** [comment]
For future reference, please report all Text related issues to the [Text add-on repository](https://github.com/biolab/orange3-text/issues).

As for the Data Table, you should definitely see the changes when using the IDF transformation.

Word Cloud, however, is currently implemented in a way that it shows frequent tokens, that are a separate property from a table, which is constructed from a bag of words. That said, your idea sounds interesting, since I cannot think of a good way to sort words by IDF frequencies. Could you perhaps open a feature request on our issue tracker: https://github.com/biolab/orange3-text/issues

Thank you!
