### ISSUE TITLE
conda upgrade to 3.18.0 doesn't account for new dependency on scikit-learn>=0.20

### ISSUE THREAD

**Issue by stuart-cls** [biolab/orange3#3438]
##### Orange version
3.18.0

##### Expected behavior
`conda update orange3` installs working 3.18.0 version

##### Actual behavior
scikit-learn is left at 0.19.0, which doesn't satisfy the current requirements and results in many import errors for `from sklearn.impute import SimpleImputer`

##### Steps to reproduce the behavior
run `conda update orange3` on an existing anaconda install of orange3 (from conda-forge)

##### Additional info (worksheets, data, screenshots, ...)
Happened to me on both win64 and linux64

**Comment by pavlin-policar** [comment]
I would note here that this is not an issue due to the `fastTSNE` dependency, but rather that the [conda recipe](https://github.com/biolab/orange3/blob/master/conda-recipe/meta.yaml#L39) was not updated to >=0.20 while the [pip dependency](https://github.com/biolab/orange3/blob/master/requirements-core.txt#L4) was.

I'm guessing that the conda recipe just needs to be updated and pushed to the Orange feedstock.

**Comment by janezd** [comment]
@pavlin-policar, can this be closed?

**Comment by pavlin-policar** [comment]
Yes, this was fixed in the t-SNE library.

However, the conda recipe sklearn version doesn't match the pip dependecy version. It's trivial to update it here, but I guess the changes need to be pushed to our orange3 feedstock repository as well.
