### ISSUE TITLE
Please add LSTM

### ISSUE THREAD

**Issue by sloggers** [biolab/orange3#3522]

**Comment by janezd** [comment]
Orange is oriented towards interactive data analysis, so we don't to add any methods that do not give (semi-)instant responses (seconds, or at most a minute or so). Even more, it does not work well with slow algorithms: they block Orange and often can't be cancelled. Orange thus has some very basic neural networks, but anything fancier and deeper is out of question. They belong to a different class of tools.

Furthermore, we wouldn't like to add new dependencies. We already experience problems due to large number of dependencies: numba and llvmlite are proving to be a big pain in the neck. In terms of dependencies, sklearn is already heavy enough, and if a method is not there, we're not likely to introduce additional ones.
