### ISSUE TITLE
Standalone canvas

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#3527]
Split Orange into three or four repositories (see also #2331):

1. Base widget + signal manager + report,
2. Orange core widgets,
3. Canvas,
4. Example add-on with some simple widgets.

Repositories 2. - 4. depend on 1., but not on each other.

@lanzagar said he would prefer three repositories, with base widget included in canvas, to avoid multiplying the number of repositories and dependencies. I prefer having four, so that widgets would not depend on canvas. Also, we often change base widget while changes in canvas are rare. But @ales-erjavec knows best, so this should be his decision.

We need to see how to "pack" this for github -- are these repositories independent or are they modules of some project. We must also keep the history of commits on github.

**Packaging**: we have two products, Canvas (possibly renamed to something completely different) and Orange, e.g. Canvas 1.0 and Orange 3.22. Canvas releases will be less common. Ideally, versions of canvas and of widgets should be independent; one can in principle run newer canvas with older widgets and vice versa.

**Installation and updates:** When user downloads Orange, (s)he gets a bundle in which the core widgets are preinstalled as an add-on. Further updates will be faster because only the add-on will be updated. The widgets included in the bundle are not necessarily the latest version: after installation, Orange checks for updates of preinstalled add-on(s) and installs (a) newer version(s) if needed.

**Releases**: to simplify releasing of new versions, (minor) releases only update the add-on package.  We will prepare a release of the entire bundle only occasionally.

**Comment by janezd** [comment]
You know best. I also like Canvas being at the bottom of dependencies because it seldom changes - and seldom by anyone but you. Unlike the base widget.

Signal manager then belongs to canvas, but report goes to base widget?

**Comment by Asuranceturix** [comment]
Hi, guys. First of all, let me congratulate you on this wonderful piece of software. I am interested in building a collection of widgets for teaching image processing in a visual way, as the old Khoros Cantata environment did, and Canvas looks like a very good starting point.

Not sure that commenting in this issue is the right place, but since this issue deals with the Canvas as a separate package, I'd like to ask you guys if you ever plan on implementing a useful feature that Cantata had: the ability to group widgets to make new composite ones (think subcanvases) that could be reused. I do not know whether implementing such thing would be easy, but it sure would be very nice for all kind of signal processing tasks.

Anyhow, thanks and keep up the excellent work!

**Comment by janezd** [comment]
@Asuranceturix, we don't need it because our widgets are not that granular, but I understand that this may be really useful in other contexts. We thus don't plan to implement it; this is really complex and we can't afford to work on projects we don't need ourselves. We could in principle accept it if somebody else implements it, but I doubt anybody (even within our group) can pull this off; @ales-erjavec is the only person who know canvas well enough and can produce code of this quality.

**Comment by Asuranceturix** [comment]
@janezd , thanks for your response.

**Comment by janezd** [comment]
Closed via #3772. 👍
