### ISSUE TITLE
TSNE widget error handling catches too many errors

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#3548]
##### Orange version
master

##### Expected behavior
Our programming errors (for example due to incompatible version of library, as in biolab/orange3-single-cell#323) show the error window so that the error can be reported.

##### Actual behavior
All errors are shown as errors in the widget, which makes them hard to report.

##### Steps to reproduce the behavior
biolab/orange3-single-cell#323

##### Notes
TSNE widget is wrongly catching `Exception`.

**Comment by pavlin-policar** [comment]
I suppose this is fairly general issue. The k-means widget also has a general `failed` ([here](https://github.com/biolab/orange3/blob/master/Orange/widgets/unsupervised/owkmeans.py#L111)). I guess nobody ever noticed this because k-means is so stable, but it would make it difficult to report errors also.

I suppose we should have a guideline that the error bar should only be used for things we can foresee to be wrong with the data, and nothing more?

**Comment by janezd** [comment]
In principle, yes. Plus IO errors, out of memory errors...

A general principle would be that we don't want to silence our mistakes. The error bar tells the user that (s)he (not us) did something wrong, or there is something wrong with his computer, internet connection, data... A border case is that there is something wrong with a 3rd party library we use.

**Comment by pavlin-policar** [comment]
This should now be fixed. The widget doesn't catch any unforeseen errors any more and in case something does fail where it's not supposed to, the standard Orange error box shows up.
