### ISSUE TITLE
Rename Transform widget to something more explicit

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#3551]
Perhaps "Apply preprocessor" or something as descriptive could be clearer.

Originally idea from @borondics.

**Comment by janezd** [comment]
I started renaming, but then I realized that "Apply preprocessor" is not a really good name since it implies that the input must be some kind of preprocessor (well, the widget already indicates so...) in a "narrow sense". This may be misleading; preprocessor would often come from widgets that compute, for instance, some projection, which many users won't associate with preprocessing.

I support the idea, but we should look for a better name.

**Comment by janezd** [comment]
Unclear name caused by the ambiguity about what this widget actually does; see #3623.

**Comment by janezd** [comment]
Fixed in #3673.
