### ISSUE TITLE
Feature Request: Resizing Option for Widget Menu

### ISSUE THREAD

**Issue by VETURISRIRAM** [biolab/orange3#3599]
This is a feature request. I would like the ability to resize the widgets menu present on the left side of the Orange portal.

##### Orange version
3.19.0

##### Expected behavior
The widget section on left side of the Orange portal should have a draggable resizing option which it does not have.

##### Actual behavior
No draggable resizing option for widgets section on the left.

##### Steps to reproduce the behavior
Launch Orange.

##### Additional info (worksheets, data, screenshots, ...)

Screenshot:

<img width="1680" alt="screen shot 1397-11-19 at 1 32 32 pm" src="https://user-images.githubusercontent.com/33236428/52818359-324cb580-306c-11e9-8f1d-1d2e357d879e.png">

Session Info:

macOS High Sierra
10.13.6

**Comment by janezd** [comment]
This is way into the "we could in principle have this - but why?" territory.

It would take quite some time to implement it, it would needlessly complicate the already large and complicated part of Orange (with essentially a single maintainer, @ales-erjavec), it wouldn't look nice (what happens with the text and the icons at the bottom?), while at the same time it wouldn't be of much use because most user don't use this menu in the long term anyway, and for those that do, the current form is OK.
