### ISSUE TITLE
Windows miniconda installer: Cannot install 3.20.1 over 3.18.0

### ISSUE THREAD

**Issue by stuart-cls** [biolab/orange3#3619]
##### Orange version
3.18.0

##### Expected behavior
Windows miniconda installer (Orange3-3.20.1-Miniconda-x86_64.exe) upgrades existing installation of 3.18.0 (installed with the same type of installer) in-place, This has always worked before.

##### Actual behavior
Installer gives error 

```
"C:\Users\reads\AppData\Local\Orange" contains a pre-existing
environment that is not binary compatible with this installer.
Please choose another destination folder.
```

##### Steps to reproduce the behavior
I assume install 3.18.0 miniconda Windows and then try to install 3.20.1 over top, but I haven't verified.

**Comment by acopar** [comment]
I wrote a separate issue on this: biolab/orange3#3749

It is possible to achieve in-place install from 3.18 to 3.20 by completely bypassing the installer:
    Follow the menu Options -> Add-ons.
    Click "Add more" button.
    Type "Orange3" in the dialog box that appears and click "Add".
    Make sure you have checked the Orange3 checkbox (black square symbolizes out-of-date, checkbox symbolizes marked for update). Click "Ok" to update Orange.

![orange-update](https://user-images.githubusercontent.com/8665160/56039765-50b1f300-5d35-11e9-9baa-0af12064ea36.png)


The issue with the miniconda installer is that it expects Python 3.7 environment. This works fine on a clean system, but it is incompatible with existing Python 3.6 environment. For it to work, you need to provide a separate destination folder or first remove existing Orange application.

**Comment by ajdapretnar** [comment]
I would say this is an 'issue' of Anaconda, not Orange.

**Comment by stuart-cls** [comment]
@acopar Thanks for the update tip!
@ajdapretnar I agree that is technically true, but when my users complain they are not interested in the distinction :)

In any case, feel free to close WONTFIX and I'll just get them to uninstall and re-install. I'll watch the update discussion with interest.

**Comment by ajdapretnar** [comment]
@stuart-cls I know, but it is not something _we_ can fix. This is something for Anaconda to consider (if even possible, desirable).

**Comment by pklaerner** [comment]
I tried to upgrade from Orange 3.19.0 to 3.20.1 using the Add-on method described.

Install starts but then I get an error:

> Collecting Orange3
  Downloading https://files.pythonhosted.org/packages/dd/d8/d236b31c9c43cc32ff8d26955ea517a0b59ea73c1b80a9f24e6947cb4d00/Orange3-3.20.1-cp37-none-win_amd64.whl (4.2MB)
Installing collected packages: Orange3
  Found existing installation: Orange3 3.19.0
    Uninstalling Orange3-3.19.0:
      Successfully uninstalled Orange3-3.19.0
Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\Users\\PK\\AppData\\Local\\Temp\\pip-uninstall-de1xma41\\users\\pk\\anaconda3\\lib\\site-packages\\orange\\data\\_contingency.cp37-win_amd64.pyd'
Consider using the `--user` option or check the permissions.

**Comment by vincenzooo** [comment]
I had some problems with 3.28.
solved following the procedure above, after starting orange as administrator.
