### ISSUE TITLE
Louvain clustering widget % of progress bug

### ISSUE THREAD

**Issue by iva-c** [biolab/orange3#3747]
Louvain clustering widget stops showing progress at 49% and then suddenly jumps to 100% as it finishes the process.
![Louvian Clustering](https://user-images.githubusercontent.com/48483052/56029729-539fea00-5d1b-11e9-9039-8a172eec2f66.PNG)

**Comment by pavlin-policar** [comment]
To clarify, this isn't a bug, but a limitation of our implementation. The widget works in two steps, which will clarify this behaviour.

Firstly, the data table is converted into a graph. We construct this graph ourselves, and it's easy to display progress for this because we know how many samples we have. This is why the progress bar works well for the first 49%.

Secondly, the Louvain clustering algorithm is run. We use a library for this which doesn't provide a way to see the progress, which is why the best we can do is jump from the previous 50% to 100%. Even if we were to implement this ourselves, it would still be unclear what the progress bar should display. Louvain clustering is an iterative algorithm, which typically takes few iterations to converge. However, the number of iterations changes from data set to data set because it includes an early stopping criterion once it has sufficiently converged. Therefore the number of iterations is not known in advance, so even if we were to see the progress, there's no way of knowing where the "end" is.

Additionally, if you tick the PCA checkbox, there's a PCA preprocessing step before converting the data to a graph. This probably "jumps" from 0 to 33% with no intermediate progress because we let scikit-learn do PCA for us. But PCA is typically very fast so this isn't noticeable :)

I am closing this because I don't foresee that this is something we *will* fix in the near future, nor *how* we would fix it.
