### ISSUE TITLE
Legend and Size setting: don't show more than 5 values

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3748]
##### Issue
Visualizations enable displaying shapes of points, which are derived from categorical variables. If a categorical variable has many values, strange things begin to happen --> see how shapes represent different values in each plot?

##### Scatter Plot
<img width="1068" alt="Screen Shot 2019-04-12 at 12 47 25" src="https://user-images.githubusercontent.com/12524972/56032102-8c42c200-5d21-11e9-8f6b-64f113d50f24.png">

##### Linear Projection
<img width="832" alt="Screen Shot 2019-04-12 at 12 47 17" src="https://user-images.githubusercontent.com/12524972/56032116-9664c080-5d21-11e9-9e17-28e344b6d250.png">

##### Geo Map
<img width="1133" alt="Screen Shot 2019-04-12 at 12 35 37" src="https://user-images.githubusercontent.com/12524972/56032131-9d8bce80-5d21-11e9-8b6c-10a58d240b86.png">

In three different widgets we show three different things. This is confusing and, quite frankly, ugly.

##### Proposed solution
Do not allow selecting a categorical attribute with more than 5 values. Edit Domain now has the option to merge several discrete values into one. ⭐️ 
Another argument for limiting the upper bound to 5 is that one cannot keep 9 shapes in mind while inspecting a plot. Even 5 is a lot.

**Comment by janezd** [comment]
Filtering categorical attributes by number of values would be hacky and, moreover, confusing to the user who wouldn't know why some values are missing. I'd prefer merging all but the four most common values into a single one.

All visualizations that use the common projection base class show shapes in the same way -- everything is handled by the base class, not the widget itself. I suppose that the difference arises because some values (value '6'?) are missing.

As for Geo map, it uses a different subclass. Thus if this is a bug, it's not a bug in Orange widgets but in the geo add-on.

**Comment by janezd** [comment]
We will decrease the number of different symbols to 6 (or 6 + other) and reconsider the choice of symbols.
