### ISSUE TITLE
It is possible to have a single file with all the dependent library so that it can install offline for Linux verson similar to Windos version

### ISSUE THREAD

**Issue by dkmauryabarc** [biolab/orange3#3797]
Hi Nice app
but i have following issue/ concerns/

1. No option for offline add-ons installation.
2. Do you have any option to bypass proxy server for linux installation
3. Can we use downloaded GEO dataset for analysis offline.

Regards
Dharmendra

**Comment by ajdapretnar** [comment]
Title of this issue is misleading at best. Please rename accordingly.

1. It is not possible to install add-ons without internet connection.
3. Yes. They are stored locally once retrieved. On Mac they are stored in Library/Application Support/Orange/<latest version>/bioinformatics/serverfiles-bio/GEO. I don't know about Linux.

Don't know about no 2.

**Comment by dkmauryabarc** [comment]
Thanks for response.
