### ISSUE TITLE
Elide labels pt. 2

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3850]
We recently fixed eliding horizontal labels in Mosaic Display and Sieve Diagram. Still, issues remain present in other widgets. I propose eliding the following, too:

1. Vertical labels in Silhouette Plot. Lots of redundant white space.
<img width="616" alt="Screen Shot 2019-06-03 at 14 07 59" src="https://user-images.githubusercontent.com/12524972/58801586-3dbbf080-860b-11e9-8485-b10af24cc353.png">

2. Y-axis labels in Mosaic Display should not overlap with attribute name.
<img width="707" alt="Screen Shot 2019-06-03 at 14 09 06" src="https://user-images.githubusercontent.com/12524972/58801633-5debaf80-860b-11e9-9608-68cd26cc8678.png">

3. Distributions still doesn't elide horizontal labels. Could this be fixed with CanvasText? #3849 
<img width="760" alt="Screen Shot 2019-06-03 at 14 09 21" src="https://user-images.githubusercontent.com/12524972/58801672-82478c00-860b-11e9-9d8b-cef90d6030c3.png">

**Comment by ajdapretnar** [comment]
p.s. We should elide legend labels to some sensible length as well.

**Comment by janezd** [comment]
1. Does it happen in practice? Silhouette plot does not make much sense if the groups are so small that the length of the label exceed the height of the group. I'd support this if you can convince me with a realistic example. :)

2. Overlaps between graphics scene elements are impossible to fix in general. I suppose it would be easy to check for the overlap but even then there's no easy fix? Do you have any (doable) solutions in mind?

3. Duplicate of #3736.

Legend labels: reasonable and easy. 20 characters?

A general observation: as much as I hate having to many open issues (we're striving to get down to 75!), it's better to write issues in such a way that each issue can be solved in a single pull request, otherwise we have half-solved issues. A good bad example is "Two other issues with Feature Constructor" in #3056. Exception:  #3761, where each checkbox corresponds to a commit in the issue, but they're all on the same topic, just in different files.

**Comment by ajdapretnar** [comment]
1. Yeah, I agree such groups make no sense. There was a slight disagreement today whether we should guide the user or have them make stupid thing so they learn. Same thing as allowing 20+ variables in FreeViz. Labels would overlap and everything would be ugly, but the user would hence know having so many variable there is not a good idea. Whatever we decide, I will support.

2. If it's not easy to fix, then ignore this. :) It's not so horrible that one can't function without it.

3. Sorry. 😞 

Legend labels: yes. I will try to do it today.

Closing this since no active issues remain, I guess.
