### ISSUE TITLE
OWHeatMap: PDF and svg image export wrong

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3872]
##### Orange version

3.21.dev

##### Expected behavior
PDF export is the same as .png.

##### Actual behavior
PDF export is incomprehensible and not faithful enough.

##### Steps to reproduce the behavior
File (iris) - Heat Map (make one export in png and the other in pdf).

##### Additional info (worksheets, data, screenshots, ...)

PNG
![iris1](https://user-images.githubusercontent.com/12524972/59201163-154b6d80-8b9a-11e9-8d77-12d73dabff3c.png)

PDF
[iris2.pdf](https://github.com/biolab/orange3/files/3272362/iris2.pdf)

**Comment by ajdapretnar** [comment]
The issue is the same of course for .svg.

**Comment by Mowglisdad** [comment]
I have this problem as well. In addition, saving as png appears to save only part of the image.

**Comment by markotoplak** [comment]
The corresponding Qt bug is https://bugreports.qt.io/browse/QTBUG-54809. It was fixed in Qt 5.13.

I patched it (biolab/orange-widget-base#5), but the patch only works with Qt 5.13. On any older Qt it won't change anything. 

This is how heatmaps look with the patch: [hm513.pdf](https://github.com/biolab/orange3/files/3457097/hm513.pdf)

**Comment by lanzagar** [comment]
I guess this can be closed, since we don't expect it to be fixed for older versions of Qt.
Hopefully everyone (and our installers) get Qt>=5.13 soon.
