### ISSUE TITLE
Installer removes previously installed add-ons

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3903]
##### Orange version

3.21.0

##### Expected behavior
Previously installed add-ons are kept in Orange once the software is updated.

##### Actual behavior
Add-ons are removed, one has to install them again.

##### Steps to reproduce the behavior
Install older version of Orange, install some add-ons, them install Orange 3.21 over it. Add-on are no longer there.

**Comment by markotoplak** [comment]
Good idea!

Did you try it on a Mac or Windows? On Mac it is obvious it would not work because of how .dmg work. On Windows we currently have a bug which prevents you to install anything in the same environment (#3830) - and even there we should make it a feature due to potential problems with environment and package incompatibility, see comment in #3830. 

The way I see this working is that Orange would keep a list of add-ons as a setting. Then, at the first start after updating it could ask you if you would like to install add-ons you had again.

Asking in the installer would not work for Mac, because there is no installer.

**Comment by ajdapretnar** [comment]
Tried it on Mac.

I suppose splitting canvas and core would solve this problem, since updates would be called with conda/pip install within the environment. Installing with a new installer would act as it does now.

**Comment by janezd** [comment]
This is related to canvas, not just Orange. @ales-erjavec will consider whether it is possible to implement lighter updates.
