### ISSUE TITLE
Some add-ons give an install error

### ISSUE THREAD

**Issue by PNAG68** [biolab/orange3#3904]
Some add-ons like text, bioinformatics do not install and give error below, please advise?

https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\xxxx\AppData\Local\Temp\pip-install-vicoqbjm\shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\xxxx\AppData\Local\Temp\pip-install-vicoqbjm\shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "C:\Program Files\Orange\lib\ctypes\__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] The specified module could not be found
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\xxx\AppData\Local\Temp\pip-install-vicoqbjm\shapely\

**Comment by ajdapretnar** [comment]
For reference: Text add-on does not depend on Shapely, hence it cannot cause this issue. There might be other issues, but surely not this one.

As for bioinformatics, the issue is known: https://github.com/biolab/orange3-bioinformatics/issues/152

Thanks for reporting this. If there is an issue with a particular add-on, please report it to the corresponding repository.
