### ISSUE TITLE
Scatter Plot: crashes on sparse input change

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3913]
##### Orange version

3.22.dev

##### Expected behavior
Scatter Plot doesn't crash.

##### Actual behavior
Scatter Plot crashes.

##### Steps to reproduce the behavior
Corpus - BoW - Scatter Plot. Now change the Term Frequency type to any other.

##### Additional info (worksheets, data, screenshots, ...)
`TypeError: descriptors must be instances of Variable, not 'NoneType'`

**Comment by janezd** [comment]
@VesnaT, this happens because `Orange.widgets.visualize.utils.widget.OWDataProjectionWidget.set_data` has

```
        data_existed = self.data is not None
        effective_data = self.effective_data if data_existed else None
```

`effective_data` is a property which constructs a `Domain` from `effective variables, and effective variables are in scatter plot defined as

```
    @property
    def effective_variables(self):
        return [self.attr_x, self.attr_y]
```

However, `self.attr_x` and `self.attr_y` are `None`, so `Domain` fails.

This is easily fixed by changing `effective_variables` to

```
    @property
    def effective_variables(self):
        return [self.attr_x, self.attr_y] if self.attr_x and self.attr_y else []
```

But the actual bug occurs earlier. First, if `self.attr_x` and `self.attr_y` are `None`, then `self.data` should be `None`, too; this is inconsistent. Second, in the schema that @ajdapretnar constructed, there are useful (albeit sparse) numeric attributes, so `attr_x` and `attr_y` should be non-`None`.

**Comment by janezd** [comment]
Upon some further investigation: all numeric attributes are hidden, so they don't appear in `xy_model`. `xy_model` is empty, so `self.attr_x = self.xy_model[0] if self.xy_model else None` (in `init_attr_values`) sets `attr_x` to `None` without setting `self.data` to `None`.

We should either allow `init_attr_values` to set `self.data` to `None` (and then `set_data` has to check `self.data` again after calling `init_attr_values`) **or** we should patch `effective_variables` as above.
