### ISSUE TITLE
Edit Domain: very slow

### ISSUE THREAD

**Issue by pavlin-policar** [biolab/orange3#3923]
##### Orange version

master

##### Expected behavior
Renaming a variable shouldn't be slow.

##### Actual behavior
Renaming a variable is very slow.

##### Steps to reproduce the behavior

The following matrix is ~44k by 3002. I rename two variables and it takes like 5 minutes.

##### Additional info (worksheets, data, screenshots, ...)
[reference_3000_data.csv.gz](https://github.com/biolab/orange3/files/3358334/reference_3000_data.csv.gz)

**Comment by PrimozGodec** [comment]
This widget performs renaming in two steps:

1. It constructs a new domain that tells how variables/values should be reordered.
2. Then it uses `data.transform(domain)` to transform the data into a new domain. 

The operation that takes most of the time in your case is the construction of new matrix X that the method `from_table` does. It is implemented with a loop. I do not see the easy solution for how to correct `from_table` to do that selection faster since new X can be a combination of three tables X, Y, and meta in general. Edit Domain does not use the reorganizing of features anyway so I think it would be simpler to just not use the `transform` in this case, and do something custom in the widget. What do you think? @janezd @ales-erjavec 

P.S.: On my computer this operation takes 5-7s.
