### ISSUE TITLE
Distributions: binning datetime

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3964]
**Describe the bug**
Distributions doesn't bin datetime variables correctly.

**To Reproduce**
Datasets (Philadelphia Crime or any timeseries data set) - Distributions.

**Orange version:**
3.23.dev

**Expected behavior**
Bin width should not be hidden behind the slider and it should be datetime (i.e. 2019-08-01).
X axis in the plot should be datetime.

**Screenshots**
Example of Kennedy's speeches. Bins are not correctly computed. The final bin contains only 1 item, even though the speeches come in fairly equal intervals between 1960 and 1963. Bin should probably be <1962 and >=1962.

<img width="842" alt="Screen Shot 2019-08-02 at 13 39 08" src="https://user-images.githubusercontent.com/12524972/62448754-c7ea1780-b768-11e9-955c-135066b747ef.png">

**Comment by ajdapretnar** [comment]
To test: 
[kennedy.tab.zip](https://github.com/biolab/orange3/files/3466508/kennedy.tab.zip)

**Comment by janezd** [comment]
Thanks for the test data!

Just a comment (to self or anybody else who decides to solve this).

**Labels.** Methods `_cont_plot` and `_cont_split_plot` call `self.ploti.getAxis("bottom").setTicks(None)`, which lets pyqtgraph compute the tick labels itself, so it interprets number as numbers, not datetimes. (Note that tooltips are correct!). This should be fixed by setting ticks to values returned by `str_int`, I suppose. Like tooltips do.

**Bins.** `Orange.preprocess.discretize.decimal_binnnings` finds nice bins for numeric variables. You can see they *are* nice here -- 0, -100, -200, -300 * 10^6 ... except that 100 million does not translate into nice time intervals. To fix this. we would need to implement a function `Orange.preprocess.discretize.time_binnnings`, and call it from `OWDistribution` instead of `decimal_binnings` when it has time variable.

**Comment by janezd** [comment]
After a lot of unsuccessful prototying, I think there is a limited number of reasonable intervals:
- 100, 50, 25, 10, 5, 2, 1 years (labels is a year, without any date)
- 6, 3, 2, 1 months (can span over multiple years; same below) (label is year + month, no day)
- 2, 1 weeks (label is a date, without hours)
- 1 day (label is a date)
- 6, 3, 2, 1 hours (labels is a date + hh:00)
- 30, 15, 10, 5, 1 minutes (date + hh:mm)
- 30, 15, 10, 5, 1 seconds (date + hh:mm:ss)
- parts of seconds to arbitrary precision, using the existing decimal binnings (date + hh:mm:ss.ssss)

Time binning should check which of these produce 2 - 20 bins (or so).

Labels should be formed as described above, with some exceptions:
- if consecutive labels have the same date, the date is shown only for the first one, e.g. if the bin width is 15 minutes, the first label may be "10 Sep 2019 19:30", followed by "23:15", "23:30", "23:45", "11 Seo 2019 00:00", "00:15"
- similarly, if the width is a month or less, if multiple labels have the same year, it is shown only for the first label

Datetime variables may not contain actual dates but, for instance, times of day. If all data is in 1970 (i.e. zero), and the width is in range of months, only months are printed. If month is always January, only a day is printed. If the date is Jan 1, 1970, only hh:mm is printed. If hh:mm is 00:00, date time is treated as continuous variable (because the data is about seconds). I don't know how to formulate the rule for data that refers to days of week -- I don't think we have a good presentation (and Jan 1 1970 was Thursday).

@ajdapretnar?

**Comment by ajdapretnar** [comment]
I love the proposal above. It makes sense.

As for Unix timestamp values, I don't think we support them atm. Just ISO in the form 1970-01-01. Yes, you can 'convert' a numeric variable to datetime, say petal length, but it doesn't look any different to me. It is treated as any numeric variable. Perhaps a check that variable satisfies ISO format? (Perhaps this should be done in the File widget anyway?)
