### ISSUE TITLE
Have you consider using Julia as the computing backend()?

### ISSUE THREAD

**Issue by danielchen26** [biolab/orange3#3970]
seems like orange3 backend is using python, I was wondering how easy or do you have any intention to bring julia as an alternative backend computing power?

**Comment by ajdapretnar** [comment]
But why?

**Comment by janezd** [comment]
I know Julia rather vaguely. I've seen it's possible to call Python from Julia, but I don't know whether it goes the other way around (without hassle). Even if it does, the core team doesn't have any Julia programmers, so the interest and future maintenance is very questionable.

However, somebody outside the core can develop an add-on with a Python wrapper (or whatever is needed) for calling Julia code. No modifications in Orange are needed for this.

@ajdapretnar, as for "why", Julia is strong where Python is weak. It's a high performance language with a strong following in some scientific and data science circles, because it can do things for which Python needs numpy and Cython (or C). If Julia could accept numpy tables without memory and time overhead (maybe it does?), and if calls between Python and Julia were nice, trivial and cheap, it could replace Cython in Orange. But still, nobody uses it here, and it's probably better to stick to a single language (Python) and its "dialect" (Cython).

I'm closing the issue, but I'd still be happy if somebody provides an add-on with an interface, if this would be useful.
