### ISSUE TITLE
Outliers and DataFusion/Movies

### ISSUE THREAD

**Issue by leshankinson** [biolab/orange3#4012]
Hi,

This is a fantastic tool.   I wish I'd had something like this 20 years ago, but am glad to have it now.

I have 2 questions... 

1) my goal is to make a scatter plot showing outliers among the inliers.  I have used the outlier procedure and even created a class for inliers and outliers (same field name).  However, I can't find a way to bring them back together w/ a new inlier/outlier field (or class) that I can use in my scatter plot to differentiate the 2 groups.

2) I noticed that there were reference to other add-ons (e.g.  Movies, DataFusion, etc.).  Where can I find these or others?

Also a comment... the workflows are very helpful.  It would be great if you had more workflows for analysis of multivariate categorical data... so many surveys have this type of data (e.g. to find patterns, important relationships, and clusters of data).  Also, it is a bit slow w/ large amounts of data... are you going to make it more robust to handle larger datasets?

Thank-you for this great tool.  It really makes me want to visit Ljubljana and your University.

Thanks!

**Comment by janezd** [comment]
Thanks for the praise and apologies for the long wait.

1. I don't understand exactly what you did, but would the Merge widget help?
2. Options / Add-ons will show the list of supported widgets.

We are working on more tutorials. We also pay attention to the size of data sets Orange can handle -- but it's difficult to have a tool that is both interactive and friendly, and powerful at the same time.

I am closing the issue (because it's not about a bug report or enhancement proposal), but feel free to use it for further communication.
