### ISSUE TITLE
Orange crashes upon canvas resize if Text addon is installed

### ISSUE THREAD

**Issue by irgolic** [biolab/orange3#4062]
**Describe the bug**
Should the Text add-on be installed, upon dragging the edge of the canvas window, Orange throws a segfault.
Educational and Textable do not cause the same behavior.
The segfault behavior remains if an add-on is installed in addition to Text.

Happens on PyQt==5.9.2
Does not happen on PyQt==5.12

**Orange version:**
Orange3, canvas core, widget base latest master branches.

**Operating system:**
macOS 10.14.3

**Comment by ajdapretnar** [comment]
Text add-on doesn't force PyQt to any version, which means it could be one of the dependencies. Not sure we can fix this... 🤔

**Comment by irgolic** [comment]
To clarify, Orange3 is installed with PyQt==5.9.2.

**Comment by ajdapretnar** [comment]
Ok, this still means it is not the issue of Text per se. We just need to make sure the new release updates PyQt to a higher version, namely 5.12.3 (not 5.13, because it causes too many issues).

**Comment by PrimozGodec** [comment]
Yep, I have the same issue for a long time now but I couldn't find out what dependency exactly is the reason for that. Here are also some of my findings:

- it happens only in Conda environment, virtualenv is OK
- it does not depend on how PyQt is installed if you install it with PIP or conda it crashes
- also PyQt==5.12.* did not help in my case

@ajdapretnar current conda-forge version of qt is 5.12.5 which is good. It should not be an issue to users that use installed to install orange since Mac installer does not use Conda.

**Comment by PrimozGodec** [comment]
I can try text dependency one by one to see where the issue happens.

**Comment by lanzagar** [comment]
I don't remember well, but I thought we already encountered this issue and the answer was something with Tk not playing well with Qt.
Edit: this is probably what I remember, not sure if it is related:
https://github.com/biolab/orange3-text/issues/407

**Comment by PrimozGodec** [comment]
@lanzagar that is exactly the same issue. 

    conda install --channel conda-forge tk=8.6.8

will help.
