### ISSUE TITLE
Box plot freezes when feature has many values

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3#4094]
**Describe the bug**
Box plot freezes when a feature has many values and is selected in the subgroup menu.

**To Reproduce**
1. Save telecom-customer-churn dataset locally
2. Change CustomerID to be a discrete variable
3. Open the dataset with File widget
4. Connect box plot
5. If it does not freeze directly change subgroup value to csutomerID

**Orange version:**
3.24dev

**Expected behavior**
Orange would not freeze

**Operating system:**
Any

**Additional context**
The idea for a fix: The box plot does not need to plot a line for each value in those cases. Let's limit the number of plotted subgroups to let say first 100.

**Comment by janezd** [comment]
Many widgets would crash like this.

Alternative, general fix: prohibit discrete variables with > 100 values. These should be text variables. If there are any widgets that could do something useful with such a variable and they don't accept text variables, let them start accepting text variables.

**Comment by astaric** [comment]
Opsi car registration data (https://orange.biolab.si/blog/2017/10/13/diving-into-car-registration-data/) can be nicely visualized in BoxPlot, using Municipality/Car model as a subgroup and Sort by subgroup checked. (I was (ab)using boxplot since distributions widget does not scale too this many values, while boxplot with its slider does).
There are 213 municipalities in the dataset, 107 car models, and boxplot is fast enough. For this usecase, limiting the plot to first X values would be a preferable option to not being able to subgroup by Municipality at all.

**Comment by janezd** [comment]
What about this: if the file widget outputs a discrete variable with > 100 values, it would warn `"Categorical variables with >100 values may decrease performance."`?
