### ISSUE TITLE
Feature Statistics: wrongly computed index of dispersion

### ISSUE THREAD

**Issue by lmari** [biolab/orange3#4159]
##### Orange version
3.23.1

##### Expected behavior
As specified in the help page, and also in the linked wikipedia page, the Feature Statistics widget should compute the index of dispersion of numeric features (i.e., sigma^2/mu).

##### Actual behavior
The Feature Statistics widget actually computes the coefficient of variation of numeric features (i.e., sigma/mu).

##### Steps to reproduce the behavior
Feed the Feature Statistics widget with any data set with at least one numeric feature.

##### Additional info (worksheets, data, screenshots, ...)
...

**Comment by ajdapretnar** [comment]
@pavlin-policar You should probably decide whether to rename or change the formula.

**Comment by pavlin-policar** [comment]
Yes, so this is an issue. The reason this came about was that we needed a way to measure the "spread-out-edness" of any variable, so not only continuous but also discrete variables. For discrete variables, entropy is a quite natural choice but it's less apparent for continuous variables because the variables can have different scales. I believe this is the reason I went for the coefficient of variation over other measures. We still had to give this column a name, and unfortunately, we settled on "Dispersion" because it's short and to the point. However, as you pointed out, and I agree, this is very confusing because there's also a statistical quantity called "dispersion".

I'll need to think over what the best fix for this would be.

**Comment by lmari** [comment]
Hi. If I may provide my suggestion (I teach statistics and data mining -- with Orange! -- in engineering courses) the way the statistic is currently computed is ok: sigma/mu is adimensional, as entropy is.
I would only change the description in the help page, by replacing "index of dispersion" with "coefficient of variation". And that coefficient of variation is a statistic of dispersion (again, as entropy is) -- as in the header of the widget -- is perfectly acceptable.
