### ISSUE TITLE
2 x Transpose + Preprocess loses information

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#4188]
**Describe the bug**
Second transpose cannot retrieve the domain after Preprocess.

**To Reproduce**
1. File (brown-selected).
2. Transpose.
3. Preprocesss (say Normalize).
4. Transpose.

**Orange version:**
3.24.dev

**Expected behavior**
Second Transpose puts columns names into a string variable.

**Screenshots**
<img width="1232" alt="Screen Shot 2019-11-14 at 09 33 02" src="https://user-images.githubusercontent.com/12524972/68839832-c910d600-06c1-11ea-9286-5bf033a9802f.png">

**Comment by janezd** [comment]
The problem is in preprocess, more accurately in Normalize. Attributes' attributes are not copied when creating new attributes. I'm not sure this is a bug.

<img width="527" alt="Screenshot 2019-11-15 at 15 34 20" src="https://user-images.githubusercontent.com/2387315/68950857-4705d780-07bd-11ea-91a2-7aaaa309c9e2.png">

**Comment by ajdapretnar** [comment]
But wouldn't you expect this works? I mean former column _names_ (from Input Data) do not appear in any column, which is _wrong_ in my opinion.

**Comment by janezd** [comment]
Preprocessing should keep meta attributes and attributes of attributes.
