### ISSUE TITLE
Distances: Cosine similarity should handle categorical features

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3#4200]
**Is your feature request related to a problem? Please describe.**
Take zoo data from the Dataset widget. All features are categorical. If this data set is passed to Distances, Euclidean distance works fine but Cosine fails. In principle, both types of distances require continuous features, so it is conceptually surprising that one distance type works on categorical data and the other one complains about it.

<img width="280" alt="image" src="https://user-images.githubusercontent.com/726604/69045014-473ce780-09f6-11ea-88da-da345d2fae8b.png">

**Describe the solution you'd like**
I propose to apply continuization preprocessor for cosine distance. If really needed, the widget can still throw a warning that categorical features were continuized, but in this way the widget and the cosine distance did what was expected: computed the distance from all the features.

**Comment by janezd** [comment]
This is a note to self and @BlazZupan. @lanzagar and others welcome, too.

I know I had reasons for not implementing this, but I forgot them. And they could have been wrong.

Euclidean distances are computed separately for numeric and discrete features and these two parts are added. The part for numeric features is computed via scalar product because this is faster, but it is equivalent to computing sums of squares. For discrete, the difference between two values is 1 if they are different and 0 if they are equal; this is summed over variables.

I'm not sure how to sensibly replicate this for cosine distance. But perhaps we should really just replace categorical features with dummy variables? The effect would be the same as for Euclidean distance: if categorical values on two instances match, the dot product will be 1, if they mismatch, it's 1.

Opinions?

**Comment by janezd** [comment]
@BlazZupan and I discused this: it seems reasonable to use one-hot encoding by just preprocessing the data.

**Comment by janezd** [comment]
#4267 implements this, but we decided against merging it. See the comment there.
