### ISSUE TITLE
Data leakage?

### ISSUE THREAD

**Issue by gengyabc** [biolab/orange3#4240]
**Learns auto impute missing values**
I think this may cause data leakage from training to testing dataset if we do not split the data before hand but use the cross validation/ random sampling in  "test and score" widget.

https://github.com/biolab/orange3/blob/b3c5fdf3615173ac81146ab632f55ee9cc1726a7/Orange/base.py#L113

the missing value is imputed before split train and test, which will be done in "test and score" widget

**Comment by janezd** [comment]
There is no cross validation after that line -- a few lines later this entire data is used for fitting. Test and score widget cannot do anything *after* that line. Splitting occurrs earlier and preprocessing is applied only to training data: https://github.com/biolab/orange3/blob/master/Orange/evaluation/testing.py#L432.

Of course you have to construct a correct schema:
<img width="295" alt="Screenshot 2019-12-02 at 13 19 01" src="https://user-images.githubusercontent.com/2387315/69958914-1e444880-1506-11ea-8c0b-c24dd2e02b35.png">

If you do the following, it's wrong, but the problem is not in the line you mention.
<img width="395" alt="Screenshot 2019-12-02 at 13 20 16" src="https://user-images.githubusercontent.com/2387315/69958953-3fa53480-1506-11ea-8228-b88738be2e05.png">
