### ISSUE TITLE
Feature constructor with expressions referring to column names forgets content if input file of workflow is changed

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3#4256]
**Describe the bug**
If a feature constructor widget contains expressions referring to column names in its inputs, it loses all of its new feature definitions once the input file of the workflow is changed, even if it contains the same columns as the old one

**To Reproduce**
1. In the File widget, select an input file that contains a column named Y. Connect it to a Feature Constructor, in which you define a new feature X:=1 if Y==0 else 0.
2. Now, in the file widget, select another input file that also contains a column named Y.
Open the Feature Constructor and see that the feature defined in step 1 has been replaced by something else.
This is annoying, since the point of having a workflow is that you can reuse it without  having to redefine parts of it

**Orange version:**
3.23.1

**Expected behavior**
After selecting the new input file, the Feature Constructor should check if all referenced variables still exist, and retain the expressions that are still valid. Otherwise it could generate an error message.

**Operating system:**
Mac OS X 10.14.6

**Comment by janezd** [comment]
> the point of having a workflow is that you can reuse it without having to redefine parts of it

Thanks for telling us. We suspected that this could be the point of it, but we were not really sure. :) 

> Feature Constructor should check if all referenced variables still exist, and retain the expressions that are still valid.

It does it. And even more. See the following.

1. I loaded brown_selected and typed expression `1 if alpha_77 > 0 else 0`.
2. I used Select Columns to remove variable alpha_77 from the data. The expression disappeared.
3. I re-added the column and expression reappeared.
4. I loaded another data set, Iris. Expression disappeared.
5. I typed an expression for Iris, `1 if petal_length > 3` else 0.
6. I switched back to brown selected and Feature Constructor changed the expression to the one I used for brown, `1 if alpha_77 > 0 else 0`.
7. I switched back to Iris and expression switched back to `1 if petal_length > 3 else 0`.
8. I saved the workflow and closed Orange.
9. I loaded the workflow. The selected set was Iris, and it contained the proper expression.
10. I switched to brown and the expression switched to brown's.
11. I closed Orange.
12. I opened Orange and **didn't load the workflow at all*.
13. I loaded brown data and connected it to Feature constructor. Feature constructor remembered that the last time it saw this data, the expression was `1 if alpha_77 > 0 else 0`, so it automatically added this expression.

Then I created two files, one with variables x and y, and the other with x and z.

1. I opened the first file and type an expression that uses x and an expression that uses y.
2. I switched to the second file; the first expression remained, the second was removed because variable y doesn't appear in the second file.
3. I switched back to the first file and the first expression reappeared.

This said, I can't replicate your problem.

**Comment by ajdapretnar** [comment]
I also cannot replicate this.

**Comment by janezd** [comment]
> has been replaced by something else

Unless ... if this is a different expression, it is something that you used earlier. Orange generally matches the newest appropriate context, unless (depending on particular widget and context handler) there is a context that is older but matches better in terms of other variables that appear in the data although not necessarily in the widget.

**Comment by wvdvegte** [comment]
Strange - now I can't reproduce it anymore either. Last Friday it was happening to me all the time. Must have been some other factor causing the described behaviour. If I can ever find out what it was, I will report back. Sorry for having bothered you with this!
And yes, the "something else" was something that I used earlier.
