### ISSUE TITLE
How to send real time data?

### ISSUE THREAD

**Issue by gengyabc** [biolab/orange3#4265]
I am trying the development tutorial of "Responsive GUI"(https://orange-development.readthedocs.io/tutorial-responsive-gui.html),  and I want to send the real time loss to show it in  scatter plot in  real time as a monitor to the training process.

I send to loss in `setProgressValue`, but I find the data is send when the whole training process is fininsed. 

```python
    @pyqtSlot(float)
    def setProgressValue(self, value):
        assert self.thread() is QThread.currentThread()
        self.progressBarSet(value)
        self.Outputs.losses.send(Table.from_list(self.domain, self.output_results))
```
What can I do if I want to show the real time data? Thanks

**Comment by janezd** [comment]
First, you shouldn't abuse `setProgressValue` for this (although it may work). More importantly, Orange is, to my knowledge not designed so that widgets could continually push ouputs to one another. The problem you encountered must related to threads; the thread that actually processes signals is apparently not executed until the training is done.

Consider that the widget on the output will keep being bombarded with new signals that it will have to handle ... when? In which thread?

I'm not sure this is possible with the way Orange works, but at any rate, you're on your own. :|
