### ISSUE TITLE
Plot axis title

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange3#4306]
Currently there is no option to add axis titles to plots (e.g. Line Plot) or these can not be changed (e.g. Scatter Plot). This is especially problematic when saving plot images as information about what is on each of the axis must be saved separately and added to the image later.
There should be an option, at least when saving an image, to add axis labels and possibly a title.

**Comment by janezd** [comment]
We had this option, but nobody used it.

I read in some book about visualizations that no software can produce publication-quality visualization. The best that software can offer is vector graphics, so you can import it to Illustrator/Inkscape(/vi :) and add the finishing touches there.

A solution to the problem you exposed -- the need to save image and description separately, so you can later edit the image, would be to save images in reports, and add data as comments. Later you would save images from reports and add the stuff from the comment.

The problem is that reports contain bitmaps (and also doesn't support saving of individual images).

@markotoplak, @VesnaT, would it be possible to have vector graphics (that is, SVG) instead of images in reports? AFAIK, Qt can save SVGs, and reports are HTMLs, so this should work.

**Comment by markotoplak** [comment]
SVGs in reports would certainly be a welcome improvement.

I think @Hrovatin's use case is valid. Even if you can't make a publication-quality visualisation, you still want to make something you can share with your colleagues and therefore needs to be minimally annotated. A figure with a title can go into emails or rough presentations. @borondics wanted this for Spectra. He is actually using it (the solution theres is not good UI, though). 

I think we should have titles and axis labels as common editable options of all our plots.

**Comment by janezd** [comment]
How do you suggest we implement it without burdening the GUI?

**Comment by borondics** [comment]
@janezd, I think you are right (or the book is) that no software can produce the exact same graph one would need, but the basics are usually good enough. If you just have a look at what biologists put in their papers (or even chemists or physicists) I sometimes want to cry. Many people, however, will never edit SVG files to make the figure look perfect, so adding the little bit flexible but not super quality options to all Orange widget figures would be a big enhancement.

What features would be useful in my opinion: 
- legends that don't overlap with anything
- axes and title text boxes with the possibility of changing the font size (check out the `Spectra` widget in [Orange Spectroscopy](https://github.com/Quasars/orange-spectroscopy), that would be a start)

To not clutter the GUI, in `Spectra` we use a menu button, which is also pretty simple and not too appealing at the moment.
What I would like eventually is a nice icon that would bring up a **GMail**-like semi-transparent overlay with all the options, that would also contain the graph customization with labels, etc.

I also like the possibility of exporting a `matplotlib` script, like `Scatter Plot`, but that might be a bit too much for all widgets, especially with big datasets.

**Comment by janezd** [comment]
@borondics, would it suffice if the user could specify those things when saving visualizations?

We discussed overlay menus, but it clashes with our current implementation, so it would require a larger rewrite of (almost) every widget separately.

> legends that don't overlap with anything

The simplest option would be to just save it in a separate file, so the user can then put it anywhere (s)he likes.

**Comment by borondics** [comment]
Yes, making a nice figure upon saving is perfect. 
I guess the "optimal" font size could be calculated from the image size and/or resolution, so the user just needs to give the text, right?
I would also implement standard figure aspect ratios, so the saved figures are reproducible.

It would be nice to avoid multiple files because that just adds one more post-processing step to combine them, but I see your point too. Separate legend would work OK for presentations.

**Comment by janezd** [comment]
OK, we'll see if adding a dialog that opens before saving will help and whether it won't require too many specific changes for each visualization.

Separate legend is also useful if you publish several figures that have the same legend.

**Comment by janezd** [comment]
Moved to #4090.
