### ISSUE TITLE
Highcharts replacement

### ISSUE THREAD

**Issue by msat-cont** [biolab/orange3#4307]
Could Orange (widgets) use some free alternative to Highcharts? I understand that Highcharts is a good library, though it is too expensive for commercial use when one considers that it is just a library used in a tool.
If a reasonable amount of business is based on it, then its price is justifiable. This situation (that is a library in a tool) is not such a case.

Wikipedia shows a list of alike libraries:
https://en.wikipedia.org/wiki/Comparison_of_JavaScript_charting_libraries
and since Orange is in Python, Bokeh and Dash come to mind too.
https://bokeh.org/
https://plot.ly/dash/

**Comment by janezd** [comment]
Orange does not use highcharts, precisely because of its license. The core set of widgets as well as most add-ons use pyqtgraph because it's based on Qt. In the past we experimented with js-based libraries, but it's impossible to seamlessly integrate them into our PyQt GUI. Same for other non-Qt Python libraries.

To my knowledge, there are two add-ons, though, that use highcharts. One is "Educational", but this shouldn't be a problem because it's uncommercial by nature. The other is Time series. This one is a problem because it's essentially unmaintained.

Does your suggestion refer to time-series add-on? If so, I'd suggest you copy this issue to https://github.com/biolab/orange3-timeseries. Though, as said, it's not likely that anybody will pick it up; changing the visualization library tends to be a project. Could you perhaps volunteer?

**Comment by msat-cont** [comment]
It is good that Orange itself and most of its add-ons use pyqtgraph. Even though I do sw development and data analysis for years, I am new to Orange, and got (fortunately) false impression that highcharts are considered a way to go here. I was looking for some sort-of PowerBI-like open source sw, and Orange looks interesting.

Thanks for pointing to the orange3-timeseries repo, it is indeed the add-on that I was looking at. And it already has a ticket for it: biolab/orange3-timeseries#58 even though it seems it'll take time to deal with it as you've noted. Thus this ticket can be closed.

I am afraid that I will not find time (in a near future) to volunteer on it, as I would need more time to deal with stuff that I have to do already by now (I know, it is common). At least I will have a look at the previous discussions on this issues.
