### ISSUE TITLE
Visualizing categorical data in scatter plot with Orange (version > 3.18)

### ISSUE THREAD

**Issue by rosenm1973** [biolab/orange3#4385]
**Describe the bug**
It is not possible to visualize categorical data in Orange, version >3.18. Orange official doc states otherwise, showcasing support for both, continuous as well as discrete-valued attributes. 

**To Reproduce**
![1](https://user-images.githubusercontent.com/60474572/73464649-ed5a8580-4387-11ea-86c9-1d63db11c27a.png)
![2](https://user-images.githubusercontent.com/60474572/73464675-f4819380-4387-11ea-8808-e6581623f9f2.png)
![3](https://user-images.githubusercontent.com/60474572/73464689-f9464780-4387-11ea-9b08-2d941b2e5bab.png)
![4](https://user-images.githubusercontent.com/60474572/73464704-fea39200-4387-11ea-863f-6ecc8ecbbdef.png)

**Orange version:** 
3.20 - 3.24

**Operating system:** 
Win 10 64-bit, Win 8.1 64-bit,

**Comment by rosenm1973** [comment]
Thank you for the attention. But how to visualize Categorical data with Scatter plot?

**Comment by ajdapretnar** [comment]
This was done intentionally. Scatter Plot is intended for numeric variables. For discrete, use Mosaic Display, Box Plot or some other visualization.

**Comment by rosenm1973** [comment]
Thank you!

**Comment by porenti1** [comment]
Hi all, 

Even though it was done intentionally, would it be possible to reconsider this decision?

We found it very useful in industry to quickly visualize important variables through different projects. None of above proposed visualization does this equivalently. Mosaic Display is to complex, while Box Plot is too simplified (e.q. pure bimodal distribution, quickly label/select extreme points). We are currently solving this with Continuize widget, which is not preferred solution.

Regards, Tine

**Comment by ajdapretnar** [comment]
So if I understand this correctly, you wish to use SP to visualize *all* variables, continuous and discrete? IMO, not one visualization is appropriate for all data types. Each type requires its own visualization. You are not doing yourself a favor using a one-fits-all solution (but again, this is just my opinion).

I would use Feature Statistics though, for a quick overview.

**Comment by porenti1** [comment]
I will try to explain :) I do agree, that every type has preferred visualization. On the other hand, every question that arises requires a tool that can successfully answer it. My comment more in direction, that there was a very useful tool, which was omitted and the functionality was lost (I believe there is not widget that can overcome this deficiency - but again, this is just my opinion :). 

Firstly, Feature statistics widget is regularly used - really nice widget to go through variables! But it does not cover functionality we used in SC. We were constantly using SC for visualization and answering questions that arise
- quick overview of 1 variable across projects (where we clearly see distribution, box plots are too simplified at one side and rather complex to explain to everyone)
- desire to see not compressed information or non normal distributions across categorical variable (e.q. small number of data samples)
- quickly label possible outliers, detect one outlying group, etc ...

Living in a world without perfect datasets a quick full overview of data is necessary. It may not be state-of-the-art, but it is found really useful to answer as many questions as possible during our meetings.

**Comment by markotoplak** [comment]
I also had similar wishes from some users of Orange Spectroscopy.

I understand the pedagogical motivation for removing discrete variables, but maybe it was used it so much because it was indeed a quick and dirty path to some insight.

And then, there is one use case that none of the current widgets cover and the previous scatterplot did: if you have one discrete and one continuous variable, the scatterplot can give you an idea of the distribution of the continuous variables given the discrete one. 

Maybe the current scatterplot is indeed too limiting. Seeing some users continuizing their data to get the feature back is quite a signal. I'd vote for supporting discrete vars again.

**Comment by ajdapretnar** [comment]
Ok, I see your point. We will raise the issue at Friday's meeting.

**Comment by rosenm1973** [comment]
"if you have one discrete and one continuous variable, the scatterplot can give you an idea of the distribution of the continuous variables given the discrete one" - what can be more pedagogical than this?
Also, why parallel coordinates plot was removed?

**Comment by janezd** [comment]
> "if you have one discrete and one continuous variable, the scatterplot can give you an idea of the distribution of the continuous variables given the discrete one" - what can be more pedagogical than this?

*I have seen things you people wouldn't believe.* :) Scatterplot was a mädchen für alles for just about everything. In many cases, there exists a much better, cleaner, more informative, less misleading visualization, but people didn't discover it because they were stuck in the local optimum (=scatter plot).

What @markotoplak wrote was one of the few (if not the only) "legitimate" uses of scatter plot with discrete variables. I'd prefer to see how to expose (or add) better visualizations, and how to make them more suitable for the cases in which experienced users would prefer to use the previous scatter plot. For instance, the @markotoplak's case could be handled by putting dots inside of box plot. Maybe. Or maybe there is a completely different visualization for this. Same for other uses of discrete variables in scatter plots.

**Comment by ajdapretnar** [comment]
@rosenm1973 Parallel coordinates was removed because it was unmaintained and it was crashing all the time. Feel free to bring it back to life. It was moved to Prototypes and the original code can be found somewhere in the history of the repo.

**Comment by janezd** [comment]
> I will be honored to discuss some of my comments in Friday’s meeting :)

Not much of an honour, but I'm happy you feel this way. :)

We'll probably revive discrete variables in scatter plots, but it may not happen soon. @VesnaT is busy and she said she can look into it after a month or so. A lot of code was removed and reverting this is not trivial because new code may expect to find numeric variables only, so this needs to be done carefully (which disqualifies the other candidate for the job -- myself.)

Our reservations about misuse of the widget will be adressed by the widget showing a (discrete) warning in cases where other visualizations may be more appropriate.

**Comment by wibrt** [comment]
+1 for reintroducing this feature, and optionally adding a short section in the documentation of scatterplot to other visualizations that might be more usefull for non numeric data

**Comment by tomsnowgb** [comment]
I do agree that there is value in this feature.
