### ISSUE TITLE
Unify normalization in Preprocess and Continuize widgets

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#4418]
Now that #4379 was merged, Continuize can not normalize sparse data.

Also, Preprocess and Continuize widgets have different normalization options. They should be probably be unified. Some options from Preprocess would also work for sparse data.

**Comment by janezd** [comment]
It is difficult to offer the same options as in the Preprocess widget because the Continuize widget has this stupid "zero based" option at the end, which, ironically, applies to categorical values only when using "Divide by number of values".

<img width="350" alt="Screenshot 2020-02-26 at 18 24 11" src="https://user-images.githubusercontent.com/2387315/75370335-36d5bc00-58c5-11ea-9af1-b276b92a2aed.png">

## Options

1. Keep the interface the same, but we don't translate sparse features and show a warning instead.

2. Redesign the widget: remove the box at the bottom and instead copy the same options as in Preprocess>Normalize.

    We also split the option "Divide by number of values" (in both places where it appears) into two: "Divide by number of values" and "Divide by number of values and renormalize into interval [-1, 1]" (the latter should obviously be rephrased). This would allow for providing the same functionality (with some settings migration).

3. Redesign the widget: remove the box at the bottom and instead copy the same options as in Preprocess>Normalize.

I lean toward option 3. About 1: The last box is currently confusing; I wasn't sure what it does with categorical features. About 2: It adds yet more radio buttons, and the new options would be useless anyway -- why would one transform categorical variables into interval [-1, 1]?!?!

**Comment by ajdapretnar** [comment]
+1 on the third option.
