### ISSUE TITLE
Scatter plot: bring subset data in front

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange3#4487]
When viewing large scatter plots (e.g. in tSNE) it can be sometimes hard to see the points from data subset, as they hide behind other points. The same happens when colouring by variable that has a value for only some of the instances (and is NA for others). It would be nice if in such cases the subset/coloured data could be painted in the front of the remaining points. 
Example of showing both subset data and colouring by variable with many NA values. It is unclear if some of the coloured filled points of interest are hidden behind grey points. 
![Screenshot from 2020-03-03 15-12-57](https://user-images.githubusercontent.com/47607471/75855245-2015f480-5df2-11ea-9049-4fe22445df10.png)

**Comment by janezd** [comment]
I support the idea.

Points in projections are plotted as two curves. One are the points themselves and the other curve are selection marks. The selection curve is always on top, which may sometimes (now and after these changes, but to lesser extent) lead to strange effects if the selected point is below (or partially covered) by one that is not selected. Nobody complained about this so far, though.

The desired effect could be achieved by separating points into multiple curves based on their colors and on whether they are selected. I do not like this idea because it represents a major change and potential headaches down the road.

A simpler approach would be to reorder points in the curve. Pyqtgraph paints the curves in the order of appearance (see [pyqtgraph's most excellent documentation](https://github.com/pyqtgraph/pyqtgraph/blob/develop/pyqtgraph/graphicsItems/ScatterPlotItem.py#L775)). We can define a z-vector, argsort it and reorder the plot data by these indices.

The order should be:
- selected points above unselected
- among each of those
  - sort by increasing frequency of colors (the rare at the top)
  - points with missing color data are at the bottom, disregarding their frequency.

@Hrovatin, correct? 

Is the latter applicable only to discrete colors or also to binned continuous? In case of continuous, the could lead to, say, both tails being at the top. Would this be OK?

**Comment by Hrovatin** [comment]
Yes.
I would assume it could be used for continuous, but it may depend on the use case. If proportions of all colours are similar (slightly smaller/larger between groups) and there is no NA it might actually be better not to order points' z-position.
