### ISSUE TITLE
Updating Orange on add-on install failes

### ISSUE THREAD

**Issue by robertcv** [biolab/orange3#4649]
**Describe the bug**
```
(C:\Users\rc\AppData\Local\Orange) C:\Users\rc>conda install orange3-geo=0.2.7=py_1
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - orange3-geo==0.2.7=py_1 -> orange3[version='>=3.25.0'] -> httpx[version='>=0.12'] -> brotlipy -> python_abi=[build=*_cp27m] -> pypy[version='<0a0']
  - orange3-geo==0.2.7=py_1 -> orange3[version='>=3.25.0'] -> orange-widget-base[version='>=4.5.0']
  - orange3[url=file:///C:/Users/rc/AppData/Local/Temp/nso20D5.tmp/Orange-installer-data/conda-pkgs/orange3-3.23.1-py36h6538335_0.tar.bz2] -> orange-widget-base[version='>=4.0a,<4.1a']
Use "conda info <package>" to see the dependencies for each package.
```
**To Reproduce**
Orang3=3.23.1 from installer. Update orange3-geo to the latest build which needs Orange3>=3.25.0.

**Expected behavior**
Orange normally updates itself when add-ones require newer versions.

**Operating system:**
Windows 10 1903

**Comment by thocevar** [comment]
My error is slightly different:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - orange-canvas-core[url=file:///C:/Users/Tomaz/AppData/Local/Temp/nso4B63.tmp/Orange-installer-data/conda-pkgs/orange-canvas-core-0.1.7-py_0.tar.bz2]
  - orange3-geo==0.2.7=py_1 -> orange3[version='>=3.25.0'] -> httpx[version='>=0.12'] -> brotlipy -> python_abi=[build=*_cp27m] -> pypy[version='<0a0']
  - orange3-geo==0.2.7=py_1 -> orange3[version='>=3.25.0'] -> orange-canvas-core[version='>=0.1.9,<0.2a']
Use "conda info <package>" to see the dependencies for each package.
```

It won't update `orange-canvas-core` because it's not installed correctly as a conda package which can be updated. In your case, it looks like your `orange3` package has a problem. If I manually install `orange-canvas-core` and `orange-widget-base` with `conda install` and overwrite existing packages created by the installer, my installation of `orange3-geo` succeeds and updates Orange to 3.25.

There's a similar issue with our other pip installer. Installing orange3-geo with pip updates Orange to 3.25 without problems. However, when installing the add on from GUI, it creates and uses a constraints file with pip. The constraints specify a range of orange3 versions. My guess is that it finds that the current one is in range and pins it to this version. Therefore, it's not updated to 3.25 and some widgets that rely on new functionality fail.

@ales-erjavec, we'll need help from someone who knows what's going on in our installers.

**Comment by ales-erjavec** [comment]
I had to uninstall Miniconda, download the latest Miniconda installer and install that (updating conda in place left it unusable). Then it runs fine.
