### ISSUE TITLE
DomainContextHandler should have warning about wrong usage of it

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3#4658]
**Is your feature request related to a problem? Please describe.**

Some widgets wrongly use DomainContextHandler. They use it when no Setting variable store variables from the domain.

**Describe the solution you'd like**

I would add a warning in the DomainContextHandler which would warn the creator of the widget that he/she should not use this context handler.

**Comment by janezd** [comment]
I started working on this and then realized that this probably can't be done.

1. The following code is correct:

    ```python
        settingsHandler = DomainContextHandler()
        attr_color = ContextSetting(None)
    ```

    but context handler has no way of knowing that `attr_color` may eventually contain a color variable.

    Even worse, at the time when a widget class (or even when a widget) is initialized, it *cannot* contain instances of variables in any of its settings.

2. We could require to use a special context setting, say `VariableContextSetting`. But it wouldn't do anything, it couldn't enforce that it's value should always be `None` or an instance of `Variable`, because (a) context settings turn into attributes and we have no type checking on attributes and (b) It is legal to have something like this:

    ```python
        settingsHandler = DomainContextHandler()
        attr_color = ContextSetting("Color by stress")
    ```

    when a setting can contain either a string or a `Variable`. Thus even if the setting contains a string, the context handler can't be sure that it won't sometimes contain a `Variable`. We have something like this in MDS. `VariableContextSetting` would only serve as an indicator to the context handler, only a contract, "*I promise I'll sometimes store a `Variable` here*". It would be just

    ```python
    class VariableContextSetting(ContextSetting):
        pass
    ```

    I wouldn't do this. We'd have to change all widgets, and to very little, symbolic effect.

3. A context handler could detect that the widget contains no context settings at all, with something like this (this would be a method of `DomainContextHandler` but wouldn't check instances of derived types because I've noticed that all currently derived types would need to override the check!):

    ```python
        def analyze_settings(self, provider, prefix):
            super().analyze_settings(provider, prefix)
            if type(self) is DomainContextHandler and \
                    not any(isinstance(setting, ContextSetting)
                            for setting, *_ in self.provider.traverse_settings()):
                warnings.warn("DomainContextHandler must have at least one ContextSetting")
    ```

    This check would be useless, though. If a widget has no context settings, than context handlers simply don't do anything, so having a wrong context handler is redundant, but harmless.

I see no other options, so I'd close this as "Won't fix". We can just review all existing widgets and pay attention at this at future merges.

**Comment by janezd** [comment]
We can't implement this check, so I manually checked the uses of `DomainContextHandler` in core widgets and our add-ons, and opened issues #4664 and #4467.
