### ISSUE TITLE
Color: Renaming variables is broken

### ISSUE THREAD

**Issue by lanzagar** [biolab/orange3#4666]
**Describe the bug**
After renaming a variable in the Color widget all its values are unknown/missing (`?`).

**Orange version:**
3.25

**Comment by ajdapretnar** [comment]
I don't think Color should enable renaming variables. I mean... why? We have Edit Domain for that.

**Comment by janezd** [comment]
It's sometimes practical - we can also change a color for a certain value and rename it.

It is also quite nicely implemented, integrated into models, tested... Removing this functionality would require rewriting the widget (or keeping a lot of unused stuff in it). Fixing this issue is trivial - it was just a missing argument. #4669 is ready for review.
