### ISSUE TITLE
Add-on download

### ISSUE THREAD

**Issue by hendrix5441** [biolab/orange3#4720]
**Describe the bug**
Program states I have connectivity issue when I don't. Re-installed Orange 3.25 three times
**Here**, provide a clear and concise description of what the bug is.

**To Reproduce**

Steps to reproduce the behavior go **here**:
1. Go to 'options"
2. Click on 'add on'
3. Scroll down to N/A
4. See error, Yes See error.

**Orange version:**3.25
Orange - About - version number.

**Expected behavior**Add-on list with what is available and what is already installed. 

**Screenshots**

**Operating system:**Windows
Windows, OSX or Linux? Which version?

**Additional context**

**Comment by tolo83** [comment]
Not sure this is the same error, and the proper way to to deal with issues here (my first post on Github), but I have a very similar issue. Windows 10, Orange 3.25, fresh install. When I click the Addon entry, I get a proxy error warning (there is no proxy in the settings, I don't use proxy or VPN). The error code from Details points to something other than proxy (otherwise I would have tried what I saw in proxy related issues):

`Traceback (most recent call last):
  File "D:\Program Files\Orange\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Program Files\Orange\lib\site-packages\orangecanvas\application\addons.py", line 679, in <lambda>
    lambda config=config: (config, list_available_versions(config)),
  File "D:\Program Files\Orange\lib\site-packages\orangecanvas\application\addons.py", line 1227, in list_available_versions
    response = session.get(PYPI_API_JSON.format(name=p))
  File "D:\Program Files\Orange\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "D:\Program Files\Orange\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Program Files\Orange\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "D:\Program Files\Orange\lib\site-packages\cachecontrol\adapter.py", line 44, in send
    cached_response = self.controller.cached_request(request)
  File "D:\Program Files\Orange\lib\site-packages\cachecontrol\controller.py", line 145, in cached_request
    resp = self.serializer.loads(request, cache_data)
  File "D:\Program Files\Orange\lib\site-packages\cachecontrol\serialize.py", line 97, in loads
    return getattr(self, "_loads_v{}".format(ver))(request, data)
  File "D:\Program Files\Orange\lib\site-packages\cachecontrol\serialize.py", line 182, in _loads_v4
    cached = msgpack.loads(data, encoding="utf-8")
  File "msgpack/_unpacker.pyx", line 144, in msgpack._cmsgpack.unpackb
TypeError: unpackb() got an unexpected keyword argument 'encoding'
`

I have updated all conda packages, tried playing around with the msgpack or python-msgpack module, but nothing has helped.

BTW, using the latest Quasar (0.7.1), installed at the same time, works normally.

**Comment by ales-erjavec** [comment]
@tolo83  Can you open Orange Command Prompt (in D:\Program Files\Orange\) and run
```
conda install cachecontrol=0.12.6
```
(you will probably need to run it as Administrator; Right click on the Orange Command Prompt icon and select 'Run as administrator'

**Comment by tolo83** [comment]
@ales-erjavec 
Thank you, that did the trick, now it all works as expected :)

**Comment by vguarino** [comment]
I have been starting to use Orange3 3.25 for Windows (windows10 64bit). I have got a similar problem and in my case the "workaround" has been the following:
- Go to "C:\Program Files\Orange\Lib\site-packages\cachecontrol" directory
- copy serialize.py to serialize.py.SAVE
- edit (as administrator) serialize.py
- go to line 182
- change it as follow: 
          cached = msgpack.loads(data)
- save and close
- restart Orange3

The problem seems to be in that call which does not support the argument "encoding" anymore; so removing it allows the function to work.
Hope this helps.

**Comment by ajdapretnar** [comment]
The latest installers were now updated and include `cachecontrol=0.12.6`.
