### ISSUE TITLE
Reshape wide to long and vice-versa

### ISSUE THREAD

**Issue by bernard-liew** [biolab/orange3#4783]
Dear Orange team,

Many thanks for this very cool software. Is there a widget that can reshape a data wide to long and vice versa? I think in pandas terms it is stack and unstack (https://pandas.pydata.org/pandas-docs/version/0.23.4/reshaping.html). Or must a script be written? If so, how does one convert an orange data table to pandas, and back?

Many thanks and keep safe.

Regards,
Bernard

**Comment by lanzagar** [comment]
The current support for this is in widgets is definitely a bit lacking compared to pandas functions. Depending on what exactly you need and how your data looks you might be able to do something with the Pivot widget: https://orange.biolab.si/widget-catalog/data/pivot/
But that is more focused on aggregation than reshaping (sometimes you can make columns from a variable and use any aggregation if you are aggregating a single value anyway - that could cover long to wide).

If you need something that is not supported in a widget (yet) it is usually very easy to just connect to the Python Script widget and do some custom manipulations there (as long as you know some python).
For converting to pandas and back there are some helper functions as well:
` Orange.data.pandas_compat.table_from_frame`
`Orange.data.pandas_compat.table_to_frame`

I am closing this since it is not really an actionable issue, but we do hope to expand on this functionality in the future (we should open a more concrete enhancement proposal when someone is willing to work on it).
