### ISSUE TITLE
Concatenate: same vs. equal variable

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#4791]
**Describe the bug**

Trying to concatenate two data sources, each with a variable called, say, New that was created in Orange. Concatenate makes two variables, New (1) and New (2).

While I understand this may be desired in some cases, in my particular case it is not.

**To Reproduce**
1. File (1) (iris) + FeatConst (create variable New).
2. File (2) (iris) + FeatConst (create variable New).
3. Use Concatenate to merge the two data sets. There will be two variables New on the output.

**Orange version:**
3.26.0.dev

**Expected behavior**
Have the option of treating variable with the same name as the same variable.

**Additional context**
I know this has been a discussion for a long time and it is unclear what the preference here is. My use case: I have two corpora, each from a different language. I use Sentiment Analysis on each, as SA is language specific. Each SA create a variable called Sentiment. When concatenating, I get two variables instead of one.

What is even worse, these variable seem to have a compute_value, which adds values to the data that shouldn't have any values (say Slovenian text for English one).

Problem: how to treat compute_value for modeling when data comes from different sources (e.g. different languages)?

**Comment by ajdapretnar** [comment]
Here is an example. There shouldn't be three variables in a row, but only one.

<img width="583" alt="Screen Shot 2020-05-19 at 09 22 05" src="https://user-images.githubusercontent.com/12524972/82296929-3a537d80-99b2-11ea-89ae-9b2fb828b00e.png">

**Comment by janezd** [comment]
Work as intended ... Feature Constructor adds (and must add) compute value. It doesn't work by simply computing the additional column(s) and adding them under a plain variable.

You can, for instance, add a variable to training data, fit the formula for its computation ... and then test in on testing data. This wouldn't work if the column was computed and the variable were plain, without compute value.

> I know this has been a discussion for a long time and it is unclear what the preference here is. 

Not really. Variables with different compute_value are different variables, no discussion here.

Your two variables have different functions in compute_value, right? So you can't use Apply domain (or Concatenate before Feature Constructor)?

Then the only way I could think of would be to have widget that would strip compute_value from all variables. Or ... to have a checkbox "Treat variables with the same name as the same variable".

Both would be quite technical and understood only be developers. (Also the second, because users wouldn't understand in which cases this would make a difference!) I don't know how to frame it, explain it. It is a bit like Excel's "Paste special / Paste values".

**Comment by ajdapretnar** [comment]
No, I can't use Apply Domain nor Concatenate before FeatConst. My two datasets are in two different languages. I have to compute sentiment for each separately, because they use different dictionaries. Then I would like to compare sentiment across languages, so I want to concatenate them. Currently, I cannot do this in Orange.

As I said, I understand this is not simple (in terms of UX) and it probably works as intended. But for my use case, it doesn't. We can decide it is simply an edge case. But perhaps someone might want to join two different Cluster labels? Or something of the sort?

**Comment by janezd** [comment]
Friday's note: same situation is also possible in other widgets, like predictions. @markotoplak noted that in spectrology, there can be multiple data sets with different normalizations.

- The proper place to make the variables "dumber" is Edit domain.
- It would be nice to be able to dumb them "en masse".
- Widgets like Concatenate could detect the possible problem and give the user a hint or provide a checkbox that would merge variables with the same name but different `compute_value`s.

The biggest problem is how to explain to the user what this is doing. In this respect, Concatenate has a simpler job because it explains it in a concrete situation with such variables and can tell the user what can (s)he do (Merge variables with the same name but different *formulas*(???improve!) into a single variable) than Edit Domain.

**Comment by ajdapretnar** [comment]
"Make plain variables"?
"Ignore variable formulae."

I am also very much in favour of "Make variables dumb." Or "Dumbify." 😅

**Comment by janezd** [comment]
Make attributes dumb again, or just MADA.

Plain variables are short, concise, but only we would understand them.

Ignoring formulae describes what it does, but doesn't tell the user why would (s)he want this. Why would you want to ignore the formula? "*Looks like a bad idea; without the formula, it also won't have the value, right?*"
