### ISSUE TITLE
Colors for more than 256 values crash

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#4796]
**Describe the bug**

Several widgets crash if given Discrete Variable with more than 256 values.

**To Reproduce**

Make a Discrete Variable with more than 256 values. Pass it to Color or Line Chart (Line Chart will crash only if this variable is selected for Split by).

**Orange version:**
3.26.0.dev

**Expected behavior**

Values that are out of range are colored gray. A Warning appears.

**Comment by janezd** [comment]
> Values that are out of range are colored gray. A Warning appears.

Gray, or do we cycle through the palette again, repeating the colors? If we do this, we don't need a warning. Nobody will notice recycling since many of the 256 Glasbey colors are indistinhuishable anyway. 

Warning would be difficult to implement - we would have to do it for every widget separately. The change I describe below is a simple change in a single place that would solve problems for all widgets at once. 

Note to self of whomever may be concerned: `LimitedDiscretePalette` returns `Glasbey` if `number_of_colors > len(DefaultRGBColors)`. It doesn't check whether `number_of_colors > len(Glasbey)`. Shame on me.

`LimitedDiscretePalette` should return another palette, e.g. `ExtendedGlasbey` that won't redefine only `values_to_qcolors` and similar, but also properties `qcolors` and `qcolors_w_nan` so that they would return an array of appropriate length. Alternatively, `Glasbey` can behave like this by default (e.g. `Glasbey` wouldn't be an instance of `DiscretePalette` but of `GlasbeyPalette`).

**Comment by ajdapretnar** [comment]
> Nobody will notice recycling since many of the 256 Glasbey colors are indistinhuishable anyway.

😆 True. This is not meant to be saying I need more than 256 colors. Nobody does. Just so the widget doesn't break. I'm fine with this solution, if it is the most straightforward. 👍
