### ISSUE TITLE
Import Documents Widget is missing 

### ISSUE THREAD

**Issue by yatendra3192** [biolab/orange3#4845]
**Describe the bug** Import Documents Widget is missing 
Orange version - 3.25
Expected behavior - widget should be available in text mining
Actual behavior - widget not available

Additional info (worksheets, data, screenshots, ...)

![image](https://user-images.githubusercontent.com/30041081/83975005-d962f980-a90e-11ea-9df1-e8a868644b7b.png)

![image](https://user-images.githubusercontent.com/30041081/83975036-04e5e400-a90f-11ea-9102-0681f3b81e6d.png)

**Comment by PrimozGodec** [comment]
Hi. Thank you for reporting this. We just found out that somehow an older version of a text addon is installed when installing addons. We are fixing this issue. 

Currently, the best option for you to fix this issue is:
1. Go to the folder where Orange is installed on your computer. By default it is C://Users/<your user name>/AppData/Local/Orange.
2. Open `Orange command prompt`
3. Upgrade the version of the addon with typing `conda install orange3-text=0.9.1` in the command prompt
4. Open Orange

**Comment by janezd** [comment]
Also, please report further issues related to text add-on to https://github.com/biolab/orange3-text.
