### ISSUE TITLE
Pass single file to file widget in recursive manner

### ISSUE THREAD

**Issue by ajitmtalekar** [biolab/orange3#4847]
**Is your feature request related to a problem? Please describe.**
This is a feature,
**Here**, write a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
When we call the file widget it picks up only one file.
**Describe the solution you'd like**
I have written a python code to get the files from a directory and pass to the workflow but what it does is passes all files in the directory and completes the flow.
Can we have some thing like a file Monitor which picks up files one by one and passes to the file widget so the work flow can work on one input at a time and store the output.
Add a clear and concise description of what you want to happen **here**.
Am looking for a widget which will do file monitoring at a given path and as soon as it receives a file in the folder pass that file to the file widget in the workflow. 
**Describe alternatives you've considered**
Alternative i can see is writing a python code which calls the workflow from command line.
**Additional context**

**Comment by janezd** [comment]
No. Orange is not intended for automating things, but for visual exploration of data. In the context of interactive analysis, such widget(s) would not make sense.

Such widget is also impossible because the first widget has no way of knowing that the last widget is done and that Orange can start processing a new file.

That said, https://www.aps.anl.gov/Science/Scientific-Software/OASYS, which is based on Orange canvas (but for an entirely different field, simulation of x-rays for synchrotrons) does have something like this, but its canvas is modified to allow cycles. In Orange for interactive data mining, we don't and won't have cycles.
