### ISSUE TITLE
New CSV File Import variable type assignment breaks old workflows

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange3#4858]
Latest master has changed the assignment of variable types in CSV File Import. Previously all variables were Numerical or Text. Now some variables are Categorical, which also includes the variables with all zero values (e.g. {0}), that may in fact be numerical (as is done in File widget). This  breaks old workflows that used CSV File Import in order to ensure that all number-like variables were treated as Numerical.

**Comment by PrimozGodec** [comment]
@janezd Widget now guesses the column type when the type is set to Auto. Before the column type was either Numeric when only numbers are in columns and String otherwise. It is the change in the widget behavior and not settings change. One possibility to fix it would be to set a special variable with the version of settings from the restored workflow and if this variable would have a value 1 types would be assigned based on the old behavior. 
The problem here is that when someone re-saves the same workflow with settings_version=2 this would not work anymore and new behavior would be used. For now, I do not see the other solution.

**Comment by janezd** [comment]
Could this idea be copied: https://github.com/biolab/orange3/blob/master/Orange/widgets/data/owdatasampler.py#L357?

**Comment by PrimozGodec** [comment]
This is a possibility. I was thinking about similar implementation but taught that introducing another setting would not be nice. I will implement it this way. Thank you.
