### ISSUE TITLE
Exporting plot to currently open ppt

### ISSUE THREAD

**Issue by VesnaT** [biolab/orange3#4883]
- Exporting to currently open ppt
Applicability: General.
Importance: Low, but it was very pleasant to use on Spotfire. (KH)
    - **JD:** This is very platform specific

**Comment by irgolic** [comment]
Supposedly CTRL+C CTRL+V-ing in a widget copies the plot. This should be tested by someone else too.

**Comment by ajdapretnar** [comment]
@thocevar for Windows, @lanzagar for Linux?

**Comment by thocevar** [comment]
I tried all widgets in our Visualization section on Windows. Almost all of them work.
- Distributions: background in the widget changes from gray to white on Ctrl-C.
- Venn Diagram: the copied image has white background, while the widget has gray.
- Pythagorean Forest: Ctrl-C doesn't work.
- CN2 Rule Viewer: Ctrl-C doesn't work (it's a table not an image).

**Comment by lanzagar** [comment]
Similar on linux.
Scatter plot also has (unnecessary) bottom and right borders when I paste the image

**Comment by ajdapretnar** [comment]
I think white/gray background is actually expected. I assume images have transparent background, with the image being on gray in Distributions and Venn by chance. @janezd Correct me if I am wrong.

**Comment by lanzagar** [comment]
That the copied image has a different background is not so problematic.
But the case in Distributions, where pressing Ctrl-C changes the look of the widget is a bug (even if pretty harmless).

**Comment by borondics** [comment]
Is Mac OS going to be supported too?

**Comment by ajdapretnar** [comment]
@borondics I have asked for Win and Linux just because I have already tested on Mac and it works. :) However, I assume these bugs are present regardless of the platform.

**Comment by borondics** [comment]
Ajda, you are right indeed it works. For whatever reason I had to restart
my Power Point and it worked fine. :D

**Comment by irgolic** [comment]
Perhaps a 'Copy plot' button should be added to the status bar?

**Comment by ajdapretnar** [comment]
I would be cautious with extending the status bar. It is growing rapidly and some widgets can't handle many more options below.

Also, I don't think it is really needed. Anyone can simply save an image on a computer and use it in ppt. A shortcut is just a welcome benefit.

**Comment by borondics** [comment]
Would it be possible to somehow match the Copy/Paste image resolution to the screen resolution? Or at least increase it so that the Copy/Paste image becomes better quality? What I really like is of course that it is only the graph that Copy/Paste gives and that the last number on the axis is also fully captured, while it is not visible in the window.

Here is what I am getting on a Mac with Retina screen.

Copy/Paste
Resolution: 913x691
![image](https://user-images.githubusercontent.com/6304794/88394904-82cb5500-cdc0-11ea-9689-d6b8f4f9e68e.png)


Screen Capture tool of OS X (let's ignore that the whole widget window is on the picture)
Resolution: 2024x1668
![image](https://user-images.githubusercontent.com/6304794/88394964-9aa2d900-cdc0-11ea-89ac-4fb0fd2e3776.png)

**Comment by richardharrishk** [comment]
I can't seem to export data easily to an excel - or power point.  it's so easy to import - impossible to export - why do I get pickle files...?!  I just want excel, or png/jpeg.

**Comment by janezd** [comment]
Attempted fixes for retina are in https://github.com/biolab/orange-widget-base/pull/208.

It appears, though, that macOs clipboard does not know the actual dpi of image data and always assumes 72 dpi. Copied images will have the full resolution but will appear too large.

**Comment by janezd** [comment]
Fixed via https://github.com/biolab/orange-widget-base/pull/208.
