### ISSUE TITLE
Color node is destructive

### ISSUE THREAD

**Issue by AlexisMARTICOMTE** [biolab/orange3#4895]
Hello !
so

**Explain the bug**
I cant use the color node on my data since i downloaded the last version of orange (3.26.0), the version i was working on before was the 3.24.1.
From now on, if i use the color node on my categorical data, this categorical data will be lost in the following nodes (? appears instead of 6 or 3 for example), but after further researchs, it seems that its my way to make csv that is not well recognized ? (i saved my csv with the save data node, reused it and the color node was working on this new csv

**How to reproduce the problem.** 

[orange_color_node_bug.zip](https://github.com/biolab/orange3/files/4895384/orange_color_node_bug.zip)

To reproduce the problem, open the workspace, put the csv_not_working.csv in a csv node, and look at the node after the color node , there will be no colors and the categorical information is now "?"

the csv_working is a csv made with orange from a csv not working but actually work, so maybe i dont make my csv the good way idk)

**Which version of Orange are you using? How did you install it?**
orange is in 3.26.0, installed with the .exe for windows

**What is your operating system?**
I am on windows 10 updated

here is an image of what i saw : https://cdn.discordapp.com/attachments/633377197196836875/730338897820909680/unknown.png)

**Comment by janezd** [comment]
First, thanks for your exemplary report. :) And apologies for the late response.

The bug you discovered goes deeper. The problem occurs because of something that happens in Edit Domain, but the real bug is deeper in the core.

I guess I have fixed it (I just need to add some tests), but as a temporary workaround, you can load the data using the file widget, which will allow you to set the type of "all_polygons" to categorical, so you won't need to use Edit Domain.

**Comment by AlexisMARTICOMTE** [comment]
Thx for the update, have a nice day !

Le ven. 24 juil. 2020 à 12:41, Janez Demšar <notifications@github.com> a
écrit :
