### ISSUE TITLE
add logical "or  ,and ,  ( ,)"  combination of conditions  in row select addon

### ISSUE THREAD

**Issue by yuanxin-cq** [biolab/orange3#4938]
Now，we can do 'and' caculation in row select addon by default, hope to have a flexible combination of conditions caculation.

**Comment by janezd** [comment]
We had disjunctions in an earlier version of the widget, but we removed them because they only complicated the user interface, but they were almost never used. Reasonable subgroups are very seldom defined as disjunctions of conjunctions.

If you wish, you can use two (or more) Select Rows widgets and then Merge.

**Comment by ajdapretnar** [comment]
I often need OR instead of AND and I have to do it in pure Python then return to Orange. A usual use case is to filter the data that either has missing values OR some wrong values. So it is not just subgroups as such, but data filtering and preparation. I do this it is a valid use case, but I agree the widget could get overly complicated.
