### ISSUE TITLE
tuple index out of range, at Add-ons

### ISSUE THREAD

**Issue by lalberts** [biolab/orange3#4944]
Installed Orange yesterday on WIn10 2004 by downloading and running th esetup for all users 3.26.0-miniconda.exe.
Whenever I try to click on Add-ons
I get the error Message:
Traceback (most recent call last):
  File "C:\Program Files\Orange\lib\site-packages\orangecanvas\application\canvasmain.py", line 2044, in open_addons
    .format(name),
IndexError: tuple index out of range

What should I do?

thanks
Lukas

**Comment by markotoplak** [comment]
I am very sorry about this, this is a bug that I caused. It has been fixed in biolab/orange-canvas-core#107 and therefore the next release should be fine.

You can circumvent the bug by either (option 1) running Orange as the administrator or (option 2) install Orange only for the current user. Were it not for that bug, a dialog would open which would have asked you just that.

**Comment by lalberts** [comment]
disinstall from win-apps.
needed to remove user/appdata/orange..

but working now.. thanks
