### ISSUE TITLE
Force regression through origin (zero)

### ISSUE THREAD

**Issue by jkmgeo** [biolab/orange3#4954]
**relevant info**
macOS 10.13.6, orange 3.26.0 from Anaconda distribution (conda 4.8.4).

**Is your feature request related to a problem? Please describe.**
No.

**Here, write a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]**
When using the Canvas, Model > Linear Regression and Educational > Polynomial Regression do not allow forcing of the regression through 0, i.e. Coefficients always include intercept and independent variable terms.

**Describe the solution you'd like**
Add GUI elements (e.g., checkbox) to Linear Regression and Polynomial Regression widgets that allow the user to specify the forcing of the regression through the origin.

(Separately, perhaps add a Model > Polynomial Regression feature separate from the Educational add-on?)

**Add a clear and concise description of what you want to happen here**.
Return regression coefficients so fit `y = m_1x^n + m_2x^{n-1} + ... + m_nx + b` is calculated such that `b = 0`. (May only be feasible/valid for polynomials of first order.)

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

Thanks! (And apologies if this feature exists. However, a search of the GUI and documentation was not fruitful.)

**Comment by janezd** [comment]
The feature would indeed be trivial to add and there's plenty of space in the GUI. However we do not want to add redundant features (especially not to educational add-on), because the user (in this case - a student) may accidentally enable them. It would be just another point where something can go wrong.

Educational add-on is essentially a collection of widgets that we ourselves use for teaching, so it is tailored specifically for our courses. We use this widget primarily to show overfitting and how to fight it with regularization. Although our lectures are unscripted and largely driven by students, we (at least I) never encountered a situation where I'd need this feature. I am however sincerely open to use cases that you may present.

You also suggested "Polynomial Regression feature separate from the Educational add-on". Do you think polynomial regression model with a single independent variable would be useful in real world?

(By the way -- we should be discussing this in [another repo](https://github.com/biolab/orange3-educational).)

**Comment by ajdapretnar** [comment]
I think @jkmgeo was not referring to Educational add-on as such, but generally having this feature for Linear Regression (and a new widget Polynomial Regression?). Or did I get it wrong?

**Comment by markotoplak** [comment]
In an educational widget, especially, I'd like to have an option to remove the bias term from the model. To actually show students how important the bias really is.

**Comment by janezd** [comment]
My bad. Of course. Alright, let's do it. In both, I guess.

**Comment by jkmgeo** [comment]
Thanks, all, for the fast replies. 

@ajdapretnar is right. I was requesting the addition of a new Polynomial Regression widget in the Model menu as a secondary request. My main request is to add a "force through zero" feature/toggle for the Linear Regression widget. 

The reason I'm requesting this is that I use a lot of chemistry data, and particularly the ratio of two elements. It would be nice to be able to select a subset of my data on a binary A vs. B plot (e.g., by selecting in a scatter plot) and get a sense of the elemental ratios (A/B) via linear regression forced through zero during data exploration work. Alternatively, adding "force through zero" and "display regression equation" toggles beneath the "Show regression line" option in the scatter plot GUI would suit me, but I don't want to impose too much on what the devs think is the best implementation. (I don't think the "Treat variables as independent" option located there right now is the same, but correct me if I'm wrong.)

Cheers!
