### ISSUE TITLE
Bayes net structural learning

### ISSUE THREAD

**Issue by GottM** [biolab/orange3#4972]
Hello,
This post is not about an issue but about a proposed enhancement.

I would like to suggest a new widget running bayes net structural learning on at least categorical data inputs running algorithms like [bnlearn] and [networkD3]. The main outputs of the new widget would be a "force network" showing a learned model of how the input features correlate (without directed edges thus no causal preconception) and the log-likelihood measuring the quality of the Bayesian model. One would opt one out of several optimization algorithms: in particular the very efficient "Tabu search" and "Chow-Liu".

This widget would enable a quick overview and understanding of wide datasets (many features), possibly helping further causal hypothesis modeling and enable "dimensionality" reduction for a given target feature predictive modeling.

http://www.bnlearn.com/
http://christophergandrud.github.io/networkD3/
https://paulgovan.shinyapps.io/BayesianNetwork/

Best regards,
G.

**Comment by janezd** [comment]
We have discussed this at today's meeting. This belongs to the would-be-nice-to-have category, but it is quite a project and nobody in the core group is currently interested or available. Would you consider doing it?

For the time being, I'm moving this to #4090, where we collect such ideas.

**Comment by GottM** [comment]
﻿
Hello Janez,
As you can read below, Paul Govan shares our enthusiasm and would be willing to join forces with Biolab to extend it in the field of Bayes nets and notably Chow Liu trees.

Yet, I think he is mainly using R and would need transcription support into Python if Python is the only coding option for Orange Biolab.

Would you think we can find a way forward to bring Paul in, maybe with limited support from some Python experts in your teams?

Best regards,
Gottfried

**Comment by janezd** [comment]
Including code in R is not an option because it would require the user to have R installed. Plus, there would be an additional dependency, the module for interaction between R and Python; such dependencies may be nightmare to maintain. Finally, transferring data back and forth is not very inefficient. Having R code would only be possible if this would be an add-on, but even then I would warn about maintenance problems.

If there is (or there would be) a reasonable-quality bn code in Python and if the widget would be simple, that is, without any visualization (note that Orange has an add-on that includes network visualization), just various radio buttons and combo boxes, we can help. But implementation (or translation) of bayesian networks in Python or implementing complex visualization ... would require too much effort.
