### ISSUE TITLE
Select Columns: ignores upstream changes

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#4978]
- [ ] **What's wrong?**

I assume this is not only Select-Columns-related, but a general context setting issue.

I open the File widget, load a data set. Connect Select Columns to File. Then I change variable role in File, say I assign ID variable to metas. I press Apply. Changes are not reflected in Select Columns.

- [ ] **How can we reproduce the problem?** 

File (iris).
Select Columns.
File (change sepal width to be a meta variable).
Open Select Columns and see that sepal width is not in metas.

- [ ] **Which version of Orange are you using? How did you install Orange?**
3.27.dev

- [ ] **What is your operating system?**
OSX

**Comment by janezd** [comment]
Works as intended, though unexpected. Select Columns overrides the changes in File widget.

However, the user would (reasonably) expect the Select Columns widget to apply only changes that (s)he made -- manually and explicitly. Instead, it stores the roles of all variables as shown in the widget, and applies them to any matching new data (via contexts).

It could be possible to stores only changes (though it could lead to unintended consequences in over-general context matches). However, the widget does not store only the assigned roles but also indices of variables, so the user can change the order of attributes. Because of this, changing the role of one variable changes indices of all that follow, and these changes would be recorded, and consequently those variables would then also change their roles. In short: it would be a mess, and it would be unpredicatble for the user.
