### ISSUE TITLE
Warnings can get mixed up between widgets

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#5008]
I have a specific configuration where I get an unexpected read warning in the File widget.

To reproduce:
1. File (heart disease)
2. Test & Score, LR as learner
3. Set LOO in T&S.
4. Let T&S run a bit, then change the data set to iris.
5. Read warning occurs.

```
lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
```

Probably something that should be handled more gracefully.

**Comment by markotoplak** [comment]
Seeing this bug was a consequence of two things:
- frequent warnings, generated by LOO and Logistic Regression, which, prior to #5027, showed warnings very frequently.
- a non-threadsafe warning handler (`catch_warnings`) in OWFIle

So a warning was shown by training within Test&Score was caught by OWFile. Which means that we probably need to handle warnings differently.

After #5027 is merged, this will be harder to reproduce. To reproduce it afterwards, set `max_iter=100` in `owlogisticregression.py`, make a workflow as instructed by @ajdapretnar and keep changing datasets until you get lucky.
