### ISSUE TITLE
Proposal: Add Python support to WinUI 3

### ISSUE THREAD

**Issue by delzac** [biolab/orange3#5014]
Hi, there's a movement to try to get Python support for native Windows GUI apps. Since i use Orange on windows a lot, i thought maybe the maintainers might want to consider supporting this? Please free feel to close this if it's the wrong avenue.

Link to the github post can be found [here](https://github.com/microsoft/microsoft-ui-xaml/issues/3364)

**Comment by janezd** [comment]
Orange uses Qt because it runs on Windows, macOs and Linux, without us having to write any OS-specific code (except is a very small number of situations). Since most of Orange's code is about GUI, using some Win-specific library would basically duplicate the work.

If you consider PyQt as a layer between Python and native GUI (of whatever system), Orange already uses native GUI, except that it uses a universal library that exist and not a specific one which does not, and never may. :)
