### ISSUE TITLE
Metas first in lists

### ISSUE THREAD

**Issue by borondics** [biolab/orange3#5021]
- [x] **What's your use case?**

Typically there are more features in a dataset than meta variables, but those can be pretty important, especially for visualizations. This comes up in data reduction like PCA (very often used in spectroscopy workflows having usually hundreds of features) all the time, where PCs are added by default as metas. However, they are pretty hard to access in Scatter Plot for example because they are at the end of the list in the text box.

- [x] **What's your proposed solution?**

Would it be possible to order the lists such that metas come first?

- [x] **Are there any alternative solutions?**
Not for this problem.

**Comment by janezd** [comment]
The default order is already classes, metas, attributes. Some widgets, like x and y in scatter plot, explicitly override this.

We had a discussion and opinions differed. There are cases where having metas first would make sense, but some of us disagreed with having metas first on scatter plot (as in "this is exactly where you would not expect metas"). There are cases where the number of meta attributes is small and the number of other variables is large, but some pointed out cases where it's the opposite (as in "you never worked with texts, guys").

In absence of clear cut, we decided not to change anything, because in two weeks we may find reasons to revert it.

**Comment by borondics** [comment]
OK, thanks for considering it!
