### ISSUE TITLE
save the result of "Preprocessing Text"

### ISSUE THREAD

**Issue by Rezabagheriloye** [biolab/orange3#5035]
Hi every,

I want to save the result of "Preprocessing Text" of the Corpus in CSV or TXT format. I used "Save Data" while the result was the same with the original corpus. 
I was wondering if anyone show me how to save clean data which is the result of "Preprocessing Text".

<img width="379" alt="Capture" src="https://user-images.githubusercontent.com/72498672/96333321-002bfc00-1076-11eb-816c-8ef686d24abd.PNG">

**Comment by PrimozGodec** [comment]
CSV or TXT format does not have the capacity for storing preprocessed text data (Corpus stores preprocessing results separate from the data table). Instead, the user could save preprocessed Corpus with selecting Pickle format (.pkl). 

While testing this possibility I got another error which must be solved. Since this issue is more suitable to the orange3-text repository I will close the issue here and reopen it there.

**Comment by PrimozGodec** [comment]
Thank you for this report and discovering the new issue.
