### ISSUE TITLE
Predictions: IndexError when clicking outside the table

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#5074]
- [ ] **What's wrong?**

Predictions crashes when clicking outside the table fields.

```
-------------------------- AttributeError Exception ---------------------------
Traceback (most recent call last):
  File "/Users/ajda/orange/orange3/Orange/widgets/evaluate/owpredictions.py", line 1130, in select
    self.store.select(selection, flags)
  File "/Users/ajda/orange/orange3/Orange/widgets/evaluate/owpredictions.py", line 1057, in select
    rows = {selection.model().mapToSource(selection).row()}
AttributeError: 'NoneType' object has no attribute 'mapToSource'
-------------------------------------------------------------------------------
```

- [ ] **How can we reproduce the problem?** 

Create a prediction workflow with a small test data set. Click outside the table.

- [ ] **What's your environment?**

- Operating system: OSX
- Orange version: 3.28.dev
- How you installed Orange:

**Comment by erelin6613** [comment]
Hey, I would like to take a look at this one, may I? Thanks in advance!

**Comment by ajdapretnar** [comment]
@erelin6613 Hello! You are welcome to take this over! ⭐

**Comment by irgolic** [comment]
@erelin6613 Hey, nice to meet you, thanks for the initiative. If you've any questions, feel free to ask on [Discord](https://discord.gg/FWrfeXV) :)

**Comment by erelin6613** [comment]
@irgolic @ajdapretnar
I have been trying to dig deep into the warning the terminal was displaying:
`QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 0, 0, 0, 100'`
For now I just added functionality to 'just not break' but was not able to discover some deeper problem if there is any. If you have any idea why `SharedSelectionStore.selection.model()` could return None, I appreciate you for suggestion. Otherwise a fix for stability is available on my forked repo.

**Comment by irgolic** [comment]
@erelin6613 Create a new branch with your fix on your forked repo, then create a pull request https://github.com/biolab/orange3/compare, and we can see what's up.

You should be able to find some help here: https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/working-with-forks
