### ISSUE TITLE
Geo Map disables Opacity when data subset signal present

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3#5109]
**What's wrong?**

Feeding a data subset into Geo Map disables Opacity. Which is wrong, since opacity allows to see beyond the data points and perhaps read some of the labels on the map, which are now, with disabled opacity setting not readable.

![image](https://user-images.githubusercontent.com/726604/101166830-37ac3300-3639-11eb-963b-5086eb83559f.png)

In the old version of the widget a similar visualization looked like this:

![old-one](https://user-images.githubusercontent.com/726604/101167333-097b2300-363a-11eb-8f4c-6d0dd12460d5.png)

Notice also that the opacity in the old version of the widget was such that it was possible to read the map labels.

**How can we reproduce the problem?**

Here is the workflow. Use the Philadelphia Crime data set.

![image](https://user-images.githubusercontent.com/726604/101167561-5b23ad80-363a-11eb-978d-4cf1051f7182.png)

[philly.ows.zip](https://github.com/biolab/orange3/files/5642912/philly.ows.zip)

**What's your environment?**

- Operating system: macOS Catalina
- Orange version: 3.27
- How you installed Orange: dmg

**Comment by janezd** [comment]
This behaviour is inherited from the base widget for projections, e.g. scatter plot behaves the same. This makes the subset easier to identify.

Have you reported this in orange3 repository instead of in https://github.com/biolab/orange3-geo because you would like to change this general behaviour, or by accident and you're only suggesting a change in this widget?

**Comment by janezd** [comment]
Either we increase the contrast if the subset is present OR we display a warning if opacity is too low in presenece of subset.
