### ISSUE TITLE
Add median to Feature Statistics

### ISSUE THREAD

**Issue by eguegain** [biolab/orange3#5317]
- [ ] **What's your use case?**
I need some statistics about the features of my data, including the median from each feature.
Feature Statistics is very close from what I need but doesn't provide the median.

- [ ] **What's your proposed solution?**
Adding a column with the median in Feature Statistics would solve my problem. 

- [ ] **Are there any alternative solutions?**
I don't know Orange well enough to provide any alternative solutions.

**Comment by janezd** [comment]
I forgot the reason why this widget doesn't show medians. Does anybody remember it? (In case not: I added it, it's trivial.)

**Comment by pavlin-policar** [comment]
I think the reasoning was that there's no real analogue for discrete variables. We had to pick some measure of centrality, and mean is usually what people want. For discrete variables, the mode is probably the most reasonable measure of centrality, so we went with that (even though mode seems more analogous to the median than the mean).

I think the reason we didn't do both was because there would be too many columns. And then what do we put as the analogue for discrete variables? The mode is already there in the "Mean" column. Do we show the mode twice? Do we move the mode to the median column and leave "Mean" blank for discrete variables? It's not clear to me what the best option would be.

But yeah, medians would definitely be nice to show.
