### ISSUE TITLE
Feature Statistics: order of variables

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#5329]
- [ ] **What's wrong?**

Not sure if this is wrong or just a heuristic I do not yet understand, but Feature Statistics has a strange order of variables. Does the order mean anything? Because it is not the same as in domain.

- [ ] **How can we reproduce the problem?** 

Look at any file in Feature Statistics. The weirdest one is heart-disease.

- [ ] **What's your environment?**

- Operating system: OSX
- Orange version: 3.28.dev
- How you installed Orange: git

**Comment by janezd** [comment]
They are ordered by type -- first numeric, then categorical. Within a type, they are in the same order as in the domain, just backwards. Any child can see this.

You're arrogant enough to believe that you have a better idea?

Seriously, the widget has no button for "original order" (nor would I add it), so it has to be sorted by something. Type is convenient because variables of different types show different statistics. Yet within each type, I suppose alphabetical order would be better.

Note that sorting is stable. If you sort by names and then re-sort by type, they renamed sorted alphabetically within a type. I suppose that we should set the initial order to be like that.
