### ISSUE TITLE
AUC confidence intervals

### ISSUE THREAD

**Issue by rehoyt** [biolab/orange3#5372]
- [ ] **Are there any alternative solutions?**

**Comment by janezd** [comment]
I assume you'd like to say you'd like to have them in a widget like Test and Score?

I know how to compute confidence intervals for AUC computed from a single test set (because of its equivalence of Wilcoxon-Mann-Whitney's statistics), but I'm not sure how to compute them from, say, results of cross-validation. You know some decent paper about this? (Since you want a new feature and programming it is on us, you can do the Googling part for us. :)

**Comment by rehoyt** [comment]
Because the computational engine for Orange is Python, would you want to create CIs with Python? Here is a potential solution on StackExchange using cross validation

https://stats.stackexchange.com/questions/100159/confidence-intervals-for-auc-using-cross-validation

**Comment by janezd** [comment]
No, this is wrong. The code naively underestimates the variance by ignoring the correlations between samples.

The paper to linked at the comment recommends bootstrapping and, as I understood, provides empirical arguments by using it with cross-validation. I would rather not rely on such arguments (and with a single method), and, at any rate, this doesn't help us because it works only with bootstrapping and does not address how to compute CI for AUC in general.

Now you see why Orange doesn't compute these intervals. :)

**Comment by rehoyt** [comment]
If k=10 you have multiple cross-validations, why not report the variance for all calculations? In other words, cross-validation takes the average of the 10 cross-validations. This should give you a min-max and should be the approximation of the confidence intervals

**Comment by rehoyt** [comment]
Is there a way to duplicate this image in Orange?

![image](https://user-images.githubusercontent.com/25651922/113161688-3f08d500-9204-11eb-96c6-8e62163f22ea.png)

**Comment by janezd** [comment]
> If k=10 you have multiple cross-validations, why not report the variance for all calculations? In other words, cross-validation takes the average of the 10 cross-validations. This should give you a min-max and should be the approximation of the confidence intervals

As I said, this underestimates the variance because it assumes that we deal with an independent sample of k measurements, while in reality the training subsets share most of the data. This is what the code does and it's wrong.

There are ways to counteract this, though, as I recall, they are just estimates that were empirically shown to give reasonable results. And I think I saw this done only for classification accuracy. And, finally, it's still just k-fold cross validation, while the widget supports different sampling techniques.

**Comment by janezd** [comment]
> Is there a way to duplicate this image in Orange?

You cannot get *exactly* this figure, but you can draw separate ROC curves for all folds. The ROC widget doesn't show AUC, in particular not per fold. You can get this by connecting Data Sampler to SVM and to Predictions, and manually switch between folds and write down the AUCs.
