### ISSUE TITLE
Row uids

### ISSUE THREAD

**Issue by astaric** [biolab/orange3#54]
Some widgets can return selected examples object, which can be used to filter visualization widgets. Selected examples can sometimes be derived from different Table than the one they are used to filter (i.e. table created with discretization, filtering, selecting attributes, ....).

We could implement this by generating a list of guids when table is created and pass it along, just as we pass weights, as all new tables are created through class methods on Table class. There are some operations, that are not injective, they would have to generate new row id-s manually. (This might already be solved, if the code starts by creating a new empty table.)

Things are more complicated with sql backend, but solvable, as long as there is a unique column in the table.

**Comment by astaric** [comment]
Table has attribute ids (added in 46570001308), which is a numpy array of numbers, that are used as row identifiers. All data modifications done via Table.from_table preserve row ids. Classes extending Table can provide their own implementation of ids.

**Comment by hugobuddel** [comment]
Thank you @astaric! This patch certainly would be useful for our fork.

Some thoughts/comments/questions:
* Wouldn't it be 'cleaner' to add the `id` attribute to the `Instance` class instead of to `RowInstance`? Because conceptually any Instance can have an `id` while only RowInstances can have a `row_index`.
* Is it possible for classes extending Table to provide non-numerical ids? E.g. a string, or a tuple? At first glance there doesn't seem to be anything preventing this, but maybe the ids are used somewhere else in a way that is only compatible with integers.
* Can a certain Instance in a Table be addressed using its id? That is, is something like `my_table[my_instance_id]` possible? Overloading `__getitem__` is probably hard when both `id` and `row_index` are integers, but should be possible when `id` can be something else like a string.

This is just me thinking out loud for our own project, so don't feel obliged to reply. I'll try to answer these questions myself by merging in your nice work.

**Comment by astaric** [comment]
1. You are correct. id should be added to Instance. (see #558)

2. Id can be any object, as long as it is hashable. Currently they are only used in ScatterPlot widget, where they are added to a set, so they have to be hashable.

3. Currently, we use ids to check whether the two instances from different tables represent the same "real world" instance. When using bootstrapping or other methods that use sampling with replacement, one Table can contain multiple instances with the same id. This would make addressing instances by id complicated.

In a special case, where ids are known to be unique, this would indeed be possible. You would probably need to store the id -> row_id mapping in a dict to speedup the access.
