### ISSUE TITLE
Predictions widget sorts numerical columns as text

### ISSUE THREAD

**Issue by processo** [biolab/orange3#5405]
The table view of the _**Predictions**_ widget - when clicked on column header - sorts numerical values like text instead of number in the _**target**_ and _**prediction**_ columns but NOT in the rest of the data columns. (e.g. "100.0" < "58.0" because it starts with a '1')

![image](https://user-images.githubusercontent.com/5299789/115367050-20c04480-a1c6-11eb-8a0d-bf7837237858.png)

**Comment by janezd** [comment]
Thanks for reporting this.

This widget is, well, complicated.

To whomever would work on this: I think the widget should be migrated to `orangewidget.utils.itemmodels.AbstractSortTableModel`. This would improve its performance (see https://github.com/biolab/orange3/blob/master/Orange/widgets/evaluate/owpredictions.py#L404), as well as simplify obtaining the keys for sorting. The problem is that the current code expects various `QSortFilterProxyModel`'s method at several places.
