### ISSUE TITLE
Rank score keeps changing without changing data 

### ISSUE THREAD

**Issue by mari-mk** [biolab/orange3#5447]
I'm using Orange for mineral prospectivity mapping using the Random Forest model. The issue I'm having is that everytime I open the project, the rank score for RF keeps changing, giving me different priorities, even though I'm not changing any of my data. It seems to directly affect the predictions. 

I'm using Windows 10. I've tried downloading the latest version (3.28), but the problem remains.

![orange issue1](https://user-images.githubusercontent.com/84459056/118832466-0649bb80-b897-11eb-9294-ffdde50b39a1.jpg)
![orange issue2](https://user-images.githubusercontent.com/84459056/118832473-06e25200-b897-11eb-98db-38fa0e01acd3.jpg)
![orange workflow](https://user-images.githubusercontent.com/84459056/118832476-06e25200-b897-11eb-8b87-b3f256bdfb08.jpg)

**Comment by markotoplak** [comment]
Random forest is indeed random. If you enabled the "Replicable training" option in the Random Forest widget, you will get the same results every time. 

More importantly though, if feature scores keep changing substantially on reruns this points out that you are using too few trees in your forest. I'd suggest you increase your number of trees sufficiently so that changes between reloads are only slight. Then, enable the "Replicable Training" option (if you still need it).
