### ISSUE TITLE
Hierarchical Clustering by Column Does not Output Cluster Numbers

### ISSUE THREAD

**Issue by brainy-ninja** [biolab/orange3#5467]
- [ ] **What's wrong?**

Performing a hierarchical clustering of data by column does not output the cluster number of the columns. HCA of same data by row does output cluster number.

- [ ] **How can we reproduce the problem?** 

[Archive.zip](https://github.com/biolab/orange3/files/6595014/Archive.zip)
!-- Describe the steps (open this widget, click there, then add this...) -->
Perform HCA on data, selecting columns. Select all clusters individually. Output from HCA does not contain cluster numbers when data are clustered by column. Similar workflow in same file clustering by row works as expected. Attached file has workflow and primary data. 

- [ ] **What's your environment?**

- Operating system: MacOS 11.4
- Orange version: 3.29.1
- How you installed Orange: Downloaded the install package from orangedatamining

**Comment by janezd** [comment]
It can't. The Hiearchical clustering widget outputs a data table whose rows represent data instances. When clustering by rows, each row belongs to a cluster, so the widget adds a column that shows the cluster. When clustering the columns, each column belongs to a cluster. The widget cannot add a row that would represent a cluster (because we have the same data type for the entire column, so this row would contain cells of different data types).

Cluster number could be indicated as a meta-information for each variable, but I don't know whether and how would this be useful. If anyone knows otherwise, please correct me.

**Comment by janezd** [comment]
Similarly to #5468, the cluster index could indeed be added as an attribute of variable, which would be useful if the Transpose widget turns this into a column. (Does it?)

**Comment by ajdapretnar** [comment]
It does. For example, "bow-feature" and "hidden" from Text add-on become meta attributes.
