### ISSUE TITLE
CDLib (NetworkX and iGraph) and KatateClub/RolX

### ISSUE THREAD

**Issue by BrandonKMLee** [biolab/orange3#5479]
- [x] **What's your use case?**
CDLib contains two features that are not the main features of NetworkX:
- Node Community Classification (e.g. Twitter user community classification)
- Node Centrality Indices (e.g. Twitter user influence in a graph)

It relies on the Graph objects of NetworkX and iGraph to work. Ref:
- Main library https://cdlib.readthedocs.io/en/latest/
- https://github.com/igraph/igraph/
- https://networkx.org/documentation/stable/

KarateClub is another library that provides the feature of "Node Embedding" derived from NetworkX objects
- https://karateclub.readthedocs.io/

There are examples that apply this into Node Role Classification (e.g. Twitter KOL/follower distinction)
- https://github.com/benedekrozemberczki/RolX and https://github.com/dkaslovsky/GraphRole

- [x] **What's your proposed solution?**
1. Allow the use of node classifiers to be made into a module.
Input: NetworkX Graph
Selector: Community Detection or Role Detection algorithms
Output: Dictionary of node names as keys and community/role affiliation prediction as values

2. Allow the use of evaluation metrics to be made into a module
Input: Predicted node partition, Ground Truth data
Selector: Accuracy measures e.g. NMI, ARI, Purity...
Output: Accuracy Index

3. Allow the centrality measure to be made into a module
Input: NetworkX Graph
Selector: Centrality measurements
Output: Dictionary of node names as keys and centrality quantification as values

- [x] **Are there any alternative solutions?**
There have not been any GUI solution for this at the moment

**Comment by BrandonKMLee** [comment]
> There is an add-on, but it no longer uses networkx
That is unexpected that Orange3 is not as tightly tied to Network Node Classification tools.

**Comment by janezd** [comment]
The add-on used networkx until we realized that the only thing that we used were

- one file reader, which was actually broken, so as a workaround we had to write a function that modified the input file so that networkx would be able to read it, but the whole hack was more complicated than writing the reader from scratch;
- several functions that computed various statistics, but worked only on toy examples because they were in pure Python and too slow for anything serious.

Hence we stopped using networkx and instead implemented the necessary data structures and code ourselves. Some statistics are still missing, but those didn't properly work in networkx, neither.

But I still don't understand what do you actually wish. Please read the first two paragraphs of my previous comment again.
