### ISSUE TITLE
Random: Cannot copy model with Impute preprocessor

### ISSUE THREAD

**Issue by VesnaT** [biolab/orange3#5480]
- [ ] **What's wrong?**

Model with `Impute(method=Random())` preprocessor can not be deepcopied.

- [ ] **How can we reproduce the problem?** 

Run the following snippet.
```
import copy
from Orange.data import Table
from Orange.preprocess import Impute
from Orange.preprocess.impute import Random
from Orange.regression import LinearRegressionLearner

learner = LinearRegressionLearner(
    preprocessors=Impute(method=Random())
)
copy.deepcopy(learner(Table("housing")))
```

- [ ] **What's your environment?**

- Operating system: MacOS
- Orange version: master
- How you installed Orange: source

**Comment by janezd** [comment]
`Random` contains `Continuous`, which is derived from `Distribution` and, in turn, from `np.ndarray`. The problem is that

```python
import numpy as np
import pickle

class A(np.ndarray):
    pass

a = A([1, 2, 3])
a.x = 12

b = pickle.loads(pickle.dumps(a))
b.x
```

fails with 

```
AttributeError: 'A' object has no attribute 'x'
```

because `ndarray` implements `__reduce__` and does not copy attributes added in derived classes.

We will need to implement `__reduce__` for all classes derived from `ndarray`. Deriving from `ndarray` is nothing but trouble, and we should have avoided it before it was too late.

Alternatively, we should check whether `Distribution` and `Contingency` could be refactored without breaking too much code. These classes are about as useless and thus as unused as `Instance` and `RowInstance`.

**Comment by janezd** [comment]
> We will need to implement `__reduce__` for all classes derived from `ndarray`.

... as well as `__deepcopy__`.

> Deriving from ndarray is nothing but trouble, and we should have avoided it before it was too late.

When I die and go to purgatory, I won't do anything special; I'll atone for my sins by continuing to maintain them.
