### ISSUE TITLE
Hierarchical Clustering: change of cluster colors at k=18

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#5696]
**What's wrong?**

Not sure whether this is a bug or designed intentionally, so reporting it just in case.
Clusters change colors when selecting clusters in the dendrogram in Hierarchical Clustering after level 18 (when the number of clusters is 18). Initial cluster colors become different when passing from 17 to 18. 

**How can we reproduce the problem?** 

Change cluster numbers in the dendrogram.

![hc-colors](https://user-images.githubusercontent.com/12524972/142181354-13ffdc56-2be2-4d55-a3f4-b0af2731edb7.gif)

**What's your environment?**

- Operating system: OSX
- Orange version: 3.30.2dev
- How you installed Orange: pip

**Comment by janezd** [comment]
This is a result of intentional decision.

`DefauiltRGBPalette` has 17 colors, starting with some that are presumed to look nicely and be distinguishable, and continuing with some that are still as distinguishable as possible. After 17, it switches to a different, Glasbey palette. See https://github.com/biolab/orange3/blob/master/Orange/widgets/utils/colorpalettes.py#L162.

We could use Glasbey from the beginning, but we preferred a different set of colors for smaller palettes. Most widgets do not show that many colors anyway, so our smaller palette is better. For dendrogram, which occasionally does, we could use Glasbey all the time, but then the colors would not match those in other widgets.
