### ISSUE TITLE
Learner widgets fail (without warning) without proper preprocessing

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3#5703]
**What's wrong?**

When using "Select Relevant Features" preprocessor with a learner, the learner fails with error "Fitting failed. Wrapped scikit-learn methods do not support multinomial variables". Note that when the same preprocessor is given the same data it works, that is, it returns a data set with reduced number of features.

<img width="899" alt="image" src="https://user-images.githubusercontent.com/726604/143118996-ba078b7b-c132-4610-8b29-3c3c63c2634a.png">

<img width="663" alt="image" src="https://user-images.githubusercontent.com/726604/143122233-61fc95f3-f691-4b62-989f-4d4110b80be9.png">

**How can we reproduce the problem?** 

See the workflow above. I have used the heart_dissease data set.

[preprocessor-bug.ows.zip](https://github.com/biolab/orange3/files/7591004/preprocessor-bug.ows.zip)

**What's your environment?**
- Operating system: mac os x
- Orange version: head (from github)
- How you installed Orange: pip install -e .

**Side note**

The workflow with Test & Score and preprocessed learner fails as well.

<img width="414" alt="image" src="https://user-images.githubusercontent.com/726604/143123655-8d783270-b18a-4a29-83ff-0913085c85f0.png">

but when preprocessor is given to the Test & Score, it works. 

<img width="403" alt="image" src="https://user-images.githubusercontent.com/726604/143124893-336bb2ef-24e3-4796-ae76-b7051a1c9a34.png">

**Comment by janezd** [comment]
Works as intended. See [documentation](https://orangedatamining.com/widget-catalog/data/preprocess/#:~:text=This%20will%20override%20the%20default%20preprocessing%20pipeline%20for%20the%20learner%20and%20apply%20only%20custom%20preprocessing%20pipeline%20(default%20preprocessing%20steps%20are%20described%20in%20each%20learner%E2%80%99s%20documentation)).

One could wish to have a better message, but I don't see a good way to implement it - the widget can't know whether an error occurred due to preprocessing or something else. One thing that we could do, though, would be showing an information that default processing was replaced by the one from Preprocess widget and that the user is now responsible to include everything necessary.

**Comment by markotoplak** [comment]
@janezd, I like your idea of showing this information to the user. In hindsight, it is so obvious that we could even be a bit ashamed of not already having it.
