### ISSUE TITLE
File can not read Google Sheets

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#5723]
**What's wrong?**

Google Drive apparently changed the API to retrieve Google Sheets. Now, one cannot just enter sharable link to load the data (Read error).

We should check the API and see whether we can fix this so that one can easily load the data from the link.

**How can we reproduce the problem?** 

Try to load any data from Google Sheets via link.

**What's your environment?**

- Operating system: OSX
- Orange version: 3.30.2dev
- How you installed Orange: pip

**Comment by JakaKokosar** [comment]
The issue here is that since https://github.com/biolab/orange3/commit/62a7605ba4c08db89703838ec9e767cc400a7a1a we encode URLs, and google docs services don't like this.

Plain URL works fine: https://docs.google.com/spreadsheets/d/1PJhmH0X_N7hZn03le5J70E4IKL4LiqAZenlhg2kWWUU/edit#gid=0

Encoded URL cannot be found:
https://docs.google.com/spreadsheets/d/1PJhmH0X_N7hZn03le5J70E4IKL4LiqAZenlhg2kWWUU/edit%23gid%3D0

This seems to be specific to google services because Dropbox links and links to biolab servers work fine:
http://file.biolab.si/text-semantics/data/elektrotehniski-vestnik-clanki/detektiranje-utrdb-v-%C5%A1ahu-.txt

One solution is to do an additional check for 'docs.google.com' URLs and skip encoding entirely. Any other ideas?

**Comment by fabform** [comment]
This is handy to find google sheets id
[find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)

**Comment by lukasholovsky** [comment]
Hi, Lukas from AlgOps.com here.

This issue is probably not based on API because in older versions of Orange (3.27 respectively) it worked even though it didn't work in newer versions. A

@JakaKokosar also your plain URL doesn't work fine - I tried this several minutes ago and it returns the same error even though I am able to look at the Sheet in the browser.

Please can you speed up on this issue since a big portion of our customers can't use both AlgOps and Orange due to this?

Thanks!

**Comment by markotoplak** [comment]
The bug is there from merging #5412. So this bug may stem from:
- `quote` being overzealous, at least in that URL part - I do not know the exact URL specification, but quote is written as a general function which does not distinguish between parts of the URL
- dropbox and google docs have a special functions `_trim_*` functions that in docs' case adds a sheet (maybe something else) - maybe quoting prevents it

@lukasholovsky, if the functionality is important for you, consider making a PR.

**Comment by fabform** [comment]
Handy to [find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)
