### ISSUE TITLE
Paint Data: Radius stuck when on minimum value

### ISSUE THREAD

**Issue by Konrad335** [biolab/orange3#5730]
**What's wrong?**

When taking Radius value to the minimum its imposible to click on it and raise it back, I need to hold bar and wait. 

https://i.imgur.com/rt9g8WL.png

Changing skins deletes x and y axis from Scatter Plot

**How can we reproduce the problem?** 

**What's your environment?**

- Operating system:
- Orange version:
- How you installed Orange:

**Comment by ajdapretnar** [comment]
What does it mean "changing skins"?
Can confirm the radius issue, so weird.

**Comment by Konrad335** [comment]
I meant changing style to the dark mode. In default style of program I can see axises in Scatter Plot but in dark mode cant

**Comment by janezd** [comment]
- The very interesting problem with setting radius is fixed in https://github.com/biolab/orange-widget-base/pull/182 (which will close this issue).
- The problem with disappearing axes is fixed in #5680.

Thanks for reporting both. In the future, please report distinct in separate issues because they will probably be handled in different pull requests.
