### ISSUE TITLE
Control panel for adjusting parameters

### ISSUE THREAD

**Issue by kaimikael** [biolab/orange3#5739]
**What's your use case?**

(I have a vague feeling I already have raised this point, but I can’t find that issue.)

My concrete problem: I read two datasets of time series data.  I want to extract the data for the year x from both datasets.  To do this I have to create two separate Select Column widgets and make sure I set the same year column in both widgets, and if I want to look at year y, I have to edit both widgets.
I would much prefer to be able to have a single control where I set the year and then feed this to all widgets that need to know this.
(And in general of course not just years but arbitrary parameters.)

As an old OpenDX user, I miss the Control Panel where you could set variables that were connected to relevant parameters in the modules in the network.  That way one could control isosurface values, adjust axis ranges, turn alternative visualisations on and off, etc from a single interactor panel.  This allowed for an interactive visualisation to be handed to a novice user who could then explore the data from a bespoke interface.  

**What's your proposed solution?**

I understand the data model and user interface of Orange would need to be modified quite extensively for this.  At the very least it would require named connection ports.

**Are there any alternative solutions?**

Uh, maybe it could be possible to mark controls in the widgets and say: “make this input value available on a global control panel”?

**Comment by janezd** [comment]
This is a very interesting idea, particularly for synchronizing different visualization widgets.

Unfortunately I don't think it can be implemented. But for the sake of brainstorming (perhaps something can be done in this direction): your idea is that every parameter the the user can input would be somehow controllable from outside?

One problem is that these parameters may be anything - a checkbox, or a combo or listbox. The Control Panel would have to receive the information about the content of combos and checkboxes from (multiple!) widgets, and output the selection back. What happens if the content is different in different widgets, and if the selected value is not available in all?

Also from the user interface standpoint, I don't see how to present to the user which parameters are controlled manually and which from the control panel.

We would probably have to give all parameters some recongnizable names.

The more I think about it, the more problems I see. The idea itself is appealing, but maybe it just doesn't fit into Orange's mindset.

**Comment by kaimikael** [comment]
Yeah, the current data model of Orange doesn’t really support it well.  In OpenDX it worked since every parameter in a module could be accessed through a separate, typed, port, so your selection variable could only connect if there was a selection port made available in the module.

Oh, goody!  I found the relevant book online: http://mitran-lab.amath.unc.edu/courses/SoftwareTutorials/opendx/OpenDX-Paths.pdf  Page 136 shows what I’m yearning for :-)

**Comment by janezd** [comment]
Yes, I have seen software like this. They would have hundreds of widgets with dozens of inputs. Some widgets would simply output an integer that the user enter. We don't want to go in this direction.

**Comment by kaimikael** [comment]
Fair enough :-)

**Comment by janezd** [comment]
We discussed this at the meeting. These ideas are impossible to implement and also inconsistent with Orange's philosophy.

There may however be an "Orange way" to do what you need. If you select columns on one data set, you can use the Apply Domain widget to select those same columns on another data set (or, in general, apply any other transformation you've done on the first data set). I hope this helps?
