### ISSUE TITLE
Predictions is missing the "Target Class" combo for evaluation

### ISSUE THREAD

**Issue by dml5064** [biolab/orange3#5743]
**What's wrong?**
The prediction tab gives a different F1, precision, and recall score. This is compared to the same test and score model. I am using a training and test data set and marked the "test of test data". The prediction tab scores also do not match up with the confusion matrix score when calculated by hand. 

**How can we reproduce the problem?** 
Test a model using 2 data sets and compare output from "test and score" and "predictions"

**What's your environment?**
Orange 3.30.2
Windows 10

![image](https://user-images.githubusercontent.com/63750464/146688328-92e3d5f5-cb12-4d66-8745-9ed4c68ee019.png)
![image](https://user-images.githubusercontent.com/63750464/146688372-a3ce03d3-102b-4cd2-bbbb-1384fd2e2d5a.png)

**Comment by dml5064** [comment]
To clarify in the above example "Test" and "test1" are the same. If I do it separately I get the same results.

**Comment by markotoplak** [comment]
@dml5064, thanks for the report. In **Test and Score** you selected the "Target Class" to obtain scores you are seeing. If you set the "Target Class" combo to average, you would get the same scores as in **Predictions**.

**Predictions** is missing the target class selector from **Test and Score**, so evaluation can not be set the same way. This is a bug. Thanks for the report!

**Comment by dml5064** [comment]
So just to be clear? I set everything up correctly and there is an issue in the widget? Just so I know for the future. Thank you!

**Comment by markotoplak** [comment]
What you are doing is fine if you are aware that your Test and Score and Predictions are set differently:
- In the Test and Score you set the target class from the default value (which averages results) to a specific class (yes)
- In Predictions the target class can not be set explicitly, so the default averaging is used.

Because different target class settings are effectively chosen, you see different results.

The issue with the widget is that Predictions (which returns correct results) does not allow you to choose the target class.
