### ISSUE TITLE
'Normalizer' object has no attribute 'need_domain'

### ISSUE THREAD

**Issue by bluh32** [biolab/orange3#5758]
Hi,

I am testing out deploying my saved model in Python and am running into the following problem and can't quite figure out how to fix yet.  Any help would be greatly appreciated.

model = pickle.load(open("modelpkcls", "rb"))
data = Orange.data.Table("data.csv")

with the following error:
'Normalizer' object has no attribute 'need_domain'

I have been messing around changing the model and data to see where it goes wrong, but I seem to get a different 'need_domain' error with my changes so far.

**Comment by markotoplak** [comment]
May I ask when did you create the pickle? Was it the same version you are trying to use to open?

Also, which modeling technique are you using? Are you doing any preprocessing? Could you make a minimum workflow that builds a model like this which we can replicate, preferably using one of the documentation data sets?

**Comment by bluh32** [comment]
Thanks for the response Marko.

May I ask when did you create the pickle? Was it the same version you are trying to use to open?  
I am not sure I exactly understand this here.  I went ahead and uninstalled Orange App this morning and removed the Python  package.  I will reinstall and rebuild the model and save to see what happens.

So I am using a few of the modeling techniques (Random Forest, Adaboost, KNN).  And yes, I am doing preprocessing.  I will work on replicating on a documentation data set -- may take me a few days to get back.

Thanks again for the response.

**Comment by bluh32** [comment]
Got this error this morning after the reinstall "'RandomForestRegressor' object has no attribute 'min_impurity_split'"

**Comment by markotoplak** [comment]
Back to your original problem: I wanted to know if the version of Orange where you create a pickle file is the same as the one where you try to open it. I suspect they were different. Looking at the code it seems that your pickle file was created in pre-3.28.0 Orange and you were opening it in a newer version. Can you confirm this?

We usually try to take care of pickle compatibility, but sometimes we miss errors like this. I was the person who actually introduced this bug.

**Comment by markotoplak** [comment]
About the `min_impurity_split` of `RandomForestRegressor`: the same issue, but we can not do anything about this one. Normally, in Python programming, pickle files should not be treated as a stable storage, because they depend on the implementation, which can change between versions. So pickling with one version and unpickling is not guaranteed to work (but usually does so we, programmers, tend to forget about it). Sometimes it is possible to define pickling/unpickling functions manually to support pickles from different versions, but this is only done in some rare cases.

Orange internally uses scikit-learn's RF implementation, so when you save a learner, it, among other Orange properties, pickles scikit-learn's `RandomForestRegressor`. Recent scikit-learn changed RF implementation enough so that pickles are incompatible.

To solve both your problems, make sure that you use the same version of Orange and its dependencies for saving and loading models (in practice, the same versions of scikit-learn and Orange will likely suffice).

**Comment by bluh32** [comment]
Thanks so much Marko, appreciate your help here.  Yes, the version I created this model was probably from about a year ago so that is likely the issue.

I will go ahead and close this one out and come back if issues persist after reconciling the versions.  If I just delete orange from my computer and install the latest Orange Download and then pip install the package here I would be lined up correct?

I can easily recreate the model in the new version.

**Comment by markotoplak** [comment]
I am reopening because I'd like to fix the issue. The latest Orange download and pip install would have the same versions of Orange, but dependencies could differ. Try checking which version of scikit-learn was installed by doing `pip freeze` and then updating accordingly.
