### ISSUE TITLE
Edit Domain: define date format for datetime conversion

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#5779]
**What's your use case?**

Dates and timestamps come in all shapes and sizes. It would be nice if one could define the format on-the-fly, similar to the `strptime` function.

**What's your proposed solution?**

Provide a curated list of most common datetime formats to parse the time variable into ISO standard.
I.e.:
dd. mm. yyyy
dd. mm. yy
d. m. yyyy
d. m. yy
mm/dd/yy
mm/dd/yyyy
dd-mm-yy 
dd-mm-yyyy

**Are there any alternative solutions?**
Parse it implicitly, but this could lead to a variety of problems.

**Comment by ajdapretnar** [comment]
I marked it as "needs discussion", because if we are in favour of adding this, we should decide how to expose this in GUI.

**Comment by PrimozGodec** [comment]
We decided to:
- support the custom format in `TimeVariable`. The format is provided when the object is constructed and used for parsing. If it is not defined we use the current default - ISO format.
- add dropdown to select format in File widget
- add dropdown to select format in Edit Domain widget

**Comment by mw25** [comment]
I like this feature. 👍 

But were you only talking about text to datetime conversion, or numeric to datetime conversion as well?
A discussion about numeric to datetime has already been started here: #5648 
Could this issue also be addressed in the current changes?

**Comment by wvdvegte** [comment]
I think this feature would indeed be very useful!

**Comment by PrimozGodec** [comment]
> @PrimozGodec I suppose for numeric variables, we could go with the suggested:
> 
> %Y%m%d%H%M%S
> %Y%m%d
> %Y%j
> %Y
> %H%M%S.%f
> Depending on the type of the feature, we could propose different format options.

@ajdapretnar I would not convert numeric values according to those formats in Edit Domain. The reasons are:
- since numeric values remove leading zeroes, there is no nice way of parsing them. I widget I would need to include a hardcoded format checking and adding leading zeros before conversion, which is ugly, and error prune for some changes in the future
- I think it is not necessary since users will be able to interpret values according to this format in the File widget (I will implement it after I finish with the Edit Domain) 

My proposed solution is that this format is still available for String and Discrete variables (where leading zeros are kept). We convert numeric variables to time as the UNIX epoch (it is done this way currently in Edit Domain).
