### ISSUE TITLE
scatter node legend miss some terms.

### ISSUE THREAD

**Issue by leaf918** [biolab/orange3#5808]
**What's your use case?**

in my case,there is 16 target attributes,but in scatter only 11 terms are represented.
what I need is show all terms ,or setting entry for showing that .
and the term 'other ' is a little funny and stupid,in my scenioar ,I wanna the full information.

![image](https://user-images.githubusercontent.com/170311/151288565-8d36a6f3-6d3a-4c7e-a40c-12981ba69dd8.png)

**What's your proposed solution?**

give the user more options(color ,shape) for displaying the legend info,remove the term 'other'

**Are there any alternative solutions?**

no

**Comment by ajdapretnar** [comment]
Would displaying a 100 colors help? I don't think so. Hence the need for the term "other". Categorical variables over a certain number of distinct values are useless. What is the threshold? Hard to say. We went for 10, because they can still be shown with reasonably distinct colors. Above that the palette switches to one that is a mess, as you can see.
We might consider enabling turning off this threshold in Visual Settings.

For shapes, a clear answer is no. 7 is quite enough. If you need more, then what you are looking for is a different kind of visualization, which would be able to convey your message.

**Comment by leaf918** [comment]
displaying 100 colors will indeed help.

if user donot like 100 colors, thery would turn off [show all] option,but if ther are analyzing the the data,comparing each catelog with others,this is indeed helpfu.

**Comment by ajdapretnar** [comment]
I think you are missing the point. You cannot distinguish 100 colors. No human can. It is useless to have a 100 different colors available. But perhaps we need not to keep people from making their own mistakes.

**Comment by leaf918** [comment]
Let's talk about the case that showing in my previous post,
there are 16 catelogs,we need to review which catelog point are near, and talk about why ther are near together, whether we shoud retry our experiments ,whether our farvour catelog points are clustered as expected.
In the real case,we care about the catelog which are marked 'x', there are some other points near the 'x',if we ten persons are reviewing the data,we wanna know why the other points are near the 'x' point,but ,as orange beheviour now,it only show 'other', we want to see full infomation of each point.

**Comment by janezd** [comment]
> _we want to see full infomation of each point._

But you do see it. Don't you have labels? Is this not "full information"? Why does this "full information" also have to be given with colors? How would this improve your insight?!

The answer is: it wouldn't. With so few data points, you can easily get the entire picture ("full information") by simply reading labels. Having a few more shades of blue and orange that wouldn't be distinguishable from the existing shades of blue and orange wouldn't be helpful but misleading, because you could mistake two similar colors as the same color.

Orange tries to guide the user towards better visualizations. Allowing more colors than the user can distinguish would be a bad practice, which Orange tries to avoid.

**Comment by leaf918** [comment]
![image](https://user-images.githubusercontent.com/170311/151483473-495eaa01-4284-4927-9c91-61da254ee03d.png)

plz ref matplotlib legend.

**Comment by janezd** [comment]
Think again.

**Comment by borondics** [comment]
I agree and disagree in the same time. 

I also ran into the problem of this limitation in Orange, but I fully agree that putting a 100 different categories on the Legend would make no sense. How did you determine the limit here? Would it be possible to have a parameter that changes this limit? @janezd, the _"guidance towards better visualizations"_ can be also done a bit gentler and communicated via setting a default value there... 

Even with not saving the last used 243 category value set by the user but resetting it to 10.

Would it be possible to use textures on the circle markers together with colors? That would immediately double (triple... depending on the number of textures) the possible Legend items that are easily recognizable from one another.

Here is an interesting page on categorical colormaps from my favorite [Colorcet](https://colorcet.holoviz.org/user_guide/Categorical.html) folks. Maybe has some good ideas, although doesn't give a number of how many the limit should be.
