### ISSUE TITLE
File widget can't handle unreasonably long PATH

### ISSUE THREAD

**Issue by borondics** [biolab/orange3#5946]
**What's wrong?**

We can't load some files because the PATH is too long.  I know, one can make it shorter, but users don't and then they suffer. This is a general python problem I guess as I have ran into it in other places too.

**How can we reproduce the problem?** 

Make a long PATH.

**What's your environment?**

- Operating system: Windows
- Orange version: 3.29
- How you installed Orange: Quasar

**Comment by markotoplak** [comment]
What happens?

**Comment by borondics** [comment]
Orange / Python says that the file doesn't exist and gives a path with the
funny ~ characters that are used in windows.

**Comment by markotoplak** [comment]
This is a know Python/Windows limitation. See the discussion here: https://bugs.python.org/issue18199

In the liked discussion, they wrote that this was planned to be fixed in Windows 10 with NTFS. Which Windows version did you use. Feri?

The Python developers decided to do nothing about the bug. We likely won't fix it either: fixing this rare issue could easily introduce some nasty and even more common bugs.

**Comment by janezd** [comment]
@markotoplak, close?

**Comment by markotoplak** [comment]
I am closing this for now. If the problem starts being obnoxious often, then we could reconsider.
