### ISSUE TITLE
Confusion Matrix creates non-unique names in annotated data output

### ISSUE THREAD

**Issue by rickierich** [biolab/orange3#5978]
I am trying to use confustion matrix as an outlier stripper.

I have a chain setup like this File to select rows to select columns to outliers to data sampler to preprocessor to test and score with learners attached. Then to my first confusion matrix, I send data from there to the  second test and score with learners attached. The second test and score has a second confusion matrix, which breaks down 99% of the time, with the final error being that the variable names have to be unique in a domain. 

My approach is genius it does not improved scores, but the 'specific generality' it gives is what I am experimenting with.

**What's wrong?**

**How can we reproduce the problem?** 

**What's your environment?**

- Operating system:
- Orange version:
- How you installed Orange:

**Comment by ajdapretnar** [comment]
Please attach a workflow with the error and describe how you installed Orange (which version) and which OS you are using.

**Comment by janezd** [comment]
@ajdapretnar is correct: if you don't send us the workflow, we cannot know that you have also checked the "Probabilities" checkbox in Confusion Matrix, which is essential for reproducing this problem.

Well, we *cannot know* unless we can *guess* what is going on. The bug is here: https://github.com/biolab/orange3/blob/master/Orange/widgets/evaluate/owconfusionmatrix.py#L387

**Comment by rickierich** [comment]
Orange is installed through anaconda, it is the latest version which is 3.30.2 and yes the probabilities ticked is when it doesn't work.

Thanks in advanced.
