### ISSUE TITLE
There is no disk in the drive error

### ISSUE THREAD

**Issue by fcocespedes** [biolab/orange3#5979]
**What's wrong?**
After installing the adds-on, I can open orange anymore and appears the following error: 
There is no disk in the drive. Please insert a disk into drive

**What's your environment?**

- Operating system: WIndows 7 Enterprise, 64 bits, Ram 32 Gb
- Orange version: 3.3.32
- How you installed Orange: webpage
![error orange](https://user-images.githubusercontent.com/105875238/169346966-18379e24-2196-4942-bd99-a8ddd5817667.PNG)

Any idea??

**Comment by janezd** [comment]
No idea. :) This looks crazy.

Which add-on(s)?

**Comment by markotoplak** [comment]
We have never seen anything similar and can not replicate the bug on our computers. We might be able to help if you help us finding the specific add-on that makes the bug show up on your computer.

I am closing this bug because there is too few information for further debugging. But if you find the specific add-on (by repeatedly uninstalling/installing Orange and then perhaps installing add-ons one-by-one), we will reopen it. We would appreciate it! Thanks.
