### ISSUE TITLE
Recursive imputer

### ISSUE THREAD

**Issue by hydrastarmaster** [biolab/orange3#6001]
Use case: We have a model with 200 features. We apply a “Model base imputer (simple tree)” to fill in missing data.

Problem: The “Imputer” widget fills in just a part of the missing data (that's the limit of the default 1-NN regressor used).

Current workaround: We have chained 5 instances of the same imputer, that’s to say, as much as needed to “complete” the imputing procedure for our data. At each stage, more data are imputed, up until the point where the regressor cannot produce further predictions.

Proposed solution: Add a check-box in the Impute widget, to activate iteration. The process will be repeated leveraging the imputed data from the previous iteration. Loop until no more changes are produced.

**Comment by hydrastarmaster** [comment]
I confirm that iterative imputation is giving consistent values and proves by far the best option to interpolate lacking data --> in our specific case.

**Comment by janezd** [comment]
We discussed this at a core team meeting. The situation you describe shouldn't have happened: models in Orange should never output a missing value. A single iteration of imputation should have imputed all values. Could you upload a minimal example (data + workflow) that reproduces the bug?

This, on the other hand, means that the feature you wish for will not be implemented because it is quite incompatible with Orange's existing architecture.

**Comment by hydrastarmaster** [comment]
Ok, here are the files for you to check.
[Orange - Check 6001.zip](https://github.com/biolab/orange3/files/8890317/Orange.-.Check.6001.zip)
