### ISSUE TITLE
"Select Row" widget improvement

### ISSUE THREAD

**Issue by hydrastarmaster** [biolab/orange3#6031]
The "Select Row" widget needs a little improvement. It currently lacks a multiple selection filter.
Let's suppose we have a feature "Licence Plate No.", and a list of numbers to extract. The widget allows us to insert just an "Equals" filter, accepting only 1 value. If we put several "Equals", they are in AND, so nothing is extracted. Thus, there are two solutions to solve the case (both can be implemented concurrently, to better approach the case):
1) add a "is in" condition, accepting a list of values (e.g. in Python list format);
2) when several "equals" conditions are applied to the same feature, they have to be considered in OR, not in AND.

Just one more thing. There's a "remove all" button. It would be better to add independent delete buttons alongside each condition.

**Comment by janezd** [comment]
Option 2 was implemented in Orange 2 and we removed it because it introduced complexity that almost nobody used. The widget is much better without it.

Python list format is a bad option for software intended for non-programmers.

You have a specific scenario, but you are more than welcome to propose a generally useful solution. I would, however, recommend that you first write just a prototype for the code, and write the final version (including the unit tests and so forth) only after we discuss  whether this is indeed a feature we'd want to have - and have it in this form.

Regarding one more thing: there are independent delete buttons on the right side of each row.

**Comment by hydrastarmaster** [comment]
Thanks for the info. I'll think about a different general solution for the filter.
I've found the single delete button thanks to your note; I didn't see it because it's "invisible", all grey without border or graphics.

**Comment by markotoplak** [comment]
@hydrastarmaster, could you perhaps make a screenshot of this widget so that we can see how the delete buttons look on your computer? Thanks!

**Comment by hydrastarmaster** [comment]
Sure. As you can see, there are just a couple of pixels coming out on the left ... maybe the border of red Xs?

![image](https://user-images.githubusercontent.com/41840980/174565449-644aca61-d2f6-46cd-a168-7cff4ca9b49b.png)

**Comment by hydrastarmaster** [comment]
Note about the filter:
I noticed the "CSV File Import" marked the "Licence Plate No." feature as Text instead of Class (I know, there are too many values in the column to be automatically recognized as a class). Forcing it as a Class, the filter allows to use the "is in" condition with multiple selections, that was the point of my request. I was expecting the filters to be the same for both classes and texts. Initially, I didn't mark the plate number as a Class because in this file there is just 1 row for each plate, so it's not really a class.

**Comment by OumaimaZer** [comment]
> 1. add a "is in" condition, accepting a list of values (e.g. in Python list format);

There is no "is in" for some attributes, for example I have a variable called "Country", and the only conditions I have that can be applied to it are "equals" and "contains". However, both of them are not satisfying the result I am expecting.
