### ISSUE TITLE
Manifold Learning progress indicator

### ISSUE THREAD

**Issue by hydrastarmaster** [biolab/orange3#6032]
The "Manifold Learning" widget should be provided with a progress indicator animation like the other widgets. It frequently takes some time to run, and it is pretty annoying not to know how far the process has gone.

**Comment by janezd** [comment]
We generally add progress bars to widgets. Widgets that don't have it, usually lack them for a reason -- typically because it is difficult to add them; sometimes because they use a 3rd party library that doesn't provide the necessary callbacks, sometimes because it is impossible to assess the time left, and there may be many other reasons as well.
