### ISSUE TITLE
Remove MDS widget

### ISSUE THREAD

**Issue by hydrastarmaster** [biolab/orange3#6034]
Please consider the opportunity to remove the "MDS" widget, because it seems to be redundant. The same task can be achieved with the existing "Manifold Leading" widget in MDS mode + a "Scatter Plot".
In that case, please note the "Jitter" Optimization/Initialization is currently missing in the Manifold options.

**Comment by janezd** [comment]
We designed it the way it is designed for a reason. MDS' plot includes things (for instance, visualization of similar pairs, of stress...) that scatter plot does not. MDS has a recognizable name: we wouldn't want to bury it in the list of Manifold learning methods. MDS is animated (with some problems due to threading, which needs to be smoothed out). And so forth.

**Comment by hydrastarmaster** [comment]
Thanks for clarifying.
