### ISSUE TITLE
SQL request replies Data is to big/ How big ist the data max?

### ISSUE THREAD

**Issue by Bubbu17** [biolab/orange3#6046]
I Request a table from mssql data server and orange is telling me data ist to big. I am working mit real-live data, and of course the are large. so it is a bit sad, that this useful tool can not handle this! Please make it possible the long term.

![image](https://user-images.githubusercontent.com/62136070/175502738-c32a5046-ff16-41dc-9a96-8ff9a4a670f7.png)

**Comment by lanzagar** [comment]
The current limit is set to 1,000,000 rows.
I agree that this could be larger, especially when the number of columns is low and the computer has a lot of memory.
Ideas for future improvements are:
- make the message more explicit (mention the actual limit)
- change the condition to check the whole table size (=rows * columns) instead of just number of rows
- I am not sure if we want to have a variable limit depending on the amount of RAM

Even if we allow loading more than a million rows, the first steps will usually involve some filtering/sampling to visualize and interactively work with the data or use slower ML algorithms.
Note that you can already use the Custom SQL option to load a filtered/sampled subset of a table (this does require knowledge of basic sql syntax however).

**Comment by Mikhaylov-yv** [comment]
I would like to take on this issue.
I can make the message more explicit (specify the actual limit)

Other issues are worth discussing.

We know that boolean data will take up a lot less RAM than double data.
I don't know much about it yet. But maybe try using swap to save big data?

**Comment by Mikhaylov-yv** [comment]
I checked this issue. So far only on postgres.

It allows you to load large tables, but at the same time unexpectedly makes them smaller.

When displaying a message:

```
Data appears to be big. Do you really want to download it to local memory?
```
And pressing `yes`. We get a reduced table, which does not look logical.

I could fix it. And try to work with MySQL

**Comment by lanzagar** [comment]
Thanks @Mikhaylov-yv for making the message more informative.

As for the optimizations of data storage - Orange currently works on float data, so saving space by using booleans/float32 would require a lot of changes. Swap is also out of scope here, but people are actively working on supporting dask and on-disk data.

The main problem with allowing loading of big data is that many _interactive_ components of Orange stop being interactive and one has to be very aware of computational complexity of different algorithms - if something has quadratic (or greater) complexity you should not use it on data that just barely fits into memory.

**Comment by lanzagar** [comment]
> I could fix it.

I am not sure what you were referring to in the last comment, but if you notice any other problems or bugs it's best to open a new issue.
