### ISSUE TITLE
Deploying a Machine Learning Model

### ISSUE THREAD

**Issue by Yibbou** [biolab/orange3#6137]
Hi All,
I suggest, if it is possible, the creation of an adds-on that will help to deploy and generate web apps, desktop apps (exe, dmg etc.) and mobile apps for orange users Machine Learning models or projects.
Thank you

**Comment by janezd** [comment]
Orange is an interactive tool for data exploration. If you want to deploy a model, you need to export it to pickle file (using Save Model), but then you're on your own. Also because this depends on the context: if you are, for instance, preparing an app for physician, you would have a specific input form and some specifically designed screen with result.

**Comment by ajdapretnar** [comment]
My answer would be a little different: Orange is open source, so anyone is free to create their own add-ons that can be integrated into Orange. If you have an idea for one, follow instructions in https://github.com/biolab/orange3-example-addon to create it.
