### ISSUE TITLE
"Statistics" output of Feature statistics is inconsistent

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3#6151]
**What's wrong?**
For categorical variables, Feature Statistics determines the Mode as the central tendency and puts it in the Median column. That's OK with me, although it could be described a bit better in the help popup. A separate Mode column would even be better.
But if I want to put the feature statistics in a table (or save them in a file) the categories in the Median column are converted to integers. This is inconsistent, and unclear because the mapping from a category to the corresponding number isn't obvious. 

**How can we reproduce the problem?** 
See attached zip file and screenshot

**What's your environment?**
- Operating system: Mac OS 12.6 on Silicon
- Orange version: 3.32.0
- How you installed Orange: from DMG
[Feature statistics inconsistent output.ows.zip](https://github.com/biolab/orange3/files/9674384/Feature.statistics.inconsistent.output.ows.zip)
<img width="634" alt="Screen Shot 2022-09-29 at 13 54 27" src="https://user-images.githubusercontent.com/55989717/193026461-88b5fac2-c18f-4a67-87a9-7d8d95e5946e.png">

**Comment by janezd** [comment]
The name of the column shown in the widget should be renamed to something like Median/Majority.

The problem with the output is the type of the column because it mixes values from different variables. When showing it in a widget, we can print out anything. But in a table, each column must have a certain type. To be of any use for numeric variables, it must be a number. But even if all variables are categorical, the column cannot be a categorical variable because each of original variables can have different categories. Hence, it must be a textual column and therefore a meta variable.

I think the summary of our today's discussion is:
- The output will have a column Median, but the value for categorical variables will be undefined (`?`).
- We also add a column Majority (only if there are any categorical variables?) with majority values as texts.
- I believe that it could be useful to have a categorical variable with majority, but only when all categorical variables have the same categories (typically: yes or no, like Zoo without variable legs). This could be in parallel with, or instead of, the Majority in metas. Yet I wasn't able to convince others, so this bullet serves as a note to myself so that I don't forget we also had this discussion. :)

**Comment by wvdvegte** [comment]
Majority can also be useful for numerical variables, especially if the number of different values is limited. In particular this can be the case when the values are integers (e.g., Likert scale). No problem if the values would be converted to text - for further processing there's always Edit Domain.
