### ISSUE TITLE
Change Refresh in MDS widget to Delay

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3#6228]
**What's your use case?**

We used the Refresh option with MDS for educational purposes to show that MDS performs optimization and is an embedding method. The points moved in every step of optimization, and one could see the convergence to the final solution. Not that this is too enlightening or required, but it was just an extra feature that could help when introducing MDS.

![image](https://user-images.githubusercontent.com/726604/204546466-427d4c89-50d8-425c-bd43-ec1fd25caa30.png)

Since computers got faster, and for small data sets such as the zoo dataset, setting the refresh even to Every does not help. The optimization converges instantly, and the movement of points can not be tracked.

**What's your proposed solution?**

Replace the Refresh with Delay, with options 0.1s, 0.2s, 0.5s, 1s, which defines that max delay between two successive iterations.

**Are there any alternative solutions?**

Remove the refresh option altogether.

**Comment by janezd** [comment]
Note that even Iris still requires ~100 iterations (when starting from random positions) so delays would have to be much smaller. So instead of what you suggested, #6234 lets the user set the number of steps and widget ensures that at least 1/10 of a second passes between each refresh. Effect is the same, but it's easier to control (I think) and the implementation is a bit simpler.
