### ISSUE TITLE
Distances widget needs improvements in documentation and interface

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3#6243]
**What's your use case?**

When using the Distances widget to compute the correlation between features (columns), the computation returns values inconsistent with the documentation. For instance, the documentation says that for the spearman correlation, the value of the Spearman correlation is scaled to the interval of [0, 1]. It does not say that Orange also substracts the resulting value from 1. If $r$ is the correlation coefficient, Distances returns the matrix where every entry corresponds to $1-(r+1)/2$.

**What's your proposed solution?**

For the user, it may not be clear what is on the output of this widget if we use correlation to estimate distances. We can solve this by:
1. Correcting the documentation (the easiest)
2. Changing the widget settings so Orange can output either the (a) raw scores or (b) scores transformed to distances. (we need to correct the documentation in this case as well)

I would vote for 2, as this is the only widget from which we can get the correlation matrix and then visualize it by, say, Distance Matrix, MDS, or Hierarchical Clustering.

**Comment by janezd** [comment]
Maybe something like this?

<img width="360" alt="Screenshot 2022-12-23 at 21 59 01" src="https://user-images.githubusercontent.com/2387315/209405024-a87748f1-7695-4ab2-afb3-47b672c0f005.png">

<img width="360" alt="Screenshot 2022-12-23 at 22 00 38" src="https://user-images.githubusercontent.com/2387315/209405144-b720869c-16d6-401e-8cb5-a0a8d9a045d3.png">

- I removed checkbox Normalized because it is enabled for only two metrics; listing them explicitly does not consume more space
- I removed Bhatasomething distance, which (almost) nobody ever used :),
- Pearson and Spearman correlation should always be absolute, imho.
- I replaced combo with radio buttons because
    - we can afford the space,
    - it makes the widget easier to navigate,
    - is friendlier to tooltips,
    -  and plays well with the next point.
- Switching to similarities disables options that are not (naturally) similarities.
- Also, some types of data may not be applicable to some metrics, which could also result in disabled radio buttons (besides being indicated as an information - currently it allows selecting an option and then reports an error).

Please comment (in particular @BlazZupan).

**Comment by markotoplak** [comment]
Interesting, I did not anticipate these problems. I agree: it would be best if we limit DistMatrix to actual distance matrices. Also, I agree that these Correlations do not belong in Distances.

An alternative solution to yours could be to make a class `Matrix` or `SimilarityMatrix`, that could then be displayed in Distance Matrix or Distance Map, but not used for computation. And Correlations could output it.

**Comment by janezd** [comment]
I liked your alternative until I I realized that it could be abused for distance laundering. Distance Matrix has an output signal.

**Comment by markotoplak** [comment]
"distance laundering" :D
