### ISSUE TITLE
Regression / Curve Fit: provide less cryptic warning when no target variable has been defined

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3#6371]
**What's your use case?**
Linear Regression and Curve Fit produce a warning "ValueError: Numeric class variable expected" when no target variable has been defined. This is a cryptic and rather contradictory sounding message: what is a numeric class variable? Sounds like a numeric variable that is categorical at the same time. Doesn't seem to make sense.

**What's your proposed solution?**
Provide a clearer message, for instance "No target defined"

**Are there any alternative solutions?**
N/A

**Comment by janezd** [comment]
A sin from almost three decades ago when we named the target a "class" - because we dealt almost exclusively with classifications. This misnomer is still used internally, but error messages should be clear.

I'd just remove "class": `Numeric target variable expected` because this same message appears when the target exists, but it's categorical.
