### ISSUE TITLE
Violin plot graph export after new widget-base

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#6391]
After biolab/orange-widget-base/pull/208 was merged Violin plot graph export does not work.

The problem should be looked at.

Also, we should add a widget test that executes graph saving for all widgets which allow that. Just to see if anything crashes...

**Comment by janezd** [comment]
Does https://github.com/biolab/orange-widget-base/pull/241 fix it?

As for tests: saving relies on having the graph shown. ViolinPlot is saved via a different path, but another path it could use would be this, which, I believe, would avoid the bug because `QApplication` on CI probably doesn't have a primary screen, or its devicePixelRatio is ... whatever.

```
            views = object.views()
            if not views:
                # It is unusual for scene not to be viewed - except in tests
                # We still try to get ratio for (any) screen, otherwise
                # assume 1 (the only consequence is lower resolution)
                try:
                    ratio = QApplication.primaryScreen().devicePixelRatio()
                except:  # pylint: disable=broad-except
                    ratio = 1
```

We can add tests, but they'll probably use weird paths and ratios, or just fail because of missing views.
