### ISSUE TITLE
SOM: image is not displayed in report

### ISSUE THREAD

**Issue by anjamejac** [biolab/orange3#6392]
**What's wrong?**
When I want to create and display a report in the SOM widget, the image is not displayed (only the description of the image is displayed).

**How can we reproduce the problem?** 
Connect File and SOM widgets. Open SOM widget and click on create and display report.

**Comment by janezd** [comment]
I think I knew that and wanted to fix it by changing `graph_name = "view"` to `graph_name = "scene"`. But this fix had to wait for https://github.com/biolab/orange-widget-base/pull/208.

Now that https://github.com/biolab/orange-widget-base/pull/208 is finally merged, we can report the scene, but see also a new issue, https://github.com/biolab/orange-widget-base/issues/240.

**Comment by janezd** [comment]
@VesnaT, in 2016 you added

```python
        elif isinstance(plot, GraphicsView):
            self.report_html += get_html_img(plot)
```

to `report_plot`. Please take a look into your pensieve: was this intentional or did you actually mean `QGraphicsView`? This would also fix the issue reported by @anjamejac (and, like reporting scenes, views also have dpis that are too large).

Same question for @janezd, who in 2015 added 

```python
        elif isinstance(plot, GraphicsWidget):
            self.report_html += get_html_img(plot.scene())
```

but could also use `QGraphicsWidget`.

I suppose we only had pyqtgraph's graphs in mind.

**Comment by VesnaT** [comment]
My pensieve only works until 2017, so I'd have to guess.

My guess is this was intentional since the import of the GraphicsView is placed just couple of line above.
However, the pg.GraphicsView extends QGraphicsView so it should work either way.

**Comment by janezd** [comment]
@anjamejac, it's great that you test reports, too. Perhaps it would be useful if you check out the latest version of orange-widget-base, which improves saving figures (into reports, files and on clipboard) but may introduce (well, has introduced) some bugs as well. Like Violin Plot (#6391).

**Comment by janezd** [comment]
> However, the pg.GraphicsView extends QGraphicsView so it should work either way.

There'd be a problem if `get_html_img` expected `GraphicsView` because of some methods is adds to `QGraphicsView`. It doesn't (I think).

This code is a mess - functions accept all kinds of arguments (views, scenes, plot items) and pass them to each other, so nobody knows who can handle what. I believe that three out of four cases could be merged into one (that is, pass either `plot` or `plotItem`) and the code would still work. I don't dare to try, though.

Perhaps we'd need to rewrite and type-annotate it.
