### ISSUE TITLE
Installing add-on after uninstalling it doesn't work: can't get uninstalled add-on back

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3#6416]
**What's wrong?**
In connection to #6410 I tried to check if that problem could be resolved after uninstalling the Text add-on (1.12.2) and then reinstalling it. Problem is that after restarting Orange, the add-on won't return, even though the Add-on menu reports it as installed.

**How can we reproduce the problem?** 
Probably by uninstalling the Text add-on using the Add-ons menu, restarting Orange, reinstall using Add-ons, restart Orange.

In the meantime, I would welcome an instruction how to manually install the previous version of the Text add-on

**What's your environment?**

- Operating system: Mac OS 13.3.1 on Silicon
- Orange version:
- How you installed Orange: 3.34.1

**Comment by wvdvegte** [comment]
This turned out to work: I uninstalled Orange as a whole and all plugins, then reinstalled everything and now I have Text Mining back.

**Comment by PrimozGodec** [comment]
@wvdvegte, thank you for reporting. We spotted the error. It turned out that Gensim (one of the Text's dependencies) made a mistake in building the package with too new Numpy in version 4.3.1. We temporarily fixed it by omitting the problematic version https://github.com/biolab/orange3-text/pull/967. I also proposed the PR that will fix the problem in their repository's next version of Gensim.
