### ISSUE TITLE
Select Rows by "does not contain"

### ISSUE THREAD

**Issue by cevznriny** [biolab/orange3#6422]
**What's your use case?**

Selecting rows that do not contain a string.

**What's your proposed solution?**

Add "does not contain" to the list of conditions.

**Are there any alternative solutions?**

No.

**Comment by wvdvegte** [comment]
Do you expect the string that you want to check for to be always in the same column? In that case there is a simple alternative solution: use Feature Generator to create a categorical variable called Unselect:

Unselect := 'Y' if 'xxx' in str(Name) else 'N' 

with 'xxx' your string and Name the name of the column where to look for it.

Then put a Select Rows after Feature Constructor with condition

Unselect | is not | Y

**Comment by cevznriny** [comment]
Thanks. That works. It might be a bit tricky to work out for a non-coder.

I added a "Does Not Contain" to Select Rows in my fork. It works but I don't know if I've found everything.
Could you see if it is worth submitting for a pull request.
https://github.com/cevznriny/orange3/commit/023f668de70962fd26ee65fc09daf873d1b77619

**Comment by wvdvegte** [comment]
I'm not a coder either, but I do know some basic Python. Everything you can pull together in one line in an "=" assignment (shown as ":=" in Orange) can be used in Feature Constructor - especially "... if ... else ..." is very useful. In fact, these are pieces of Python code that you can ask ChatGPT to write for you ("produce one-line Python code that does the following:").
Since I'm not a coder, I have no idea how pull requests on GitHub work.
