### ISSUE TITLE
Forward selection in feature suggestion

### ISSUE THREAD

**Issue by processo** [biolab/orange3#6480]
I really like the feature suggestion in _Linear projection_ and _Radviz_ but finding a combination of as little as 4 features among 100+ attributes takes forever. I tried to use _Rank_ to reduce their number but often cannot go so low that it would be worth the wait (also independently measuring feature importance does not give the same result as in combination).

My idea is that a forward selection strategy would be a good alternative to brute-forcing all combinations. It can easily find a combination of 10-20 features much faster.

**Comment by janezd** [comment]
You're right: enumerating even 4 variables out of 100 takes lots of time. But these widgets already use some heuristics in ordering the combinations: variables with higher Relief scores (we use this measure because it takes interactions into account) are prioritized. You thus do not need to wait till the end because you'll get the good combinations sooner.

With forward selection, you mean just the very basic one, that is, adding one variable at a time, without removing them? This does not belong to the same window for feature suggestion (because it has a list and here we'd only have a single combination), but rather to a button in the widget itself.

Furthermore, we discussed that we could do this interactively, like having a button that would add on single variable to the currently selected variables. The user could then manually run forward selection, and also curate the selection (e.g. try removing variables).

We discussed this at today's meeting. While nobody objected, nobody was eager to implement this. If you want to do it: please go ahead, but let's keep in touch to make sure that your implementation is compatible with the current code and ideas.  I also added it to #4090, where we keep ideas that shouldn't be forgotten, but nobody is ready to implement them at the moment.
