### ISSUE TITLE
EditDomain: Unlink variable from its source variable

### ISSUE THREAD

**Issue by JakaKokosar** [biolab/orange3#6566]
**What's wrong?**
In the edit domain, the "Unlink variable from its source" checkbox is always disabled (or so it seems).

![Screenshot 2023-09-06 at 11 40 29](https://github.com/biolab/orange3/assets/15876321/e75c1086-fcad-4433-82f8-880351893abe)

This creates a problem later when we want to apply transformations. I think this workflow is enough to illustrate what the problem is:

![Screenshot 2023-09-06 at 11 50 36](https://github.com/biolab/orange3/assets/15876321/eba94a70-4b91-4922-b1e0-806c93f3e73c)

Essentially, Orange sees 'Time' as two different variables because we performed transformations in the edit domain. However, in this case, one would like to treat those two variables as if they are the same.

What needs discussion:
- Is this checkbox disabled for a reason or is this a bug?
- Should we make this option checked by default (for those who know whats up, they will disable it)?
- What about apply domain? Should we support something similar there?

**How can we reproduce the problem?** 
File -> Edit Domain -> try to click on "Unlink variable from its source"

**Comment by janezd** [comment]
First a clarification: one domain has an attribute A of type string, and edit domain converts it to numeric. In the other domain, A is already numeric and hence doesn't match the attribute coming from Apply domain (because it doesn't have compute value).

The widget works as intended. Input variables have different properties, like name, type, attributes, compute value... Edit Domain can change them, that is, rename, change type, change attributes, remove compute value. The function of this checkbox is -- like the function of all other options -- to change the existing properties, that is, to *remove the existing compute value*.

The widget always outputs a variable with compute value. Otherwise, transformations couldn't be applied on other data.

We could add another checkbox that would remove compute value from the output variable. How to describe it? @JakaKokosar suggested that the existing checkbox is about *inheriting* the connection with an older variable, while the new compute value (that currently can't be removed) is about *creating* the connection between the modified and the existing variable.

Interestingly, this problem can be solved by adding another Edit Domain, which can remove compute value from the variable created in the current Edit Domain.

**Comment by janezd** [comment]
I looked into that. But.

- Edit Domain constructs a new domain (with compute_values for all variables with any transformations.)
- It uses this domain to transform the data.
- Then it constructs another domain in which those variables that have the "unlink" checkbox checked are copied with `compute_value=None`.
- It replaces the domain (i.e. uses `Table.from_numpy` with that domain and the transformed arrays from the previous step). (This is skipped if the previous step doesn't unlink any variables.)

The checkbox is disabled for variables that don't have prior compute value. So the above steps only remove the existing compute value.

If we add a check box that would remove the new compute value, the above steps would be exactly the same! The distinction is only in *which* compute value is removed - the old one or the new one. We would have two checkboxes whose function is difficult to explain to the user, but they would do the exact same thing -- remove the compute value if *any of them* is checked.

As a further point, the code that checks whether the unlinking is required already looks like this:

```
    return trs is not None \
           and any(isinstance(tr, Unlink) for tr in trs) \
           and (var.compute_value is not None or len(trs) > 1)
```

To my understanding, the current UI doesn't even allow `any(isinstance(tr, Unlink) for tr in trs)` unless `var.compute_value is not None`. :)
