### ISSUE TITLE
Orange3-3.35.0-Python3.9.12.dmg install issue on Mac Os M2

### ISSUE THREAD

**Issue by Finisher2021** [biolab/orange3#6567]
**What's wrong?**

Hi, after installing Orange Data Mining -Orange3-3.35.0-Python3.9.12.dmg-, the app correctly lauch while clicking open
but the window crashes after a few seconds and the app doesn't work ;-). Even after restarting my computer.
Ideas ?

Thanks

**How can we reproduce the problem?** 

**What's your environment?**

- Operating system: Mac OS Ventura 13.5.1
- Orange version: Orange3-3.35.0-Python3.9.12.dmg
- How you installed Orange: With the file directly provided by Orange Data Mining site, latest version

**Comment by markotoplak** [comment]
Thanks! We've seen something similar last week. About two weeks we changed the Mac installer to build with newer APIs, so that could produce this issue. @JakaKokosar was debugging that issue so he might know better if these are related.

Did you get any error messages? I suspect not. But there is a way to start Orange that allows you to see errors in such cases. @PrimozGodec, could you help with a command for Mac? Thanks!

Do you have Rosetta installed? Did Orange DMG perhaps prompt you to install Rosetta?

Here you can download the older installer version (the same version of Orange), which could theoretically work better. Could you try it and report if it work for you? If it indeed works then we know that we introduced new bugs with the updated installer. https://download.biolab.si/download/files/Orange3-3.35.0-Python3.9.12-10.9.dmg

**Comment by Finisher2021** [comment]
Yes thanks !
Orange works after install with your version to download. Without any Rosetta prompt. Many thanks


De : Marko Toplak ***@***.***>
Date : vendredi, 8 septembre 2023 à 11:06
À : biolab/orange3 ***@***.***>
Cc : Finisher2021 ***@***.***>, Author ***@***.***>
Objet : Re: [biolab/orange3] Orange3-3.35.0-Python3.9.12.dmg install issue on Mac Os M2 (Issue #6567)

Thanks! We've seen something similar last week. About two weeks we changed the Mac installer to build with newer APIs, so that could produce this issue. @JakaKokosar<https://github.com/JakaKokosar> was debugging that issue so he might know better if these are related.

Did you get any error messages? I suspect not. But there is a way to start Orange that allows you to see errors in such cases. @PrimozGodec<https://github.com/PrimozGodec>, could you help with a command for Mac? Thanks!

Do you have Rosetta installed? Did Orange DMG perhaps prompt you to install Rosetta?

Here you can download the older installer version (the same version of Orange), which could theoretically work better. Could you try it and report if it work for you? If it indeed works then we know that we introduced new bugs with the updated installer. https://download.biolab.si/download/files/Orange3-3.35.0-Python3.9.12-10.9.dmg

**Comment by shaunie-t** [comment]
Hi, I'm getting the same issue with the latest version. It seems to be installing correctly, but the app won't launch from my (Mac) desktop. That link to the older installer version produced a 404 for me. Is there somewhere I can go to install a stable version?

**Comment by PrimozGodec** [comment]
@shaunie-t Yesterday, we rolled back to the old installer but forgot to refresh caches, so you probably got a new version of the installer. 
I re-added the old installer to https://download.biolab.si/download/files/Orange3-3.35.0-Python3.9.12-10.9.dmg and soon it will be available as the default installer on the website.

**Comment by shaunie-t** [comment]
@PrimozGodec Thank you so much! It seems to install fine now. You guys are the greatest!

**Comment by PrimozGodec** [comment]
We have published separate Apple Silicon and Intel bundles on the [website](https://orangedatamining.com/download/#macos), so it shouldn't be a problem anymore since ARM users now have a native ARM bundle (Rosetta is not required anymore). @markotoplak, I suggest closing this issue.

**Comment by markotoplak** [comment]
Thanks to all involved, especially to @ales-erjavec and @PrimozGodec.
