### ISSUE TITLE
Impute no longer works with missing values in meta variables (or in general, some things only work with features and targets)

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3#6592]
**What's wrong?**
In previous versions of Orange, it was possible to specify individual attribute settings in Impute for meta variables with missing values. In the current version (3.36.1 and possibly also 3.36) it is possible only for features and targets.

The problem may not be specific for Impute. I vaguely remember having seen other widgets where settings for meta variables cannot be modified.

**How can we reproduce the problem?** 
See attached OWS file. The meta variable does not appear in the Individual Attribute Settings window.

**What's your environment?**
- Operating system: Mac OS 14.0 on Silicon
- Orange version: 3.36.1
- How you installed Orange: 3.35 as DMG, then updates through Add-ons menu
[Impute bug.ows.zip](https://github.com/biolab/orange3/files/12801688/Impute.bug.ows.zip)

**Comment by BlazZupan** [comment]
The behavior you are describing is by design. It is not a bug.

Modeling widgets, including impute, work only with input variables. Imputing target variables would fall under prediction. Meta features are not touched since they only provide extra information on the data instances and are not used for modeling.

There is, of course, a way to circumvent these intentional design constraints. You can use Select Column, change the role of the features (e.g., move metas to features), impute, and then use another Select Column to move the selected features back to metas. If you do this for a target feature, be careful about overfitting.

**Comment by wvdvegte** [comment]
@BlazZupan, Thank you for the explanation.It is, however, not consistent with the actual behaviour of the Impute widget, since it _does_ allow imputing not only features but also target variables. Only meta variables cannot be selected and I seem to remember that it used to be possible.

My use case is not to do "prediction" by using Impute to generate new values where they are missing. I was applying a clustering algorithm where some of the records could not be assigned to a cluster. As a result, the meta variable Cluster does not only have fields with C1, C2 etc. but also empty fields ("?" in a data table). To allow selecting unclustered records with Select Rows, I wanted to apply _Individual Attribute Settings -> As a distinct value_ in Impute, which results in the category "N/A" which allows me to select the rows in question.
I was aware of your suggested workaround, which I actually applied, but I think it's unnecessarily cumbersome.

Another solution for my use case would be to allow specifying a category name for missing categorical values such as "N/A" or "unknown" in Edit Domain.
