### ISSUE TITLE
OSX cannot load the pgsql.    "plugin" to get teh data from the tables

### ISSUE THREAD

**Issue by we-sell-bags** [biolab/orange3#6647]
downloaded orange 3 from the website for  osx 12.7.1 intel

Orange3-3.36.1-Python3.9.12.dmg

it works

**What's wrong?**

the  postgres driver will not load:

dropped this file into the plugins

psycopg2-2.7.4-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl

got this:
Command failed: python python -m pip install --upgrade --upgrade-strategy=only-if-needed /Users/bob/Downloads/psycopg2-2.7.4-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl exited with non zero status.

additional:

ERROR: psycopg2-2.7.4-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl is not a supported wheel on this platform.

**Comment by we-sell-bags** [comment]
even if i drop to teh cmb line and do this:
 /Applications/Orange3.app/Contents/MacOS/PythonApp -m pip install psycopg2-binary

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.9-cp39-cp39-macosx_10_9_x86_64.whl.metadata (4.4 kB)
Downloading psycopg2_binary-2.9.9-cp39-cp39-macosx_10_9_x86_64.whl (2.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 10.7 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.9

the program will not use it or recognize it.

**Comment by PrimozGodec** [comment]
I tried both on my ARM Mac (using Rosetta2) and my old Mac (Intel) and cannot reproduce the problem. The right approach is the one with psycopg-binary (your second attempt) since psycopg doesn't provide the right wheels for MacOS, but I don't understand exactly why it is not working after installation. I can think of two possible problems:
- Have you restarted Orange after installing psycopg-binary?
- Do you maybe have two Orange3 apps installed in your /Applications directory and that you are installing the package in the wrong Orange application? 

**If you still have a problem, maybe you can install psycopg-binary from the addon dialogue in Orange (Options>Add-ons) from the top menu. Then you click the Add more button, type `psycopg-binary` in the field, and it will be added to the list of addons (scroll to the bottom). Make sure it is checked and click OK. After it is installed, restart Orange.**

Your first attempt doesn't go through since wheels are for Python 3.6, and Orange uses Python 3.9 in the Application.
