### ISSUE TITLE
Edit domain forgets settings for categorical variables when values change in any way

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#6660]
**What's wrong?**
Edit domain is very picky about values. As soon as a set of values changes, it forgets all settings connected with that variable. The widget even forgets about 

This seems to be the issue of #6659. In #6415 we fixed widget so that it uses schema-only hints instead of contexts, so I was surprised by #6659. Indeed our handling if categorical variable is very strict.

**How can we reproduce the problem?** 
1. Take a data set with a categorical variable. Edit its name in Edit domain. Save the workflow.
2. Add a value into the data set. Reload workflow. Notice that rename is lost. 
3. Remove the added value. Reload workflow. Notice that it is renamed again.

This behavior does make sense, because stored hints look like this after playing:
```
{('Categorical', ('iris', ('Iris-setosa', 'Iris-versicolor', 'Iris-virginica'), ())): [('Rename', ('blabla',))],
 ('Categorical', ('iris', ('Iris-setosa', 'Iris-setosa1', 'Iris-versicolor', 'Iris-virginica'), ())): [('CategoriesMapping', ([('Iris-setosa', 'Iris-setosa'), ('Iris-setosa1', 'Iris-setosa-ki-jo-pobrisem'), ('Iris-versicolor', 'Iris-versicolor'), ('Iris-virginica', 'Iris-virginica2')],))]}
```

Each categorical variable is matched with name and all values. Is this too strict? Should we leave it like this or can we do anything else? This smells of contexts. :)

**Comment by janezd** [comment]
I would say that any applicable hint should be reused. Adding values should be acceptable. Perhaps even renaming values that no longer exist - it's just a hint after all, so if a renamed value is removed, it won't be renamed and that's it.

To me it doesn't smell of contexts. :) There, the problem was that different contexts matched, and we couldn't define a rule that would work in all cases. Here, it's just about the strictness of matching or, actually, about treating hints as loosely as possible.

**Comment by markotoplak** [comment]
So I guess we can say then: apply as many transformations as possible if type and name match (remove values in var descriptions).
