### ISSUE TITLE
Missing api-ms-win-core-path-|1-1-0.dll

### ISSUE THREAD

**Issue by zhulaojianke** [biolab/orange3#6676]
**What's wrong?**

![image](https://github.com/biolab/orange3/assets/16543111/24fa468d-5249-4a30-a624-91619b340762)

**How can we reproduce the problem?** 

When run the Orange, it pop out this error message.

**What's your environment?**

- Operating system: Win7 Ultimate Sp1
- Orange version: 3.36.1
- How you installed Orange: Using Orange3-3.36.1-Miniconda-x86_64.exe

**Comment by processo** [comment]
It can be because Orange 3.36.1 comes with Python `3.9.12` which is not compatible with Windows 7 (Python `3.8.6` was the last supported). You might be able to get it run with a [hacked version of the DLL](https://github.com/nalexandru/api-ms-win-core-path-HACK) based on [this discussion](https://forum.freecad.org/viewtopic.php?t=70782).
