### ISSUE TITLE
TypeError: unable to convert a Python 'Shape' object to a C++ 'Shape' instance

### ISSUE THREAD

**Issue by foongminwong** [biolab/orange3#6694]
**What's wrong?**

I first imported a proprietary Python module and received an error after I dragged a new widget to the canvas. The error is `TypeError: unable to convert a Python 'Shape' object to a C++ 'Shape' instance`
![image](https://github.com/biolab/orange3/assets/23441795/e20c455f-9f5a-4d7a-8f28-078de973010e). I can use the Python module in Jupyter Notebook without any issues.

**How can we reproduce the problem?** 

I cannot share the .ows file and would like to ask what are the potential reasons that might cause this issue.

**What's your environment?**

- Operating system: Windows 10
- Orange version: 3.36.2
- How you installed Orange: `pip install Orange3`

**Comment by janezd** [comment]
I fear we can't be of any assistance unless we see more. Can you construct a minimal example -- a minimal script that causes this bug -- and share it with us?

**Comment by foongminwong** [comment]
> I fear we can't be of any assistance unless we see more. Can you construct a minimal example -- a minimal script that causes this bug -- and share it with us?

Appreciate your reply! I will look into this error internally again and get back to your team for any further questions later

**Comment by foongminwong** [comment]
@janezd FYI, we just found out that we import `PySide2` somewhere in our codes, which causes the error. Replacing `PySide2` to `AnyQt` resolves the issue. One question, when we create a custom widget in Orange, should we stick with `AnyQt` instead of `PySide`?

**Comment by janezd** [comment]
You should always use AnyQt.

The right person to answer this would be @ales-erjavec, but in a nutshell: Orange uses AnyQt so even if you know that you will install Orange with PySide, you should use AnyQt so that any changes done by AnyQt (which only Ales may know) will work correctly.

Another argument for AnyQt is that it may help resolving some (though unfortunately not all) potential incompatibilities in future versions of Qt or PySide/PyQt.
