### ISSUE TITLE
Unable to run when there is a logging.py in the directory Orange is launched in

### ISSUE THREAD

**Issue by zactionn** [biolab/orange3#6769]
Similar issue to https://github.com/jupyter/notebook/issues/4892

**Comment by janezd** [comment]
Per https://docs.python.org/3/library/sys_path_init.html, the first directory in `sys.path` is the current directory (when started with `-m`, otherwise the directory of the current script). It would seem safe to remove it, e.g. by putting `del sys.path[0]` in `__main__`.

I tried and it doesn't seem to cause any problems. Does anybody, in particular @ales-erjavec, see any problem?

**Comment by ales-erjavec** [comment]
In Python 3.11 there is a `python -P` | `PYTHONSAFEPATH=1 python` option which does not add those path entries. So the delete cannot be unconditional.

**Comment by ales-erjavec** [comment]
I think the only thing that should be done is use the `python -P` | `PYTHONSAFEPATH=1 python` in all of the application startup scripts/shortcuts like in https://github.com/biolab/orange3-installers/pull/52
