### ISSUE TITLE
Raise Exception in Python Script Widget but continue to trigger execution of next widget

### ISSUE THREAD

**Issue by foongminwong** [biolab/orange3#6782]
**What's wrong?**
I have a simple flow that contains a try-except block and link to another widget.

When the first Python Script Widget throws an Exception, why does it trigger the next widget to execute? 

Is there a way to disable the automatic execution of the next widget when an exception is thrown?

**How can we reproduce the problem?** 

![image](https://github.com/biolab/orange3/assets/23441795/13bbcec0-21b3-4259-8907-4466fdc35067)

**What's your environment?**

- Operating system: Windows 10
- Orange version: 3.36.2
- How you installed Orange: `pip install Orange3`

**Comment by janezd** [comment]
Widget's output cannot be "inactive". If the widget cannot produce data (due to an error or another reason), it needs to output `None`, it must not keep the pre-existing state. (If any widget does so, we consider it a bug.)

Therefore, in you exception handler, you need to set `out_object = None`. It will still trigger output, but with correct data. The following widget must then react accordingly.
