### ISSUE TITLE
Orange3 Widget Connection Error

### ISSUE THREAD

**Issue by JISEOP-P** [biolab/orange3#6814]
**What's wrong?**

I'm trying to create a classification model for dogs and cats, and I've connected it to the Test and Score widget to see which of the three models performs the best. However, the Test and Score and Confusion Matirx widgets are not connecting to each other. When I looked closely, I noticed that the percentages were rising and then stopping as the data was being passed to the models after embedding. Maybe this is why the Test and Score widget doesn't show any information about the models, but when I connected the models to the Predictions widget, the models performed well. What could be the reason for this disconnect?
![스크린샷 2024-05-31 071926](https://github.com/biolab/orange3/assets/171295619/efcf31f1-5088-4f78-9769-7a453c6c22f0)

The logs below were pulled just in case - could this be the reason?

C:\Program Files\Orange\lib\site-packages\orangewidget\gui.py:2068: UserWarning: decorate OWNNLearner.apply with @gui.deferred and then explicitly call apply.now or apply.deferred.
  warnings.warn(
C:\Program Files\Orange\lib\site-packages\orangewidget\gui.py:2068: UserWarning: decorate OWKNNLearner.apply with @gui.deferred and then explicitly call apply.now or apply.deferred.
  warnings.warn(
C:\Program Files\Orange\lib\site-packages\orangewidget\gui.py:2068: UserWarning: decorate OWLogisticRegression.apply with @gui.deferred and then explicitly call apply.now or apply.deferred.
  warnings.warn(
[archive.zip](https://github.com/user-attachments/files/15506429/archive.zip)

**How can we reproduce the problem?** 

[archive.zip](https://github.com/user-attachments/files/15506429/archive.zip)

Import the train folder into the top import widget and the test folder into the bottom widget.

**What's your environment?**

- Operating system: windows 11
- Orange version: 3.36.2
- How you installed Orange: Official website

**Comment by janezd** [comment]
Test and Score widgets needs learning algorithms and data. You only provided the algorithms, but not the data.

Widgets like Logistic Regression have two outputs. One gives the learning algorithms (with hyperparameters, such as regularization) that you set in the widget. The other is a trained model, that is, a model built from the data provided to the widget. The second output is only active if the widget receives the data. In your case, it does.

However, Test and Score *cannot* used a trained model, it needs a learning algorithm. Test and Score does cross-validation, or testing on separate test data or something similar. Test and Score takes the training data, uses the provided *learning algorithm* to create a model and then tests this model on testing data.

So if you double-click the connection between any of the three learning algorithms and Test and Score you'll see this:

![Screenshot 2024-06-06 at 17 43 53](https://github.com/biolab/orange3/assets/2387315/ffaf0939-7f0a-4f98-93aa-de4ef3d26843)

Since Test and Score does not use the Model, you do not need to give those three widgets the data. On the other hand, data needs to go to Test and Score. The proper workflow is

![Screenshot 2024-06-06 at 17 49 03](https://github.com/biolab/orange3/assets/2387315/54478931-2248-466e-a233-50625d0e6a21)

If you wish, you can keep the connections between Image Embedding and learners, but they won't have any effect in your case.

See the [documentation](https://orangedatamining.com/widget-catalog/evaluate/testandscore/).
