### ISSUE TITLE
Orange3 version 3.37.0 of the graph_ranks function is replaced by what

### ISSUE THREAD

**Issue by CandB1314** [biolab/orange3#6835]
**What's wrong?**

**How can we reproduce the problem?** 

**What's your environment?**

- Operating system:
- Orange version:
- How you installed Orange:

**Comment by markotoplak** [comment]
It was gone in #6062 because it caused problems with the tests and nothing within Orange (as an app) used it.

I honestly had no idea that this code was being used anywhere. If you wish to use it, just copy the corresponding code from the old version: https://github.com/biolab/orange3/blob/3.32.0/Orange/evaluation/scoring.py
