### ISSUE TITLE
qt.svg: Cannot open file '<local path>/canvas_icons:/Dropdown.svg'

### ISSUE THREAD

**Issue by Alex72RM** [biolab/orange3#6837]
When trying to run the env with "python -m Orange.canvas", this alert arises:

qt.svg: Cannot open file '<local path>/canvas_icons:/Dropdown.svg', because: La sintassi del nome del file, della directory o del volume non ? corretta. 

(in english: file name syntax, directory or volume is wrong)

**What's wrong?**

**How can we reproduce the problem?** 

**What's your environment?**

- Operating system:
- Orange version:
- How you installed Orange:

**Comment by yanuino** [comment]
Same problem.
`qt.svg: Cannot open file 'C:/Users/y*********e/AppData/Local/miniconda3/canvas_icons:/Dropdown.svg', because: La syntaxe du nom de fichier, de r?pertoire ou de volume est incorrecte.`

**How can we reproduce the problem?**
Launch  `orange-canvas.exe` or `python -m Orange.canvas`

- Operating system: Windows 10
- Orange version: 3.37.0
- How you installed Orange: from conda-forge channel with miniconda (Conda 24.3.0 and Python 3.11.9)

**Comment by sankarsh-ravi** [comment]
I am also experiencing the same issue. Can someone help?

**Comment by markotoplak** [comment]
I also see the same warning. Did you notice any other consequences? To me, orange seems to behave normally.
