### ISSUE TITLE
Box Plot: add attribute name to the plot

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#6863]
**What's your use case?**
Trying to export an image in Box Plot, there is no attribute name reported. E.g. I see no "sepal length" anywhere in the plot, leading me to guess what was the variable used.
<img width="594" alt="iris" src="https://github.com/user-attachments/assets/24ce0ead-e35a-4cce-9846-449307efc625">

**What's your proposed solution?**
Add variable name at the top of the plot. Hopefully, the category names reveal enough about the subgroup used. If not, we would have to think about this, too.
p.s. All other visualization widget include variable name.

**Are there any alternative solutions?**
Use Inkscape to add it, but this is a bit silly.

**Comment by janezd** [comment]
Other visualizations include the name of the variable as a part of the plot, e.g. the name of the axis, never as a title. (If you find such case, tell me and I'll fix it. :) Hence I'd vote against putting the name at the top.

A solution consistent with other widgets would be to label the axis.

<img width="573" alt="Screenshot 2024-08-23 at 19 19 30" src="https://github.com/user-attachments/assets/c5261bf7-6de0-4a4b-a2b6-2f906b86fc56">

I prepared a PR (#6882), but I don't like it much because the user knows which attribute he is plotting - when using Orange. Preparing a plot for publication would, in my opinion, always require a touch of Inkscape, Illustrator or, if I may suggest, Affinity Designer.

You may argue that I could use the same argument against showing variable names in scatter plot, sieve and mosaic. Yes, but there it at least (re)shows what is shown horizontally and what is shown vertically (not to mention having four variables in mosaic), while here I think the ink-to-information ratio is low.

**Comment by markotoplak** [comment]
I think adding a feature name helps if you want to observe multiple widgets at the same time and thus, to save screen estate, you hide control panes. I often do this in workshops. Having no name there can be problematic.

What bothers me more is the positioning of the score. Even if we decide not to merge this PR, it should go away from the value axis, like to the top. Having it near the axis is confusing.

**Comment by janezd** [comment]
Left-align the ANOVA line.

**Comment by janezd** [comment]
OK?

<img width="799" alt="Screenshot 2024-09-12 at 15 51 37" src="https://github.com/user-attachments/assets/7daf3f77-9516-4cdc-9830-50f508d43c2b">
