### ISSUE TITLE
New widget - set .attributes of a feature or Table

### ISSUE THREAD

**Issue by borondics** [biolab/orange3#6919]
**What's your use case?**

We are using attributes more and more to carry information about the dataset. However, it doesn't seem possible to add new attributes from inside Orange. This becomes a problem if the necessary fields are not populated for any reason.

**What's your proposed solution?**

It would be great to have an **`Add attribute`** widget, where the user would specify the name of the attribute and then the value (string).

**Are there any alternative solutions?**

One can edit files but in that case they would need to conform to the individual file structure.

**Comment by ajdapretnar** [comment]
Like a mash-up between Formula and Create Table?

**Comment by borondics** [comment]
Actually, it could be a feature addition to Formula but it would insert information into the Table or the Feature attributes...

**Comment by markotoplak** [comment]
Setting `.attributes` of a `Variable` would go into Edit domain.

Setting `.attributes` of a `Table` (as shown in Data Info). No idea. We only used these internally for now (for example setting species in bioinformatics add-on). I am not sure exposing them makes much sense.

An alternative here is to use the Python script widget when needed.

**Comment by markotoplak** [comment]
Setting `.attributes` manually should never be necessary.

In Bioinformatics, they ere designed so that if a user selects a specific species in one widget, other widgets will use that as a default. So, `.attributes` were used as something optional and not functionally necessary.

If `.attributes` are required I think a custom widget for setting them is in order, like As fairness data from the Fairness add-on. In such cases, values should be carefully crafted so that they are valid (and they are not limited to strings anyway).

So I'd say this is a wontfix. If anyone needs them, there should be a custom setter widget.
