### ISSUE TITLE
HDF5

### ISSUE THREAD

**Issue by Twizzledrizzle** [biolab/orange3#945]
Have been looking around if it is possible to have a HDF5 file as input, could not find it as a selectable option. Is this possible with any of the widgets?

http://pandas.pydata.org/pandas-docs/stable/io.html#io-hdf5

**Comment by kernc** [comment]
It's not yet possible with any of the widgets afaik, but we might be interested to support it with the optional dependency on h5py lib. However, since HDF5 files can contain multiple datasets and since Orange is not yet so well-suited to handling gigabytes of data in any way, there may be several obstacles to overcome.

Would you like to help us with a pull-request? :smiley:

**Comment by lanzagar** [comment]
This was considered some time ago, but was not followed up (yet) as some of the encountered questions still need discussion and answers (e.g. what to do with more than 2-dimensional arrays).

Interest in this might be restarted in a couple of months, but until then you can use the prototype add-on that adds a widget for opening HDF5 files. Be warned it is not actively maintained.

https://github.com/lanzagar/orange3-hdf5

**Comment by Twizzledrizzle** [comment]
I will check it out thank you!

I am interested in this because most of our data is merged from lots of different csvs (many with different delimiters etc), then put in h5 files with 'cleaned' data.

And this package looked like a nice visualization tool for the ones at office not so keen on writing scripts/programming!

**Comment by janezd** [comment]
Issue moved to #4090.
